### ISSUE TITLE
Wrong viewport calculation when padding-x and padding-y = 0

### ISSUE THREAD

**Issue by lucasew** [raphamorim/rio#100]
Note the black horizontal borders and that it's eating up a bit of the vertical area on the right side.

I'm using the WIP package from otavio in nixpkgs

![image](https://github.com/raphamorim/rio/assets/15693688/d6673301-cc67-4c9d-9b17-4234648098ea)

**Comment by raphamorim** [comment]
Hey there @lucasew , thanks for the issue. The padding-y I've pushed a fix for it in the latest main, could you please try it?

For padding-y issue, is the same we have for macos regarding font width dimensions (Ref: https://github.com/raphamorim/rio/issues/88). I plan to fix it before release the upcoming version.

Also, there's an issue in wayland for initial width recognition (#98) might be related as well.

**Comment by otavio** [comment]
I think it is fixed. @lucasew I sent the update to nixpkgs PR.

**Comment by lucasew** [comment]
On f3fbe7a020528d2f5ed8beaa3afd900a4c2e83a2

BTW the hot reload is a nice touch tho

![image](https://github.com/raphamorim/rio/assets/15693688/97b4ec04-4167-4396-a895-d2ef5a058278)

![image](https://github.com/raphamorim/rio/assets/15693688/f67be60a-dc28-4702-a756-3c7a7ce5b7ce)

**Comment by raphamorim** [comment]
That's great @lucasew @otavio .

I will close this issue for now, regarding the overflow issue that has sometimes (depends of the width and font used) I will fix soon but will keep track in the #88 issue (considering is a duplicated).

<img width="130" alt="Screenshot 2023-06-18 at 22 46 46" src="https://github.com/raphamorim/rio/assets/3630346/f360acc6-0a3c-40d6-b51f-27e752a99166">

Thank you for reporting it 🙏
