### ISSUE TITLE
tmux pane: “leaking information” at the time of re-rendering

### ISSUE THREAD

**Issue by avelino** [raphamorim/rio#103]
when it is in a long build that generates a lot of stdout the output is "leaking" into another tmux pane

**video:**

https://github.com/raphamorim/rio/assets/31996/12e1a984-edd8-4cdb-a826-c3dea415ab83

**Comment by raphamorim** [comment]
Hey @avelino, the video isn't working properly for me when I try to open it.

<img width="693" alt="Screenshot 2023-06-24 at 19 28 20" src="https://github.com/raphamorim/rio/assets/3630346/648884ab-6445-4f84-b2e8-72e8a3108f1c">

**Comment by avelino** [comment]
> Hey @avelino, the video isn't working properly for me when I try to open it.

@raphamorim sorry, upgrade new video

**Comment by raphamorim** [comment]
Fixed in v0.0.14
