### ISSUE TITLE
Distribution for Linux .deb and .rpm

### ISSUE THREAD

**Issue by avelino** [raphamorim/rio#105]
- [x] `.deb` https://crates.io/crates/cargo-deb
- [ ] `.rpm` https://github.com/cat-in-136/cargo-generate-rpm

**Comment by raphamorim** [comment]
Related https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038757

**Comment by raphamorim** [comment]
Regarding this issue and #106 , not sure if it will be part of Rio GH pipeline to distribute. I like how alacritty does https://github.com/alacritty/alacritty/releases (although kitty is more complete in this sense https://github.com/kovidgoyal/kitty/releases/tag/v0.28.1)

**Comment by raphamorim** [comment]
Nowaday the Arch linux package is also not part of Rio GH pipeline but maintained by external parts https://aur.archlinux.org/packages/rio

**Comment by raphamorim** [comment]
Updated the issue description to centralize .rpm and .deb discussions.

**Comment by raphamorim** [comment]
.deb with GH architecture ✅ 

<img width="426" alt="Screenshot 2023-07-15 at 11 48 37" src="https://github.com/raphamorim/rio/assets/3630346/cd0ab95b-8a00-433f-97ff-11f6ef9d030d">
<img width="1210" alt="Screenshot 2023-07-15 at 12 33 11" src="https://github.com/raphamorim/rio/assets/3630346/f3f2432c-a9a8-4b60-8477-18abff732cf0">

**Comment by androw** [comment]
I've packaged rio for OpenSuse: https://build.opensuse.org/package/show/X11:terminals/rioterm

**Comment by raphamorim** [comment]
> I've packaged rio for OpenSuse: https://build.opensuse.org/package/show/X11:terminals/rioterm

That's great @androw ! thanks for doing it

**Comment by raphamorim** [comment]
Not sure if I am keen to do it anymore inside of Rio pipeline, starting to believe the way alacritty does (more decentralized) is better. Closing this ticket for now.
