### ISSUE TITLE
Font ligatures feature as an option

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#108]
A ligature is a [glyph](https://fonts.google.com/knowledge/glossary/glyph) that combines the shapes of certain sequences of [characters](https://fonts.google.com/knowledge/glossary/character) into a new form that makes for a more harmonious [reading](https://fonts.google.com/knowledge/glossary/readability) experience. A common example is the “fi” ligature, which combines a lowercase “f” and a lowercase “i” into a single glyph so that the shoulder of the f doesn’t clash with the dot of the i.

Ref: https://fonts.google.com/knowledge/glossary/ligature

**Comment by raphamorim** [comment]
I've worked briefly on it and so far it increases the performance negatively in a significant way. At some moment I do plan to return on this issue but if anyone would like to work on it and make as an option feel free to take it.

**Comment by inudev5** [comment]
hello @raphamorim , are there any commits or PRs related to this? i might look at it.

**Comment by raphamorim** [comment]
That would be awesome @inudev5 ! ⭐ 
Please let me know if I can help somehow with it

**Comment by inudev5** [comment]
> I've worked briefly on it and so far it increases the performance negatively in a significant way. At some moment I do plan to return on this issue but if anyone would like to work on it and make as an option feel free to take it.

is the work you mentioned here not commited? was hoping to check on the work and start from there.

**Comment by raphamorim** [comment]
I've originally started to work on it in this branch https://github.com/raphamorim/rio/tree/migrate-cosmic-text

But then gave because the performance from sugarloaf to cosmic-text even without ligatures was really slow for a terminal. Then decided to stick with rio renderer (sugarloaf) and add the support there but opt-in so doesn't affect people that doesn't want to use font ligature.

**Comment by raphamorim** [comment]
So probably if you would like to implement it on sugarloaf would need to verify/study possibilities of font shaping like https://github.com/RazrFalcon/rustybuzz and integrate with the existent code

**Comment by inudev5** [comment]
@raphamorim thanks! i will look into it.

**Comment by zackartz** [comment]
@inudev3 How had this been going? I would be available to help if you would like

**Comment by inudev3** [comment]
@zackartz i couldnt really get the hang of it because of my job. any help would be appreciated.

**Comment by zackartz** [comment]
@inudev3 gotcha, i'll take a look at it!

**Comment by raphamorim** [comment]
Initial support was added in #428 , however will need a followup PR to stabilize performance and force monospaced dimensions. Will add more info about it in the 0.1.0 release note.
