### ISSUE TITLE
Ability to in|decrease font size using keyboard shortcut during session

### ISSUE THREAD

**Issue by mies** [raphamorim/rio#109]
Other terminals support a keyboard shortcut such as `Command - Shift - +` in order to inscrease (or decrease) the font size during a session, would be very nice if Rio supports this as well.

**Comment by raphamorim** [comment]
Changes introduced in the canary build (also with reset font-size) 

![font-change-by-keyevents](https://github.com/raphamorim/rio/assets/3630346/4b201d2b-388b-4423-b2bc-9bbd5bceb73b)
