### ISSUE TITLE
[BUG] black screen with nearly zero interactivity

### ISSUE THREAD

**Issue by FallenValkyrie** [raphamorim/rio#112]
So i'm switching over from kitty and i really like the premise, but when installing, all it shows is what's shown in the image. It never does anything else, it just hangs on that 

**OS**: EndeavourOS (Basically pre-configured archlinux)
**WM**: KDE Plasma (Wayland)
**Shell**: nushell (dunno if important)
**Install Method**: tried both AUR and building from source according to the install instructions here: https://raphamorim.io/rio/install/#linux
**Questions**:
is this a me-issue (as in, i did something wrong)? 
Is this easily fixable, if yes, how can i do that?

![image](https://github.com/raphamorim/rio/assets/42149402/432f471c-21ac-4a55-b472-25c6566bb67b)

Conversation on discord: https://discord.com/channels/1110689408962789386/1110689785896501289/1124383434765238302

**Comment by raphamorim** [comment]
@FallenValkyrie thanks for the issue, which shell are you using?

**Comment by FallenValkyrie** [comment]
> @FallenValkyrie thanks for the issue, which shell are you using?

@raphamorim i use kitty as shell ^^

**Comment by raphamorim** [comment]
@FallenValkyrie can you try with latest main?

I was able to reproduce and pushed a fix for it today.

**Comment by raphamorim** [comment]
Tested in EndeavourOS before and after the fix, can confirm it fixed. I will close this issue but anything let me know and we can reopen.

**Comment by FallenValkyrie** [comment]
checked with 0.0.8 on AUR and latest main, using `cargo build --release --no-default-features --features=wayland` to compile, but i got the same results.

could it maybe be the prompt i'm using? 
I'm using the `Starship` prompt together with `nushell` and maybe it's worth mentioning that i'm also using `rtx-cli`, a rust runtime manager similar to asdf, in case that matters.

i'll attach the config files in a gzipped tarball. 
**NOTE:**  you should change the use and source statements at the bottom of the `config.nu` file, i cannot set those dynamically, sorry for that, but this allows to have identical.

just in case: `tar -zxvf [path]` to unpack 

## extra info: 
### `starship --version`:
```
starship 1.15.0
tag:v1.15.0
commit_hash:
build_time:2023-06-06 15:23:26 +00:00
build_env:rustc 1.70.0 (90c541806 2023-05-31) (Arch Linux rust 1:1.70.0-1),
```

### `nu --version`
```
0.82.0
```

### `rio --version` (AUR version)
```
rio 0.0.8
```
[configurations.tar.gz](https://github.com/raphamorim/rio/files/12032512/configurations.tar.gz)

**Comment by FallenValkyrie** [comment]
from what i can see, no file logging has been set up, i can maybe do that in a future PR, but for now i won't be available for at least a week, because i'll be moving to a new place. 
Will try to answer any additional questions that come up asap ^^

**Comment by raphamorim** [comment]
Hey @FallenValkyrie thank you very much for the input and details. Ok, reopening the issue and

**Comment by raphamorim** [comment]
Will give a try of the nushell to debug as well and no worries! Good lick with the moving 🙏 📦

**Comment by FallenValkyrie** [comment]
I just tested the current AUR version [0.0.16] (just because i happened to see it in the update) and it mostly works.

There are some character alignment issues (see below) and i cannot maximise the window (wayland plasma, use maximise button), but beyond that, it is now responsive and actually takes input and renders the prompt ^^
![image](https://github.com/raphamorim/rio/assets/42149402/2c9d2c4c-358f-49c3-85d0-4d3613d35ed0)

following this, i suggest we close this issue, and count it as solved ^^

**Comment by raphamorim** [comment]
Niiiice! happy that is working now.
Regarding the character alignment there's other open issues about it. Will be closing this issue, thank you for testing it.
