### ISSUE TITLE
macOS Standard Tab Switching Keybindings

### ISSUE THREAD

**Issue by destructobeam** [raphamorim/rio#116]
Hi there, great work so far, thanks for putting your time in to it!

Would it be possible to add the (Mac) standard `Cmd+{` and `Cmd+}` keybindings for tab previous and tab next respectively on macOS?

**Comment by raphamorim** [comment]
Hey there @destructobeam, thanks for bringing it up. I wrote the bindings based on Hyper, Terminal.app and Firefox (control+tab). Tried to use `Cmd+{` and `Cmd+}` in some apps I use, it didn't switched tabs. Could you exemplify which app uses that?

Also, fyi I have been thinking about add the custom keybindings in this version (v0.0.9) so you could specify which keys should do.

**Comment by destructobeam** [comment]
Hi @raphamorim, I'm pretty sure it's a standard macOS keybinding, it's the default in Finder, Safari, Terminal, Messages, etc. Not sure about Hyper or Firefox though.

Cool, custom keybindings in the config would definitely sort that also. Might be nice as the default for Mac users new to Rio though.

Thanks!

**Comment by mies** [comment]
Hey @raphamorim and @destructobeam +1 for custom keybindings (and maybe indeed provide a sensible default for certain operating systems 🤔 ). The behavior is indeed standard for mac tab switching (also Firefox). Terminals such as iterm, kitty and wezterm also use it for tab switching.

**Comment by raphamorim** [comment]
I will close this issue as @mies mentioned is the default for the terminals in the MacOS, but @destructobeam created #117 to address it, so you can specify what keys you want to use.

**Comment by destructobeam** [comment]
Sorry @raphamorim, I might be misunderstanding, but wouldn’t these (#116 and #117) two issues be seperate (but also your project so manage as you like)?

1. The defaults per OS in Rust(?)
2. The configuration file for optionally specifying overrides of those defaults

Thanks!

**Comment by raphamorim** [comment]
@destructobeam we do already have defaults bindings per OS, for example, the tab keys for Windows and OSX are different.

Even that `Cmd+{` and `Cmd+}` works for Finder, Safari, Messages. Isn't the default for example Apple Terminal.app (`option+tab`) or even in other terminals running in macos, so following that principle I don't think it would be implemented in Rio that way (as a default).

So that's why I closed the issue, which leads to the only option of overriding defaults (#117).

**Comment by destructobeam** [comment]
@raphamorim Oh I thought he said it was, Cmd+{/} always has been the default on my machines in Terminal.app.

Maybe you are thinking of tab cycling versus tab previous and tab next which I mean?

**Comment by raphamorim** [comment]
I meant about the next/prev. Does Cmd+} or } works in your terminal.app to move next/previous tab? (For me it doesn’t work)

**Comment by destructobeam** [comment]
@raphamorim Yup, `Cmd+{` and `Cmd+}` work in Terminal.app, and I checked my system preferences and had no custom bindings set up.

I also just downloaded Kitty, and the those keybindings work to go next/previous tab in a default Kitty install as well.

**Comment by raphamorim** [comment]
hmm interesting, which keyboard layout you have @destructobeam ?

Would be good to understand why works for your case and not mine before decide to implement it.

**Comment by destructobeam** [comment]
@raphamorim Updated my last comment with relevant link. I’m using an Apple MacBook Pro with the US keyboard.
