### ISSUE TITLE
Various compilation errors for Void Linux targets

### ISSUE THREAD

**Issue by tranzystorek-io** [raphamorim/rio#119]
I created a PR for packaging `rio` in Void Linux, but there are some platforms in CI that currently fail to build: https://github.com/void-linux/void-packages/actions/runs/5456064996/jobs/9928361076?pr=44823

Seeing as some of the errors point to windows crates, some Cargo.toml platform selections might be incorrectly specified, but I haven't had time to check what precisely.

**Comment by raphamorim** [comment]
Thanks for the issue @tranzystorek-io 
Hmm, musl libc does not provide c_ispeed and c_ospeed fields in struct termios. I pushed a fix for musl, could you check if it works?

**Comment by tranzystorek-io** [comment]
I'll make a patch and see in a bit

**Comment by raphamorim** [comment]
Added a last commit (a3252d4c59d2f954c5c824e30eb6b4864f8dbbd8) that also will skip building windows crate for non-windows targets.

**Comment by raphamorim** [comment]
Also added 33227bae58ba358115e1e4d31d067e30799831c3 to fix it

**Comment by raphamorim** [comment]
The build has passed in https://github.com/void-linux/void-packages/pull/44823 , closing this issue @tranzystorek-io . Thanks for bringing it up.
