### ISSUE TITLE
Add selection color to the theme config

### ISSUE THREAD

**Issue by tranzystorek-io** [raphamorim/rio#125]
Looking at a typical terminal color template like: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/README.md#how-to-add-new-template

rio is missing at least a `selection` field in the `[colors]` config,

To consider if cursor text color and selection text color are desired as well.

**Comment by raphamorim** [comment]
For this issue would recommend 3 new properties for theme configuration:

```
selection-foreground = "000000"
selection-background = "000000"
selection-cursor = "000000"
```

**Comment by tranzystorek-io** [comment]
`selection-cursor` seems unnecessary - typically a user probably won't care enough

**Comment by raphamorim** [comment]
Yeah but is no brainer to implement, so rather keep as personalisation option (it can just inherits the cursor color if is not set)

**Comment by raphamorim** [comment]
Hmm, to avoid complexity ignored the selection-cursor as you suggested.

Implemented in 

![Screenshot 2023-07-07 at 14 35 00](https://github.com/raphamorim/rio/assets/3630346/eb0410ca-a623-441a-ae8a-7ab4cf95d09d)
![Screenshot 2023-07-07 at 14 35 08](https://github.com/raphamorim/rio/assets/3630346/45813837-c993-4118-a892-b53560d3a494)
