### ISSUE TITLE
Add option to set custom preset colors to tabs

### ISSUE THREAD

**Issue by chad-st** [raphamorim/rio#134]
For references: https://superuser.com/questions/403650/programmatically-set-the-color-of-a-tab-in-iterm2
https://gitlab.com/gnachman/iterm2/-/issues/7649

A simple ability of right clicking the tab on the top right and choosing from a preset list of colors would be a great first step.

The use case is I have certain tabs I designate for specific purposes: e.g. running a docker process or container.  This tab I generally color green to easily switch back to it.

**Comment by raphamorim** [comment]
Hey there @chad-st , I have implemented custom preset colors to tabs in the main, although is automated colors and not manually.

```toml
[navigation]
color-automation = [
  { program = "nvim", color = "#FFFF00" }
]
```

<img width="891" alt="Screenshot 2023-07-31 at 13 32 10" src="https://github.com/raphamorim/rio/assets/3630346/eb4b9f80-da5c-425f-84da-a595d8352953">
