### ISSUE TITLE
Glyph not rendered in prompt

### ISSUE THREAD

**Issue by ralgozino** [raphamorim/rio#135]
My prompt uses `❯` to indicate previously ran commands, but Rio doesn't render it correctly. Here are two screenshots comparing Rio and iTerm2
<img width="1059" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/ca4ebbfc-b890-46ee-bda0-7a86c6b573ba">
<img width="850" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/2e5bf2f9-e168-46d1-8180-078d8f4df808">

System:
- Rio v0.0.8 installed via brew
- powerlevel10k
- oh-my-zsh
- macos
- Victor Mono Nerd Font

**Comment by ehjmx** [comment]
Reading this I think that the issue I was about to open is about the same problem.

wezterm @20230712-072601-f4abf8fd using Fira Code and lsd-ls https://github.com/lsd-rs/lsd 

shows the glyphs
<img width="988" alt="Bildschirmfoto 2023-07-16 um 10 16 17" src="https://github.com/raphamorim/rio/assets/75489369/fc27525b-b7eb-4aa1-9001-17d8088b5cfb">

rio 0.0.9 using FiraCode Nerd Font and lsd-ls 
does not show the glyphs
<img width="1025" alt="Bildschirmfoto 2023-07-16 um 10 20 16" src="https://github.com/raphamorim/rio/assets/75489369/6fc22fdd-f01d-4fd6-9c80-e1d05ca4436a">

rio 0.0.9 using Fira Code and lsd-ls 
also doesn't show the glyphs but the output is closer to the one of wezterm
<img width="1022" alt="Bildschirmfoto 2023-07-16 um 10 21 25" src="https://github.com/raphamorim/rio/assets/75489369/fcb9bb83-e3d6-40d1-b093-b0d22a40c3f8">

Rio 0.0.9 downloaded from github
bash-it and powerline_prompt enabled
bash 5.2.15 via macports
Fira Code v 6.2

Thanks for already adding this to the wishlist.

**Comment by raphamorim** [comment]
Still fixing few things on main but pushed some improvements for font loader. Could you check how is going ? @ralgozino @ehjmx

**Comment by ralgozino** [comment]
Hi @raphamorim 

The glyph now appears, so in my case I consider it solved 🎉 

<img width="984" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/eb93d240-c483-4194-a7d8-cb4930eb6b81">

**Comment by ehjmx** [comment]
I can confirm that the symbols appear. In addition pure Fira Code can now be used. The patched Nerd font isn't necessary any longer. 
<img width="854" alt="Bildschirmfoto 2023-07-17 um 19 57 59" src="https://github.com/raphamorim/rio/assets/75489369/abbeca77-3361-459f-892e-d6564c59b9a3">
However if you compare the above Fira Code to Victor Mono below
<img width="854" alt="Bildschirmfoto 2023-07-17 um 20 00 50" src="https://github.com/raphamorim/rio/assets/75489369/d566f813-d032-4305-a52a-8a2a20b73b62">
You can see that when a new powerline segment begins Fira Code has more offset and color issues than Victor Mono. Shall I open a new issue for that?
