### ISSUE TITLE
Setting to change underline heaviness

### ISSUE THREAD

**Issue by ralgozino** [raphamorim/rio#136]
Rio v0.0.8 uses a too-heavy (for my taste) underline, I'd like an option to change it to something more thin, the default in iTerm2 for example is something I'd like to achieve.

See the underlined filename in the following screenshots comparing Rio and iTerm2

<img width="850" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/4e7ba357-d75d-4299-8b4b-8bed634f021d">
<img width="1059" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/a4762641-424c-435a-9890-98933ec5e471">

**Comment by raphamorim** [comment]
Actually it was a bug, it was using modifier based on scale, can you try again with latest main?

<img width="297" alt="Screenshot 2023-07-17 at 16 47 55" src="https://github.com/raphamorim/rio/assets/3630346/7490d5a2-179f-42e1-b7e6-ad48e591964b">

**Comment by ralgozino** [comment]
Now it is much better!
<img width="377" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/d1810446-a7e5-4d92-a19e-3b2b46c5d0ea">

But, if you compare it with iTerm2, the underline is closer to the letters in Rio. Can we add a "margin" between the letters and the underline?

**Comment by raphamorim** [comment]
As we talked in the discord, will add a fix for the margin along with #138 . Thanks for the issue and testing it
