### ISSUE TITLE
Support for blinking cursor

### ISSUE THREAD

**Issue by ralgozino** [raphamorim/rio#137]
I'd like to be able to make the cursor blink, it is easier to identify the current focused input and the cursor position when it blinks.

<insert 🦖 meme about stayin' still>

**Comment by bnwa** [comment]
+1 I _cannot_ see the cursor regardless of the enumerated shape

**Comment by raphamorim** [comment]
Support to blinking cursor added to main

![blinking](https://github.com/raphamorim/rio/assets/3630346/9f143e9e-a5e3-4d0c-ae97-725ce7e118c1)
