### ISSUE TITLE
Support for line height 

### ISSUE THREAD

**Issue by mhartington** [raphamorim/rio#138]
With terminals like iterm2/alacrity, you can set the line height for a font to increase the vertical spacing. I took a look through the config docs and the source here, but it doesn't seem like there's a setting exposed to support this. 

Would this be something you'd have interest in supporting? 

For example, here on the left is iterm with the line height increased. Compared to rio on the right. 
<img width="1915" alt="Screenshot 2023-07-14 at 10 43 37 AM" src="https://github.com/raphamorim/rio/assets/2835826/41b5abae-0867-4fd7-ab0a-fe3945f3828b">

**Comment by raphamorim** [comment]
Implemented the partial support to line-height, you can modify but it might affect the rect height with text aligned on top.

`line-height = 1.6`

<img width="712" alt="Screenshot 2024-01-12 at 12 15 57" src="https://github.com/raphamorim/rio/assets/3630346/2700741e-f2bd-4fd8-ada1-b5f54ae4b20c">

`line-height = 2.0`

![Screenshot 2024-01-12 at 12 14 28](https://github.com/raphamorim/rio/assets/3630346/8688b7e1-0916-45d3-a936-f9cfc2d1aa5f)

**Comment by raphamorim** [comment]
Closing it for now but will address the rect rendering as follow up
