### ISSUE TITLE
Font size configuration is confusing

### ISSUE THREAD

**Issue by tranzystorek-io** [raphamorim/rio#139]
Example: wezterm with font size `14.0` and rio with font size `22`:

![obraz](https://github.com/raphamorim/rio/assets/5671049/ac56431a-81d9-4386-80da-49fa208966a0)

According to discussion, this is due to rio interpretting the `font-size` setting as glyph scaling.

**Comment by raphamorim** [comment]
Thanks for the report.

Fixed at main

<img width="683" alt="Screenshot 2023-07-18 at 22 52 09" src="https://github.com/raphamorim/rio/assets/3630346/7a1b0442-0a0c-473b-b401-d42fda7ff7e9">
, should be patched in next release. Closing this issue
