### ISSUE TITLE
shell settings: default value via `$SHELL`

### ISSUE THREAD

**Issue by avelino** [raphamorim/rio#140]
There is an environment variable called `SHELL` that defines which shell I am using for the user (remembering that I can change the default shell of my user with `chsh`).

```sh
chsh -s /opt/homebrew/bin/fish
echo $SHELL # /opt/homebrew/bin/fish
```

Forcing `zsh` to **macOS** is horrible for those who use another shell by default, we are forcing the user to always configure the river shell, generating friction in the user experience.

**Release description [here](https://raphamorim.io/rio/release-0.0.9/#configuration-file-addition-shell):**
```
Configuration file addition: shell
Now you can set “shell.program” to the path of your favorite shell, e.g. “/bin/fish”.

Entries in “shell.args” are passed unmodified as arguments to the shell.

shell = { program = "/bin/zsh", args = ["--login"] }
Defaults:

MacOS: /bin/zsh –login
Linux/BSD: user login shell
Windows: powershell
```

**Comment by raphamorim** [comment]
@avelino In macOS Catalina, the default changed to the Z shell, also known as zsh. So it has been the default shell but I do understand what mean in terms can be exhausting for new users use Rio considering they need update the file.

Rio has a fallback for `$SHELL`, as we talked in the discord proceeded with the PR you made. Closing this issue
