### ISSUE TITLE
Improve Rio's window size management

### ISSUE THREAD

**Issue by ralgozino** [raphamorim/rio#143]
Rio starts up with a default window size that may not be the correct size for everybody.

For my use case, the default window size (with a retina display) is too small and I would get word-wrapping very quickly, see:
<img width="1792" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/62c66a32-3eca-444a-be75-7de27710d887">

I'd suggest:
- Making the window size configurable in the config file (optional)
- Remember the last used window size and reuse that

**Comment by raphamorim** [comment]
An idea of implementation is when Exit event is dispatched then save width/height in a file path (would change also per OS but could use temporary directories like `/tmp` and `/var/tmp`).

**Comment by ralgozino** [comment]
I gave a little more thought to this issue and I think a nice behaviour would be:

1. If there's a specified window size in the configuration file use that for new windows.
2. If there's no specified window size in the configuration file, fallback to the latest saved size
3. If there's no saved size fallback to a default (600x400 like now for example)

What do you think @raphamorim ?


My rust skills are ~0, but I've managed to add the `window-height and `window-width` parameters to Rio's configuration and fall back to a default value when they are not specified. It seems to be working :-)

You can see me opening Rio with the default size and then editing the configuration file with a custom size and reopening Rio:

[Kapture 2023-07-17 at 09.35.40.webm](https://github.com/raphamorim/rio/assets/6362698/13eab237-1847-47a5-be32-e1851934b3e1)

The next step would be to "save the last size" and use that if the size is not configured, I can't promise anything, it is a little out of my current rust skills 😄 

Here's my branch with the added configuration options:
https://github.com/ralgozino/rio/tree/configure-window-size

**Comment by raphamorim** [comment]
👍 good job @ralgozino ,

Would you mind create a PR?

> The next step would be to "save the last size" and use that if the size is not configured, I can't promise anything, it is a little out of my current rust skills 😄

Would be great add it as well, free feel to add a draft change and we can evolve it together

**Comment by ralgozino** [comment]
Opened draft PR

**Comment by raphamorim** [comment]
Have been thinking, do you think the window height/width solves your problem already? Asking because add the state file can add a bit of complexity to windows in terms of synchronize with right data. Then if it does already solve we can focus on the changes you have right now and close this issue.

**Comment by ralgozino** [comment]
For my use case, being able to set the window size solves it :-)

**Comment by raphamorim** [comment]
Coolio, if you want to explore the idea of save window width/height I am also ok with that 👌 
Maybe do in a follow-up PR/

**Comment by ralgozino** [comment]
perfect!

**Comment by raphamorim** [comment]
Merged, thanks @ralgozino 🥇
