### ISSUE TITLE
rio 0.0.9 behavior change

### ISSUE THREAD

**Issue by chenrui333** [raphamorim/rio#146]
While trying to upgrade rio to the latest release, we ran into some regression test failure as below:

```
$ /opt/homebrew/Cellar/rio/0.0.9/bin/rio --command 'echo 1'
Failed to spawn command 'echo 1': No such file or directory (os error 2)
```

relates to https://github.com/Homebrew/homebrew-core/pull/136624

**Comment by raphamorim** [comment]
The new version doesn't accept string as commands and `exit` isn't necessary anymore; So you could just run `rio --command echo e`

**Comment by chenrui333** [comment]
noted, thanks for confirming it is desired. Closing the issue now.
