### ISSUE TITLE
some symbols break the horizontal and vertical alignment of lines

### ISSUE THREAD

**Issue by ralgozino** [raphamorim/rio#148]
Displaying some symbols break the horizontal and vertical alignment of lines.

I noticed it using NERDTree in Vim which uses some symbols to display if folders are opened or closed and file icons.

Without NERDTree opened:
<img width="1113" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/c72a94f2-1560-471f-a2df-a8ccc5037653">
With NERDTree opened:
<img width="1113" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/5d7124d1-2a69-48eb-80c6-bb1ce8a65b63">

Notice how the vertical bar gets skewed and the line numbers are misaligned.

Opening and closing folders in NERDTree breaks different parts of the layout

**Comment by raphamorim** [comment]
Fixed in main, will be released in the next version

<img width="1095" alt="Screenshot 2023-07-18 at 19 15 24" src="https://github.com/raphamorim/rio/assets/3630346/a96bba5b-9005-41e5-ae4a-58f5a010287a">

Thank you for your report @ralgozino 🙏
