### ISSUE TITLE
Dragging the window up also scrolls the buffer

### ISSUE THREAD

**Issue by ralgozino** [raphamorim/rio#149]
If I drag Rio's window up, it also scrolls the buffer:

[Kapture 2023-07-17 at 18.57.16.webm](https://github.com/raphamorim/rio/assets/6362698/451e7681-1d5d-4663-b328-ed495b84a5a2)

I think that the problem may be that the title bar is considered part of the buffer maybe? notice how the cursor does not change when positioning it in the title bar, it stays as the text-selection cursor.

**Comment by raphamorim** [comment]
Closed in the v0.0.10, thanks for the bug report 🙏
