### ISSUE TITLE
fish doesn't work in v0.0.9

### ISSUE THREAD

**Issue by OlshaMB** [raphamorim/rio#151]
Fish is my default shell. I just recently updated to v0.0.9. But i got zsh in my shell.
I tried changing in the config but it also doesn't work. Also **fish is in `/etc/shells`**
![SCR-20230718-cljd](https://github.com/raphamorim/rio/assets/68439653/cc26bd51-cba2-4e54-9481-4b89ba2f0cb7)

**Comment by raphamorim** [comment]
Hey @OlshaMB , is related with #140 . The fix is in the canary release and will be released for next version.

One possible workaround to make it work in the version that you are using is simply leave shell.program empty, example

```toml
shell = { program = "", args= ["--login"] }
```

**Comment by raphamorim** [comment]
Closing this issue since is fixed in the main but please let me know anything.
