### ISSUE TITLE
0.0.11 - highlighting text seems to use the bottom of the cursor for selection

### ISSUE THREAD

**Issue by Jinkxed** [raphamorim/rio#156]

**Comment by ehjmx** [comment]
I can confirm this behavior. 
macOS 13.4.1 (c)
rio 0.0.11
bash-it
independent of the font used

**Comment by raphamorim** [comment]
Fixed in v0.0.12 https://github.com/raphamorim/rio/releases/tag/v0.0.12

Closing this issue for now, but anything let me know
