### ISSUE TITLE
Error in 'Version field' when installing .deb

### ISSUE THREAD

**Issue by DanielTolentino** [raphamorim/rio#158]
```
dpkg: error processing file rio_x11_amd64.deb (--install):
  interpreting the file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'rio':
  'Version' field with value 'x11': version number does not start with a digit
Errors were encountered while processing:
  rio_x11_amd64.deb
```

Debian 12 Bookworm xfce4
Method of installation: apt and/or dpkg

**Comment by raphamorim** [comment]
Hey @DanielTolentino , thank you for the issue. What's architecture of your machine? Is amd64, arm64, x86?

**Comment by DanielTolentino** [comment]
amd64

**Comment by raphamorim** [comment]
aaah
Sorry I read the error wrongly first time 🙈 😆 
Ok so the error is that the version is `x11` and it can't be `x11` as version. I thought it was ok use `x11` and `wayland` as version so the name would keep in the binary.

hmm, I can fix in the CI for the next canary.

**Comment by raphamorim** [comment]
Created and updated in https://github.com/raphamorim/rio/releases/tag/canary-b5210e2b9892f07d53ea842f086c74d8a063149a 👌

**Comment by DanielTolentino** [comment]
It's working!!! Thanks.
