### ISSUE TITLE
how to switch in terminal tabs?

### ISSUE THREAD

**Issue by frankyston** [raphamorim/rio#161]
On type CMD + T, opens new tab, but not to do navigation by their.

The terminal indicates by some colors on the right side as in the print below.

![Screenshot 2023-07-26 at 10 35 57](https://github.com/raphamorim/rio/assets/1836802/970348c9-31e4-4526-9dbe-89ae324f7016)

SO: OSx

**Comment by raphamorim** [comment]
Hey @frankyston thanks for the issue,

You can switch tabs using control+tab or command+} / command+{

https://raphamorim.io/rio/docs/key-bindings/#macos

You can also specify custom key bindings: https://raphamorim.io/rio/docs/custom-key-bindings/#custom-key-bindings
