### ISSUE TITLE
Add `Switch to tab with index` Action 

### ISSUE THREAD

**Issue by filipebarros** [raphamorim/rio#170]
Can we have a new action `Switch to tab with Index` that would allow users to create new mappings like

`CMD` + `1` => `SwitchToTabWithIndex(1)` or something like that. 

The use case is to be able to change to specific tabs instead of having to cycle through with `CMD|Shift` + `[` or `]`

**Comment by raphamorim** [comment]
I think would be good to have it, not as default key bindings but at least as action that someone could configure as whatever they want to.

**Comment by filipebarros** [comment]
Yes, I mean creating a new action like the existing ones (`TabSwitchNext` and `TabSwitchPrev`). With a new action like `TabSwitchIndex` we can then use the existing keybinding capabilities to create those

**Comment by raphamorim** [comment]
Added new actions for tab selection (implementation is similar to Firefox tab index keys): `SelectTab1`, `SelectTab2`, `SelectTab3`, `SelectTab4`, `SelectTab5`, `SelectTab6`, `SelectTab7`, `SelectTab8`, `SelectTab9`, `SelectLastTab`.

Coming for next version (0.0.17).

Ref: 8f33a1f
