### ISSUE TITLE
Debian package rio overwrites manually installed rio terminal .deb pkg

### ISSUE THREAD

**Issue by DanielTolentino** [raphamorim/rio#173]
There is a package called "rio" available in the Debian repositories, accessible through this link: [rio debian repo](https://packages.debian.org/bookworm/rio).

However, there is an issue when updating the system using 'sudo apt update'. When doing so, Debian will install the rio package from the repositories, but unfortunately, it removes the Rio terminal.
I think there's some workarounds, but this is the default behavior right now.

**Comment by raphamorim** [comment]
maybe we should rename the package to `rio-term` what do you think?

**Comment by DanielTolentino** [comment]
Makes sense, I've seen this convention in terminal apps.
