### ISSUE TITLE
`option_as_alt` does not really work

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#178]
### Discussed in https://github.com/raphamorim/rio/discussions/177

<div type='discussions-op-text'>

<sup>Originally posted by **srid** August  6, 2023</sup>
I tried both `'both'` and `'left'` as values but it has no effect. <kbd>Option+b</kbd> inserts `∫` and <kbd>Option+f</kbd> inserts `ƒ`.

Is there a way to solve this?</div>

**Comment by raphamorim** [comment]
Just tested and it's working for me using the follow configuration

```toml
option-as-alt = "Right"
```

or

```toml
option-as-alt = "left"
```

But the trick part is that whenever this configuration is updated needs to re-open the terminal. Think add a message regarding it would be the good. Closing it for now, let me know anything.

**Comment by raphamorim** [comment]
ah, also realized the docs were wrong, it was using `option_as_alt` instead of `option-as-alt`. Just fixed the docs

**Comment by srid** [comment]
> ah, also realized the docs were wrong, it was using `option_as_alt` instead of `option-as-alt`. Just fixed the docs

That worked for me.

**Comment by fdncred** [comment]
I can't get `option_as_alt` to work on macos. I've set it to left, both, and commented it out and they all work the same for me. I'm trying to do option/alt+s and I just get this character.

<img width="37" alt="image" src="https://github.com/raphamorim/rio/assets/343840/99013fa9-3ca3-4dbb-a16a-be0e0ef70f1c">
