### ISSUE TITLE
Split window

### ISSUE THREAD

**Issue by louismariegaborit** [raphamorim/rio#184]
Like iTerm2 or Terminator or Windows Terminal, could you add the window splitting horizontally and vertically functionality ?

**Comment by raphamorim** [comment]
Not yet but has been in my todo list for upcoming versions.

**Comment by raphamorim** [comment]
Fyi: I finally will start working on it. More info will update here

**Comment by raphamorim** [comment]
Initial support has been added on main branch (will do more adjusts before release) but will be patched in the next version

**Comment by raphamorim** [comment]
![image](https://github.com/user-attachments/assets/4c1ee130-3bce-42df-beec-1a38b52c9805)
