### ISSUE TITLE
Text not as sharp as other emulators

### ISSUE THREAD

**Issue by arminveres** [raphamorim/rio#185]
Hi there, I installed rio through
`cargo install --no-default-features --features=x11 --git https://github.com/raphamorim/rio` which works completely fine, I even configured it, as seen in my [dots](https://github.com/arminveres/dotfiles/tree/next/rio/.config/rio) but the text is quite unsharp in contrast to e.g., Kitty. Is there something I am missing? I am using the same font.
Left Rio, right Kitty
![image](https://github.com/raphamorim/rio/assets/45210978/9ad045cf-abaa-4fea-ad65-52625f2a36ac)
left Alacritty, right Rio
![image](https://github.com/raphamorim/rio/assets/45210978/b0c92474-bf21-4a36-9984-30051b29cdcd)

I am unsure if its my screen or nothing actually but the font looks a teensy bit blurred, at least for me.

Compiler: rustc 1.71.1
OS: Fedora 38
GPU: AMD Radeon RX 6900 XT

**Comment by colemickens** [comment]
It's quite a significant difference in legibility for me. I'd much rather use `rio` than `foot` but can't due to this.
![screenshot-1692583887](https://github.com/raphamorim/rio/assets/327028/ba3be71b-9b19-4906-8a47-245ad1c367e9)

(`foot` on the left, `rio` on the right)

**Comment by raphamorim** [comment]
I was going to say what @colemickens said, I prefer Rio as well but regarding the issue with Kitty is that Rio is selecting the font weight automatically hopefully it will be "fixed" by adding the support per configuration file, ref #150

**Comment by raphamorim** [comment]
@colemickens @arminveres could you check if is still the same in latest main?

Comparisson of kitty and rio now (but Rio different than kitty doesn't select the driver, think it could be connected for non-macos cases)

<img width="148" alt="Screenshot 2023-09-11 at 13 13 32" src="https://github.com/raphamorim/rio/assets/3630346/9c4cf79f-51f8-4c73-8f61-ab99c31d2ecd">
<img width="129" alt="Screenshot 2023-09-11 at 13 15 59" src="https://github.com/raphamorim/rio/assets/3630346/f04d6fba-7a69-498c-8a09-be0d3810ce24">
![Screenshot 2023-09-11 at 13 17 55](https://github.com/raphamorim/rio/assets/3630346/9531e6ac-4df3-499f-b96e-3cec7932da0f)

**Comment by arminveres** [comment]
@raphamorim Most fonts seem fine now from a sharpness standpoint, although DejaVuSansMono still isn't quite sharp yet. Also, nerd font/powerline symbols are not always displayed or displayed with spacings around each other.

See powerline symbol or nerd tree symbols. kitty above and rio below.
![image](https://github.com/raphamorim/rio/assets/45210978/76703c95-2510-40f4-9a73-484712e467d2)

**Comment by raphamorim** [comment]
Ok that's good to know. Thank you for testing it @arminveres 

> powerline symbol or nerd tree symbols

What was supposed to the rect icon there?

<img width="111" alt="Screenshot 2023-09-11 at 13 45 24" src="https://github.com/raphamorim/rio/assets/3630346/f8aa4d72-9694-4e13-98d3-563d9cc72811">

Btw I will be close this issue regarding the sharpness but the issue about the icons has another issue about it.

**Comment by arminveres** [comment]
Thank, a git branch symbol!

**Comment by raphamorim** [comment]
I see! like these ones right?

<img width="1509" alt="Screenshot 2023-09-11 at 13 49 47" src="https://github.com/raphamorim/rio/assets/3630346/862c9c18-1eb5-486d-8357-a05a9a8c2604">
