### ISSUE TITLE
'Backspace' keypress triggers Ctrl+h keybinding in Zellij instead of deleting character

### ISSUE THREAD

**Issue by tranzystorek-io** [raphamorim/rio#197]
As in title, tested in rio 0.0.18.

**Comment by raphamorim** [comment]
Interesting, download and installed Zellij and whenever I press backspace key it works as expected. Do you know if I am missing anything?

<img width="1108" alt="Screenshot 2023-08-31 at 07 39 51" src="https://github.com/raphamorim/rio/assets/3630346/52f64965-98ea-427b-87d4-e5c00cbe9fe1">

**Comment by colemickens** [comment]
I'm seeing the same thing with `0.0.18`.

**Comment by raphamorim** [comment]
You can also reproduce the issue @colemickens ?

What is your os?

**Comment by colemickens** [comment]
Yes, same issue exact issue, precisely with zellij.

OS is NixOS. Compositor is Sway, but I'm always running the very latest build of it.

**Comment by raphamorim** [comment]
@colemickens @tranzystorek-io can I also take the opportunity to ask to check if any other “basic” key is off in the zellij?

**Comment by tranzystorek-io** [comment]
Some more repro context:

- zellij versions tested: 0.37.2, 0.38.0
- environment: labwc 0.6.4 (wayland, wlroots)

> @colemickens @tranzystorek-io can I also take the opportunity to ask to check if any other “basic” key is off in the zellij?

Haven't found any more

**Comment by luccahuguet** [comment]
my case is the same

my setup:
![image](https://github.com/raphamorim/rio/assets/27565287/cd41cab1-6959-4859-9941-5a5468f2b7be)

**Comment by raphamorim** [comment]
Fixed in latest main, please let me know anything

**Comment by tranzystorek-io** [comment]
Thanks, I can confirm the issue is fixed for me in that commit

**Comment by luccahuguet** [comment]
it is working here as well! 

thanks for the blazingly fast fix, fellow Brazilian 👍🏼
