### ISSUE TITLE
Confirm before quitting

### ISSUE THREAD

**Issue by dinhtungdu** [raphamorim/rio#203]
First of all, thank you so much for Rio! It became my default terminal after 5 minutes.

I'm messy so I accidentally quit applications a lot. I searched through documentation and issues and I couldn't find a mention about this feature. So please consider this issue as a feature suggestion.

**Comment by raphamorim** [comment]
Implemented in main (coming to next version) but is necessary to use the configuration `confirm-before-quit`

![Screenshot 2023-11-13 at 11 01 36](https://github.com/raphamorim/rio/assets/3630346/8d01eb47-1a9f-48c2-8220-813a2fa1487d)
