### ISSUE TITLE
Weird border on nvim using light theme

### ISSUE THREAD

**Issue by marrcelo** [raphamorim/rio#204]
Hello, I'm using Rio with nvim with a light theme and getting this border.

Here is a comparison of the gnome-terminal and Rio.
  
![image](https://github.com/raphamorim/rio/assets/18054556/a5470552-8b89-48b0-a80f-a101cd68f400)

The border size changes when I resize the window.

I build the terminal based on the main branch and my configs are:
OS: Ubuntu 22.04.3 LTS x86_64 
DE: GNOME 42.9
Resolution: 3840x2160

**Comment by raphamorim** [comment]
Hey there @marrcelo thanks for the issue.

Rio has same border style as hyper terminal (the terminal is rendered with background border). I would recommend just set a background color as same nvim using themes or color property in the configuration file.

**Comment by marrcelo** [comment]
Aah, I didn't know about this hyper terminal border style. 

Thanks for the answer. 

Congrats on the work, Rio is great.

**Comment by raphamorim** [comment]
Thank you @marrcelo for the kind words.

I think your question gave me an idea to explore in the future like an adaptative background system that understands vi mode and replicate the vi background to the terminal.
