### ISSUE TITLE
keyboard shortcut for scroll up/down missing.

### ISSUE THREAD

**Issue by Dass99** [raphamorim/rio#206]
I noted that rio it does not have default keybinding to  scroll up/down, I looked it up in the documentation how to add a custom keybinding but there is no predefined action to do that. As a twms lover it would be great to have this functionality.

**Comment by raphamorim** [comment]
Agree! Is in progress to next version at least full scroll up and down actions.

**Comment by raphamorim** [comment]
Implemented ScrollPageUp, ScrollPageDown, ScrollHalfPageUp, ScrollHalfPageDown, ScrollToTop, ScrollToBottom, ScrollLineUp, ScrollLineDown in main branch
