### ISSUE TITLE
Failed to spawn command, no such file or directory

### ISSUE THREAD

**Issue by avelino** [raphamorim/rio#212]
```log
[ERROR] rio::screen::context Custom { kind: NotFound, error: "Failed to spawn command '/opt/homebrew/bin/fish': No such file or directory (os error 2)" }
```

River wasn't opening, after debugging I got this error

**Comment by raphamorim** [comment]
Next version will include an error treatment for whenever the command is not found ![Uploading Screenshot 2023-09-13 at 17.25.10.png…]()
