### ISSUE TITLE
Allow for a "simple mode" with no tabs, and no splits, for compatibility with terminal multiplexers like zellij

### ISSUE THREAD

**Issue by luccahuguet** [raphamorim/rio#213]
There are highly focused terminal emulators like alacritty that have no multiplexing features and thus allow high compatibility with terminal multiplexers like zellij or tmux, since there is no feature redundancy nor conflicting keybindings.

There is, thus, a desire especially from this group of users that use terminal multiplexers, of a "dumb mode" for Rio, with no tabs, splits or similar, reducing keybindings conflicts, and... possibly gaining performance?  

I am not sure if performance gain from this is even feasible, but the main point of this issue is for Rio to have compatibility with aforementioned tools from early on

**Comment by androw** [comment]
I think we should keep the copy/paste keyboard shortcut
