### ISSUE TITLE
window opacity not working on linux (X11, Picom)

### ISSUE THREAD

**Issue by oxypomme** [raphamorim/rio#214]
Hey, 

I've been using kitty for a while, but due to perfomance and stability issues, I decided to switch on Rio.

But I've got an issue with my configuration for a while: the property `window-opacity` doesn't seems to be working with [picom](https://github.com/yshui/picom) (X11 compositor) even though docs says that

> window-opacity changes the window transparency state.
> Only works for Windows / X11 / WebAssembly

Here's an example between Rio (at the top) and kitty (at the bottom):

![rio_kitty](https://github.com/raphamorim/rio/assets/34627360/591054e3-4d08-4bd9-846b-415bad13d53e)

Here's (part of) my config:

```toml
font = "FiraCode Nerd Font Mono"
font-size = 16
window-opacity = 0.75
```

I know that is kinda a specific issue, but I think it'll be cool to fix that, thanks :wave:

EDIT: I'm using Rio 0.0.18

**Comment by ralgozino** [comment]
Just to add another data point, `window-opacity` is not working for me on macos either.

I tested with 0.0.18 and main, and changing the value for opacity does not make any difference.

There are no traces of the `opacity` word in the logs.

**Comment by raphamorim** [comment]
Yes, it was supported at some moment but I suddenly removed to avoid some pain in the head when I was rewritting sugarloaf and forgot to update the docs.

I will mark this as wishlist to work soon.

**Comment by luccahuguet** [comment]
can confirm still not working on PopOS X11, 0.0.22

**Comment by raphamorim** [comment]
![image](https://github.com/raphamorim/rio/assets/3630346/1191885d-8467-4435-993f-af19c430943b)
![image](https://github.com/raphamorim/rio/assets/3630346/14501e86-82ef-4644-9c4b-184f70210364)

Blur and opacity have been added to 0.0.28 https://raphamorim.io/rio/docs/configuration-file#using-blur-and-background-opacity
