### ISSUE TITLE
Backspace behaviour misplace on Windows

### ISSUE THREAD

**Issue by bruisedsamurai** [raphamorim/rio#220]
When pressing backspace it deletes a word and to delete an alphabet I have to press CTRL.

**Comment by bruisedsamurai** [comment]
0.0.17

**Comment by raphamorim** [comment]
Can you try with 0.0.18 (I believe was fixed there)

**Comment by bruisedsamurai** [comment]
Nope, issue persists

**Comment by bruisedsamurai** [comment]
Nothing 🤭
![image](https://github.com/raphamorim/rio/assets/20334754/c22f9a4f-5047-41a0-a52c-dc15eacb6e89)

**Comment by raphamorim** [comment]
Wood, realised that oddly rio is having these behaviour whenever term is env variable is off. Can you try setting it for whatever term you have in other terminal and see if it fixes?

**Comment by bruisedsamurai** [comment]
https://superuser.com/questions/1690372/term-system-environment-variable-not-set-windows-10

I am getting empty in Windows Terminal too.

**Comment by bruisedsamurai** [comment]
Any updates?

**Comment by raphamorim** [comment]
Just tried the canary version on windows and it's working for me.

My env variables

![Screenshot 2023-09-15 at 23 39 05](https://github.com/raphamorim/rio/assets/3630346/fda64c61-0d4d-4147-b069-f960989159bf)

**Comment by raphamorim** [comment]
I tried with this version: https://github.com/raphamorim/rio/releases/tag/canary-c71b6fc2437242bca68450417821d45ad127cc18

**Comment by bruisedsamurai** [comment]
ENV or bckspc

**Comment by raphamorim** [comment]
The backspace issue, for me it does work in main branch now https://github.com/raphamorim/rio/releases/tag/canary-b2f1b6bdc079a85fd6138e2e4c85309c6eb89255

**Comment by bruisedsamurai** [comment]
Checked in latest update. Backspace is fixed but now control too deletes only one character.

**Comment by raphamorim** [comment]
> Backspace is fixed but now control too deletes only one character.

you mean just control or backespace with control?

**Comment by bruisedsamurai** [comment]
Backspace with control deletes one character too only.

**Comment by raphamorim** [comment]
> Backspace with control deletes one character too only.

Does it work in other terminals? Asking just for a compassion. I know that it doesn't work on MacOS/linux uses backspace+alt https://github.com/alacritty/alacritty/blob/b4130ddf24d9612cce4cb043e9b15acc086369a1/alacritty/src/config/bindings.rs#L434C6-L434C6

**Comment by bruisedsamurai** [comment]
I am using Windows Terminal and it works there

**Comment by raphamorim** [comment]
Ok did a small research about it, apparently control+backspace is a shortcut is something that Bash does for you, it's not something the terminal emulator provides.

But I suppose people would like to have it enabled if they are using windows so I enabled in the commit ae0ffd0. We have few exceptions for this cases like MacOS shortcuts to navigate.

More details about it here https://github.com/alacritty/alacritty/issues/2930#issuecomment-1059833970
