### ISSUE TITLE
rio complains about missing font even though it's absolutely here

### ISSUE THREAD

**Issue by colemickens** [raphamorim/rio#221]
Rio complains about not being able to find my fonts:

I used to have style/weight listed, but I've removed those just to try to get *anything* to work.

I swear this worked a week or so ago.

```
╭ zeph  ~/code/nixcfg 13ms
╰─▶ cat ~/.config/rio/config.toml
[fonts]
size = 20
[fonts.bold]
family = "Iosevka Comfy Fixed"

[fonts.italic]
family = "Iosevka Comfy Fixed"

[fonts.regular]
family = "Iosevka Comfy Fixed"
```

and

```
╭ zeph  ~/code/nixcfg 2sec 983ms
╰─▶ fc-list | grep osevka
/nix/store/wnd0mcwx8w85zin0fjzbchmlcp5dyhsi-iosevka-comfy-fixed-1.3.0/share/fonts/truetype/iosevka-comfy-fixed-italic.ttf: Iosevka Comfy Fixed:style=Italic
/nix/store/wnd0mcwx8w85zin0fjzbchmlcp5dyhsi-iosevka-comfy-fixed-1.3.0/share/fonts/truetype/iosevka-comfy-fixed-bold.ttf: Iosevka Comfy Fixed:style=Bold
/nix/store/wnd0mcwx8w85zin0fjzbchmlcp5dyhsi-iosevka-comfy-fixed-1.3.0/share/fonts/truetype/iosevka-comfy-fixed-light.ttf: Iosevka Comfy Fixed,Iosevka Comfy Fixed Light:style=Light,Regular
/nix/store/wnd0mcwx8w85zin0fjzbchmlcp5dyhsi-iosevka-comfy-fixed-1.3.0/share/fonts/truetype/iosevka-comfy-fixed-semilight.ttf: Iosevka Comfy Fixed,Iosevka Comfy Fixed SemiLight:style=SemiLight,Regular
/nix/store/wnd0mcwx8w85zin0fjzbchmlcp5dyhsi-iosevka-comfy-fixed-1.3.0/share/fonts/truetype/iosevka-comfy-fixed-extrabold.ttf: Iosevka Comfy Fixed,Iosevka Comfy Fixed Extrabold:style=Extrabold,Regular
/nix/store/wnd0mcwx8w85zin0fjzbchmlcp5dyhsi-iosevka-comfy-fixed-1.3.0/share/fonts/truetype/iosevka-comfy-fixed-lightitalic.ttf: Iosevka Comfy Fixed,Iosevka Comfy Fixed Light:style=Light Italic,Italic
/nix/store/wnd0mcwx8w85zin0fjzbchmlcp5dyhsi-iosevka-comfy-fixed-1.3.0/share/fonts/truetype/iosevka-comfy-fixed-extrabolditalic.ttf: Iosevka Comfy Fixed,Iosevka Comfy Fixed Extrabold:style=Extrabold Italic,Italic
/nix/store/wnd0mcwx8w85zin0fjzbchmlcp5dyhsi-iosevka-comfy-fixed-1.3.0/share/fonts/truetype/iosevka-comfy-fixed-regular.ttf: Iosevka Comfy Fixed:style=Regular
/nix/store/wnd0mcwx8w85zin0fjzbchmlcp5dyhsi-iosevka-comfy-fixed-1.3.0/share/fonts/truetype/iosevka-comfy-fixed-semilightitalic.ttf: Iosevka Comfy Fixed,Iosevka Comfy Fixed SemiLight:style=SemiLight Italic,Italic
/nix/store/wnd0mcwx8w85zin0fjzbchmlcp5dyhsi-iosevka-comfy-fixed-1.3.0/share/fonts/truetype/iosevka-comfy-fixed-bolditalic.ttf: Iosevka Comfy Fixed:style=Bold Italic
```

**Comment by raphamorim** [comment]
Hey there @colemickens 

Thank for the issue, could you check with latest main?

**Comment by colemickens** [comment]
Oh I forgot to reply, I update my package of rio to the tip of main basically once or many times a day. I am still getting this error.

```
❯ cat ~/.config/rio/config.toml
[fonts]
size = 20
[fonts.bold]
family = "Iosevka Comfy Fixed"
style = "Bold"
weight = 600

[fonts.italic]
family = "Iosevka Comfy Fixed"
style = "Italic"
weight = 400

[fonts.regular]
family = "Iosevka Comfy Fixed"
style = "Regular"
weight = 400
```

**Comment by colemickens** [comment]
I can remove the style/weight stuff, but I did try that with the `main` branch build from ~5 days ago and it wasn't working.

**Comment by raphamorim** [comment]
😢 

Do you know the path of the those fonts in the OS? (that would be helpful for me to understand/replicate from my side)

**Comment by colemickens** [comment]
They're listed in the initial post in the `fc-list` output. I'm on NixOS so they might look a little funny, if you've not bumped into Nix before.

**Comment by raphamorim** [comment]
and it was being found before right? 0.0.18 (introduced new rules, so broke for your case and 0.0.19 added a new font loader but is more strict regard the naming)

I tried on macos and I do find the fonts but with a different name
<img width="411" alt="Screenshot 2023-09-20 at 22 04 05" src="https://github.com/raphamorim/rio/assets/3630346/53897a41-9afb-4aee-89e6-131fd849d336">

**Comment by raphamorim** [comment]
Installed the comfy fixed and it does find as well

<img width="646" alt="Screenshot 2023-09-20 at 22 06 00" src="https://github.com/raphamorim/rio/assets/3630346/54a2c808-95cf-428d-8efa-8174a69bbc3c">

**Comment by colemickens** [comment]
I am not sure of the exact version it was working in, and I think some of the error surfacing is new code since then too, but I'm quite sure I was seeing the right font at one point.

I use a fork of Iosevka - https://github.com/protesilaos/iosevka-comfy

As far as I know, most Linux GUI stuff uses freetype in some form and thus my go to is to use `fc-list` to prove to myself that correct fonts are installed.

I use this font with wezterm and alacritty without issue. (I have my nix config parameterized such that I'm sure they use the same family name, too).

**Comment by raphamorim** [comment]
In the current version you get errors like this whenever the font isn't found? 

<img width="712" alt="Screenshot 2023-09-20 at 22 07 05" src="https://github.com/raphamorim/rio/assets/3630346/d96e3767-487b-4631-977e-d5e56496e390">

**Comment by colemickens** [comment]
Yes, exactly.

**Comment by raphamorim** [comment]
i see, will try to tweak one change on it and ask for testing again. Sorry about this whole thing

**Comment by raphamorim** [comment]
Hopefully try to get it sorted out in this version 🤞

**Comment by colemickens** [comment]
Oh please, no need to apologize. I'm just excited for another contender in the Rust-y terminal emulator space. It's easy for me to test any random commit, so let me know if I can help. 🙏 🚀

**Comment by colemickens** [comment]
Skimming, I think this is problematic: https://github.com/raphamorim/rio/blob/94d9cf91a19f2042b0b71bfe51837137fd260e60/sugarloaf/src/font/loader/mod.rs#L300-L309

That's not going to work for NixOS users, for example.

I guess sugarload doesn't use `fontconfig`, I don't know if there's another "easy" way to get system fonts on a Linux system without pulling in all of fontconfig.

**Comment by colemickens** [comment]
Poking around at my system configuration, there are quite a few files that seem to affect fontconfig font discovery. I don't think it would be feasible to re-implement it.

Per someone in #wayland on OFTC:

```
kennylevinsen> colemickens: why not just use fontconfig? it is just a font discovery library.
```

I think using `fontconfig` instead of hard coding paths would resolve this problem.

**Comment by colemickens** [comment]
Okay, sorry to spam, last comment - you might take a look at alacritty or wezterm, which of both use `fontconfig`. Wezterm even has a `fcwrap` internal crate to handle calling into fontconfig.

**Comment by raphamorim** [comment]
No worries, I had fontconfig in the previous font loader but removed.

I've just had added again, could you check it later?

**Comment by colemickens** [comment]
with: 326102a061fcfe7a97092f925e3580596f3ccbfd

```
   Compiling lazycell v1.3.0
   Compiling base64 v0.21.0
   Compiling wgpu v0.16.3
   Compiling sugarloaf v0.0.19 (/build/source/sugarloaf)
error[E0433]: failed to resolve: use of undeclared crate or module `fontconfig_parser`
   --> sugarloaf/src/font/loader/mod.rs:306:30
    |
306 |         let mut fontconfig = fontconfig_parser::FontConfig::default();
    |                              ^^^^^^^^^^^^^^^^^ use of undeclared crate or module `fontconfig_parser`

error[E0433]: failed to resolve: use of undeclared crate or module `fontconfig_parser`
   --> sugarloaf/src/font/loader/mod.rs:335:13
    |
335 |         for fontconfig_parser::Alias {
    |             ^^^^^^^^^^^^^^^^^ use of undeclared crate or module `fontconfig_parser`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `sugarloaf` (lib) due to 2 previous errors
```

**Comment by raphamorim** [comment]
I fixed it but haven't pushed my bad 🙈 pushed now

**Comment by colemickens** [comment]
It works!
![screenshot-1695391589](https://github.com/raphamorim/rio/assets/327028/78f63061-1924-4ec2-847e-c68cfb0b1b27)

**Comment by raphamorim** [comment]
😢 glad it is working!

**Comment by colemickens** [comment]
Thank you! Sorry to cause you to re-add fontconfig, but I am happy to see my lovely Iosevka again. And my daily update of wezterm has it crashing a bunch so... it's a great time to start testing rio more. :slightly_smiling_face:

**Comment by raphamorim** [comment]
💯 glad to hear and no worries at! just happy that works for nix now
