### ISSUE TITLE
Mouse click and where a cursor is displayed offset

### ISSUE THREAD

**Issue by rlperez** [raphamorim/rio#223]
### Problem
Occassionally something will happen and terminal mouse clicks become offset by 1 or more lines. I can provide an example of editing the Helix desktop file in Helix. The screen capture shows my mouse is clicking the line about my current space however the cursor is placed the line below it. 

![Screenshot_20230914_121142](https://github.com/raphamorim/rio/assets/4786115/e708cebf-b232-4c72-bf7c-b07296d68f78)

I spent time trying to identify the problem. Is there specific characters that trigger the offset. It appears to me in clicking around this file the problem is a problem around extended character sets like Nepalese and Russian perhaps as the accuracy around most of the file is fine. I attempted to replicate this behavior in Konsole to make sure this was a Rio problem and not a Helix problem. 

After exiting Helix the problem persists once its been encountered. 

For instance if I attempt to highlight the line `helix-themes main• | 1` I need to drag the cursor along the line ` rio -e "hx && exec $SHELL"`

```
 > rio -e "hx && exec $SHELL"
helix-themes main• | 1
 > rio "hx && exec $SHELL"
error: unexpected argument 'hx && exec /bin/bash' found
```

I originally thought this was a wordwrap issue when I first saw it yesterday but I have tried this in fullscreen and I also tried it using my default fish prompt instead of the Hydro prompt. I would try and debug this but I am a little busy at the moment  and unfamiliar with this code.

**Comment by raphamorim** [comment]
Hey @rlperez thanks for the issue, yes is a known issue. It mostly happens due to the way sugarloaf is rendering now and how the logic was wrote. I am closing this issue to merge into #182 (my mind gets confused with many issues with same problem, replying in different channels)
