### ISSUE TITLE
Add predefined `ToggleFullscreen` Action

### ISSUE THREAD

**Issue by hustcer** [raphamorim/rio#229]
Thanks for the great work,
Can you please add a predefined `ToggleFullscreen` Action? So I can bind custom key bindings to it

**Comment by raphamorim** [comment]
Of course! marking it as a wishlist issue

**Comment by sonbui00** [comment]
Is this `Command + Control + F` on MacOS?

**Comment by raphamorim** [comment]
Command + Control + F (on Big Sur and earlier) or Fn + F if your Mac is running macOS Monterey or later

**Comment by raphamorim** [comment]
Let’s stick with Fn + F? (Since is the new default shortcut)

**Comment by hustcer** [comment]
Both `Command + Control + F` and ` Fn + F` don't work for me.
macOS Ventura  Version 13.5.2
