### ISSUE TITLE
Please, don't discard original license and copyright holder when porting alacritty code

### ISSUE THREAD

**Issue by kchibisov** [raphamorim/rio#246]
alacritty is solely licensed under the Apache 2.0 license, with the exception of some
crates being under MIT (vte, alacritty_config_derive,alacritty_config). However `rio` itself (not `copa`) is licensed under `MIT`, so when you apply patches submitted by alacritty contributors to alacritty, you should give a proper annotation (even for not yet merged work, it's still under Apache 2.0) into your project (see 4. (a) - (c) in Apache 2.0 license).

For example, this https://github.com/alacritty/alacritty/pull/7125 was applied https://github.com/raphamorim/rio/commit/cd463ca37677a0fc48daa8795ea46dadc92b1e95 but basically re-licensed without any annotation. There're certainly more code like that, which lost its annotation and source of origin.

It's not a big issue, it's just folks submitting patches or features to alacritty could be surprised that they work got backported to other project under different license they agreed to submit their work.

**Comment by raphamorim** [comment]
@kchibisov kchibisov thank you for the heads up ( I am really grateful for the work you guys do in another note :)

What’s the most best/suitable way? Add it inside of the rio or in a folder called licenses with all licenses.

To be honest never really thought rio would be anything big and only made this project to myself so ended up in my ignorance.

**Comment by kchibisov** [comment]
You can basically do something like that https://github.com/rust-windowing/xkeysym/blob/060e9e40635fcf65b77a87a1163d93d8c4178b4b/src/lib.rs#L19 and just say that `X`, `Y`, `Z` were from alacritty and under `Apache 2.0`.

That's more than enough. You don't have to do anything about the code you wrote or MIT code (though, you can annotate the origin, we did that in early days, when we took the code from the rust directly and it was MIT).

**Comment by raphamorim** [comment]
> You can basically do something like that https://github.com/rust-windowing/xkeysym/blob/060e9e40635fcf65b77a87a1163d93d8c4178b4b/src/lib.rs#L19 and just say that X, Y, Z were from alacritty and under Apache 2.0.

Thank you for the clarification @kchibisov 

I pushed a bunch of updates adding the mention to the license as well. Let me know suggestions or if is missing anything and I will gladly update

**Comment by kchibisov** [comment]
Yeah, something like that is fine. Maybe the wip kitty keyboard patch you've applied should be go under the same license as well. You basically say which functions were directly backported.

That's fine with me, it's just wanted to ensure that you understand that you should annotate the sources when you pull external code and it has some license attached to it, which requires you to annotate ( Some doesn't require that for example, like BOOST one iirc).

**Comment by kchibisov** [comment]
Ah, you did that in the two commits.

Thanks, good luck with your terminal!

**Comment by raphamorim** [comment]
> Thanks, good luck with your terminal!

Thank you @kchibisov !

And again appreciate all the work you have done 🙏 
Anything else please don't hesitate to reach out, I will gladly update.
