### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by etam** [raphamorim/rio#247]
At the bottom of https://raphamorim.io/rio/docs/configuration-file/ the link "Move to default colors ->" leads to `https://raphamorim.io/rio/docs/default-colors#default-colors`, but should `https://raphamorim.io/rio/docs/default-colors-and-themes/`

**Comment by raphamorim** [comment]
Hey there, thank you for the issue.

Would you mind opening a PR with the correction?

**Comment by etam** [comment]
here: #248
