### ISSUE TITLE
0.0.19 - theme = "dracula" in config causes filepath error

### ISSUE THREAD

**Issue by Jinkxed** [raphamorim/rio#250]
On 0.0.19 it looks like the configs are pointing to a local folder of yours rapha:
```
[background]
mode = "Image"
opacity = 1.0
[background.image]
path = "/Users/rapha/Desktop/eastward.jpg"
width = 200.0
height = 200.0
x = 0.0
y = 0.0
```

It's in the docs too
when I first open 0.0.19 I get a filepath error even after removing it weirdly
Looks like it's related to this line in the config: 
```
# theme = "dracula"
```

commenting it out gets rid of the error

**Comment by raphamorim** [comment]
Hey @Jinkxed , thanks for the issue

Isn't the configuration pointing as an example and commented?

For me is like this

```toml
# Background configuration
#
# • opacity - changes the background transparency state
#   Default: 1.0
#
# • mode - defines background mode bewteen "Color" and "Image"
#
# • image - Set an image as background
#   Default: None
#
# Example
# [background]
# mode = "Image"
# opacity = 1.0
#
# [background.image]
# path = "/Users/rapha/Desktop/eastward.jpg"
# width = 200.0
# height = 200.0
# x = 0.0
# y = 0.0
```

**Comment by Jinkxed** [comment]
When I upgraded it wasn't commented.  So I went and copy and pasted the docs, the docs aren't commented either.

**Comment by Jinkxed** [comment]
Looking further, it's likely because the theme folder doesn't exist by default.  Atleast doesn't on mine.

**Comment by raphamorim** [comment]
> When I upgraded it wasn't commented. So I went and copy and pasted the docs, the docs aren't commented either.

hmm, the file should be commented. I tested now in the ubuntu and macos removing the configuration file and restarting rio and it comes commented

<img width="672" alt="Screenshot 2023-09-22 at 20 46 12" src="https://github.com/raphamorim/rio/assets/3630346/651cd53c-b020-4274-91fa-00252235ca52">

Regarding the docs, it's just an example, not necessarily needs to be copied. Do you think would be better clarify that's an example there? Dracula theme doesn't exist by default (it is also an example in the docs)

**Comment by Jinkxed** [comment]
I think the configuration example should be the "working" example with all defaults.  This way anyone should be able to copy and paste to start from a fresh.

We should also outline how we install themes, as I don't think I've seen anything regarding that.  Could have definitely missed it though!

**Comment by raphamorim** [comment]
@Jinkxed thanks for the suggestion. Updated the docs with default file (with examples commented) and added theme section. Closing this issue for now but let me know anything
