### ISSUE TITLE
Version wasn't updated for v0.0.20 in Cargo.lock

### ISSUE THREAD

**Issue by p-linnane** [raphamorim/rio#252]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v0.0.20 of rio we noticed that running `rio --version` is still reporting v0.0.19. Wanted to raise this issue for awareness.

Relates to https://github.com/Homebrew/homebrew-core/pull/145551

**Comment by raphamorim** [comment]
Hey @p-linnane thanks for the issue.

Oh yea, my bad 🙈 
Would you prefer for me to tag 0.0.21 with fixed cargo.toml or 0.0.20-1?

**Comment by p-linnane** [comment]
Either one works fine. It's up to you. Thank you!

**Comment by p-linnane** [comment]
@raphamorim Just checking back in here. Thanks!

**Comment by raphamorim** [comment]
Published 0.0.21 today 👍 https://github.com/raphamorim/rio/releases/tag/v0.0.21
Closing this issue but please let me know anything.

**Comment by p-linnane** [comment]
Looks good, thanks!
