### ISSUE TITLE
Cursor in Wayland sessions disappear

### ISSUE THREAD

**Issue by Nyabinary** [raphamorim/rio#254]
If you open a Wayland session, whether it be with GNOME, KDE, or any other Wayland WM/DE, the terminal will 'eat' the cursor making the cursor not visible as seen in the video below:
[Screencast from 2023-09-25 16-56-10.webm](https://github.com/raphamorim/rio/assets/97130632/571e0a65-d469-4512-a3d9-909b55da32e0)

**Comment by raphamorim** [comment]
Hmm, and looks the cursor disappear without even type anything (the disappearance when typing is a thing rio does in macos/windows for example).

**Comment by Nyabinary** [comment]
> Hmm, and looks the cursor disappear without even type anything (the disappearance when typing is a thing rio does in macos/windows for example).

Yep it does, if you do open a fresh terminal you can see the cursor but when you focus on it/click on it the cursor disappears. I tried this on Hyprland, KDE, Sway, and GNOME so far, reproducible in each one with a Wayland session.

**Comment by Nyabinary** [comment]
cc:  @raphamorim should add the wayland label as well on this

**Comment by raphamorim** [comment]
I cannot reproduce it in latest main, is it still reproduce-able for you? @Nyabinary

**Comment by raphamorim** [comment]
although when I type and move the mouse it only reappears for me if I leave the mouse outside of rio terminal

**Comment by Nyabinary** [comment]
@raphamorim Still getting the problem, Using GNOME 44 from NixOS currently with Wayland.

**Comment by raphamorim** [comment]
Hey @Nyabinary, could you try with latest main? I deactivated the cursor hiding feature, since it clearly have a different behavior in different targets https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_cursor_visible

**Comment by Nyabinary** [comment]
@raphamorim Still same issue, Wezterm uses winit and has the issue too, but setting a cursor via the configuration fixes it. Maybe look at that?

**Comment by raphamorim** [comment]
> Wezterm uses winit and has the issue too, but setting a cursor via the configuration fixes it.

Are you sure? Wezterm doesn't look that uses winit and if there's a fix per setting cursor how it does work?

**Comment by Nyabinary** [comment]
> > Wezterm uses winit and has the issue too, but setting a cursor via the configuration fixes it.
> 
> Are you sure? Wezterm doesn't look that uses winit and if there's a fix per setting cursor how it does work?

https://wezfurlong.org/wezterm/faq.html?h=xcursor#i-use-x11-or-wayland-and-my-mouse-cursor-theme-doesnt-seem-to-work
They have a FAQ about it I had to set my cursor manually to "Adwaita" to make it work.

**Comment by raphamorim** [comment]
Could you try with latest canary? https://github.com/raphamorim/rio/releases/tag/canary

Added support for Adwaita

**Comment by Nyabinary** [comment]
> Could you try with latest canary? https://github.com/raphamorim/rio/releases/tag/canary
> 
> Added support for Adwaita

Could there be a way to automatically find the cursors? Or does it have to be manual because accounting for all WMs and DEs would be a *huge* pain I imagine.
