### ISSUE TITLE
Close processing tab

### ISSUE THREAD

**Issue by sonbui00** [raphamorim/rio#255]
If tty in the tab is running (ex: sleep 1000, or background jobs), then we close the tab. If the terminal's still running, the tty keep to run. Otherwise, if it's only tab and the terminal close, the tty also be killed.

I suggest to have confirm before closing the running tab. When close tab, the tty also need to be killed.

I'm checking to find how to know running status of tty on teletypewriter lib, but it seem does not support that. Only way I know is use `ps -t` for check.

Relate: https://github.com/raphamorim/rio/issues/203

**Comment by raphamorim** [comment]
Hey @sonbui00 , thanks for the issue

I can confirm the tty is open until close the terminal, so is not the optimal behavior.

**Comment by raphamorim** [comment]
Fixed in main, please let me know anything
