### ISSUE TITLE
add `working-dir` parameter to cli

### ISSUE THREAD

**Issue by Stunkymonkey** [raphamorim/rio#258]
start the terminal with a different working-directory then specified in the config. e.g.: open the terminal from within nautilus to the correct location: https://github.com/Stunkymonkey/nautilus-open-any-terminal/issues/92

**Comment by raphamorim** [comment]
Hey @Stunkymonkey thanks for the issue,
Implemented on main 

```bash
./target/debug/rio --working-dir=/Users/username/Documents
```
