### ISSUE TITLE
Sugarloaf: Positioning glyphs

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#259]
Currently Sugarloaf has a ~hacky~ solution for position the glyphs, but it can be done using `glyph_brush` (https://crates.io/crates/glyph_brush). It would get rid of bad fonts being positioned and some weird stuff rio gets as issues.

Prob the right way is drop text/section usage (https://github.com/raphamorim/rio/blob/main/sugarloaf/src/sugarloaf.rs#L438-L469) and use GlyphPositioner.

**Comment by karesztrk** [comment]
Any plan on possible fixes regarding this issue?

**Comment by TornaxO7** [comment]
> Any plan on possible fixes regarding this issue?

Aye: I want to tackle this.

**Comment by TornaxO7** [comment]
A lot of stuff is happening in `rio` so I'll wait first.

**Comment by raphamorim** [comment]
This issue should not be able to reproduce with the latest release (v0.1.0), closing this issue for now. In case find anything odd please let me know and we can reopen or create a new issue.
