### ISSUE TITLE
Update Website with new default colors and remove old term design

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#26]
New colors:

background       = '#0F0D0E'
black            = '#231F20'
blue             = '#006EE6'
cursor           = '#F38BA3'
cyan             = '#88DAF2'
foreground       = '#F9F4DA'
green            = '#0BA95B'
magenta          = '#7B5EA7'
red              = '#ED203D'

**Comment by Krishhhnaa** [comment]
please assign this issue to me

**Comment by raphamorim** [comment]
Will close this issue for now since the colors were updated, but I can create issues to those 2 points.

**Comment by Krishhhnaa** [comment]
Thanks man ! i am a beginner to Open Source , i am finding small small issues right now. I will try to solve #27 issue.
