### ISSUE TITLE
colourscheme not rendering properly

### ISSUE THREAD

**Issue by redxtech** [raphamorim/rio#260]
I'm using the [dracula theme](https://github.com/dracula/rio-terminal/blob/main/dracula.toml), and it doesn't appear to be rendering properly.

## Relevant details
OS: arch linux
Installation method: `nix`
GPU: 7900XT, driver: `amdgpu`
WM: `bspwm`

Since I am running `nixpkgs` on a non-NixOS installation, packages are unable to access the native OpenGL drivers. As a workaround, I'm using [nixgl](https://github.com/guibou/nixGL) to wrap the command in order to get it to run.

When I run `/usr/bin/rio` instead of `/nix/store/...-rio/bin/rio`, it renders the colours properly.

## Screenshots:

![rio, blank](https://media.discordapp.net/attachments/1110689785896501289/1156517265722839110/image.png?ex=65154223&is=6513f0a3&hm=956409fcf5c2f2e7f44565edc258c409676ea6be5687e8c07a8534462fac4f6c&=)
![rio, neovim](https://media.discordapp.net/attachments/1110689785896501289/1156517266452656198/image.png?ex=65154223&is=6513f0a3&hm=8552d3e1326e970e4031189a02f4ef31bf5e622c078b2c5d1ff9492671e4c9eb&=)

## Kitty with dracula theme for reference:
![kitty, blank](https://media.discordapp.net/attachments/1110689785896501289/1156517266784002058/image.png?ex=65154223&is=6513f0a3&hm=81202721edf76071b037adc1296f049e1f22bd7d4577853546ed99e3f5c14157&=)
![kitty, neovim](https://media.discordapp.net/attachments/1110689785896501289/1156517267077599303/image.png?ex=65154223&is=6513f0a3&hm=48b4907c3e09ed0cb29d0e9b268252bbe856f704b3998d78a8553476163ba0b8&=)

**Comment by rottencandy** [comment]
I'm seeing the same issue, also running rio installed through nixpkgs on a non-NixOS distro & using nixGL.

**Comment by raphamorim** [comment]
@redxtech @rottencandy thanks for the input, could you try with latest main?

**Comment by raphamorim** [comment]
As we talked in the discord, this issue has been fixed in the 0.0.22 
<img width="658" alt="Screenshot 2023-10-02 at 16 12 14" src="https://github.com/raphamorim/rio/assets/3630346/79abc3ca-de33-4468-a6a4-31cc1fdfbb8b">
