### ISSUE TITLE
Config pwsh 7 as default shell no working on Windows 11

### ISSUE THREAD

**Issue by ErrorPower2001** [raphamorim/rio#263]
### rio version
0.0.19 and 0.0.20, portable and installation

### OS
MS Windows 11 22H2 22621.2361

### PowerShell version
Core 7.3.7

---

config no working at

    shell = { program = "C:\\Program Files\\PowerShell\\7\\pwsh.exe", args = ["--login"] }

or

    shell = { program = "C:/Program Files/PowerShell/7/pwsh.exe", args = ["--login"] }

or

    shell = { program = "pwsh", args = ["--login"] }

or

    shell.program = "C:/..."
    shell.program = "pwsh[.exe]"

e.g.

Also, cmd.exe is no working.

No matter how I configure it, rio start with *Windows PowerShell* as the default shell.

### Start portable by PowerRun
![image](https://github.com/raphamorim/rio/assets/45718918/cf7e0b9f-22f8-40b5-a393-8866a03602d8)

### Start installation by click start menu icon
![image](https://github.com/raphamorim/rio/assets/45718918/38e1d064-d3c5-46cd-9ee6-77ac1cb95939)

### Start by console is work
![image](https://github.com/raphamorim/rio/assets/45718918/66d1d0dd-f133-4387-89b8-65d8fac16ec8)

---

But, other configuration is working good, like font config

**Comment by lost22git** [comment]
work for me just 
```shell
shell = { program = "pwsh", args = [] }
```

**Comment by lost22git** [comment]
pwsh help info:

```
-Login | -l

    On Linux and macOS, starts PowerShell as a login shell, using /bin/sh to
    execute login profiles such as /etc/profile and ~/.profile. On Windows,
    this switch does nothing.
```

**Comment by raphamorim** [comment]
yes, windows powershell doesn't have `--login`, so args needs to be empty. I will add the info on the documentation. Thanks @lost22git .

Closing this issue for now but let me know anything

**Comment by ErrorPower2001** [comment]
I finally found the cause of the error. I configured rio based on the configuration file provided in the document, and did not change the order of the ```shell``` keys, which resulted in it being written to the [font] table.

    [font]
        size = ...
        family = ...
    [navigation]
        ...
    shell = { program = "pwsh" }

Please mark in the document which toml keys are the root keys and which are the sub keys.

Or simply write it as key path, like:

    fonts.family = ''
    fonts.size = 18
    fonts.regular.family=''
    ...
    shell = { program = "pwsh"}
    ...

**Comment by raphamorim** [comment]
Glad it is working now @ErrorPower2001  🙏

**Comment by ErrorPower2001** [comment]
> Glad it is working now @ErrorPower2001 🙏

thanks.

**Comment by neeraj9** [comment]
I tried all the options, but I cannot change shell in Rio on windows. It always start powershell. I am not sure what is going wrong. My config is as follows:

```ini
padding-x = 5
cursor = '▇'
blinking-cursor = false
shell = { program = "cmd", args = [] }

[navigation]
mode = "CollapsedTab"

# tried this as well without any luck
#[shell]
#program = "C:/Windows/System32/cmd.exe"
#args = []
```
