### ISSUE TITLE
selection in version 20 and 21 is off by 1

### ISSUE THREAD

**Issue by fdncred** [raphamorim/rio#264]
It seems that selection with the mouse cursor on macos is off by 1.

example
```
> now is the time
  ^--------------^-- curosor starts at ^ after the e and end at n, including n.

selection is " now is the tim"
              ^--------------^-- note the extra space before now and missing e.
```

It may happen on other operating systems but i've only tested on macos.

**Comment by raphamorim** [comment]
Hey @fdncred thanks for the issue,

could you try with latest main? (now is using fixed width for each cell)

**Comment by fdncred** [comment]
I was able to compile the Linux wayland version and run it from WSL and the selection is still off by one.

It's a little hard to see on this gif, due to optimization, but the selection color starts highlighting on the second letter as I drag the selection left.
![selection_offset](https://github.com/raphamorim/rio/assets/343840/a744e973-f2f2-446a-a020-2fbbf79e8b7a)

**Comment by raphamorim** [comment]
Dang good to know, btw I am closing this issue to merge into #182 (my mind gets confused with many issues with same problem, replying in different channels)
