### ISSUE TITLE
custom keybindings not work

### ISSUE THREAD

**Issue by lost22git** [raphamorim/rio#265]
os: win11

my config
```toml
[bindings]
keys = [
  { key = "=", with = "alt", action = "SplitHorizontally" },
  { key = "-", with = "alt", action = "SplitVertically" },
  { key = "w", with = "control | shift", action = "ClosePane" },
  { key = "up", with = "control | shift", action = "ScrollLineUp" },
  { key = "down", with = "control | shift", action = "ScrollLineDown" },
  { key = "pageup", with = "control | shift", action = "ScrollHalfPageUp" },
  { key = "pagedown", with = "control | shift", action = "ScrollHalfPageDown" },
  { key = "home", with = "control | shift", action = "ScrollToTop" },
  { key = "end", with = "control | shift", action = "ScrollToBottom" },
]
```

**Comment by raphamorim** [comment]
Which actions aren't working?
Or is every action?

**Comment by lost22git** [comment]
every action

**Comment by raphamorim** [comment]
which version are you using?
btw `SplitHorizontally` and `SplitVertically` didn't have been implemented so doesn't work yet.

**Comment by lost22git** [comment]
╰─❯ .\rio.exe --version
rioterm 0.0.19

**Comment by lost22git** [comment]
also not work

╰─❯ .\rio.exe --version
rioterm 0.0.21

**Comment by raphamorim** [comment]
ah `ClosePane` doesn't work yet (I am still working on #184 support) but realised that `ScrollLineUp`, `ScrollLineDown`, `ScrollHalfPageUp`, `ScrollHalfPageDown`, `ScrollToTop`and `ScrollToBottom` that haven't added to bindings/mod.rs. Now it should work for those

**Comment by raphamorim** [comment]
Added changes to the main branch, thanks for the issue let me know if run into anything

**Comment by lost22git** [comment]
![1](https://github.com/raphamorim/rio/assets/65008815/6329749e-d136-470f-bbea-05af9a11c13e)

ScrollLineUp can only trigger once
ScrollLineDown behave same as ScrollToBottom

**Comment by raphamorim** [comment]
@lost22git which key bindings are using for ScrollLineUp and ScrollLineDown?

**Comment by lost22git** [comment]
```
[bindings]
keys = [
  { key = "=", with = "alt", action = "SplitHorizontally" },
  { key = "-", with = "alt", action = "SplitVertically" },
  { key = "w", with = "control | shift", action = "ClosePane" },
  { key = "up", with = "control | shift", action = "ScrollLineUp" },
  { key = "down", with = "control | shift", action = "ScrollLineDown" },
  { key = "pageup", with = "control | shift", action = "ScrollHalfPageUp" },
  { key = "pagedown", with = "control | shift", action = "ScrollHalfPageDown" },
  { key = "home", with = "control | shift", action = "ScrollToTop" },
  { key = "end", with = "control | shift", action = "ScrollToBottom" },
]
```

**Comment by raphamorim** [comment]
Interesting, I will take a look on it can you create a new issue regarding ScrollLineUp and ScrollLineDown? (gets easier for me to track)

btw, when I tested I used `with = super` so might be that an existent windows key binding is co-existing (but haven't checked yet)
