### ISSUE TITLE
[docs] Fix the image preview for when you share the link to use the banner

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#27]
Fix the image preview for when you share the link to use the banner https://github.com/raphamorim/rio/blob/main/docs/banner.png.

Ref #26

**Comment by Krishhhnaa** [comment]
@raphamorim  can you assign me this issue ?

**Comment by raphamorim** [comment]
Can you also include the twitter metadata in the change?

> more details: https://www.socialpilot.co/blog/twitter-card-validator

**Comment by Krishhhnaa** [comment]
@raphamorim  i have some problems in these 2 issues can you help me out ? do we have discord or any means to convo ?

**Comment by raphamorim** [comment]
Hey @Krishhhnaa . Rio doesn't have discord yet, not planning to have until a stable release.
Would like to describe the issue? maybe we can sort out here together :)

**Comment by raphamorim** [comment]
Closed by 0e1d50b77a67129de5f0b5b6941ea0405c93013b .
@Krishhhnaa feel if you want to take #28 👌
