### ISSUE TITLE
Setting the default window as Fullscreen causes crash.

### ISSUE THREAD

**Issue by bruisedsamurai** [raphamorim/rio#271]
![image](https://github.com/raphamorim/rio/assets/20334754/ca539010-23f2-45f9-ade4-f9426adb36d5)

**Comment by raphamorim** [comment]
Is this latest rio version?

**Comment by bruisedsamurai** [comment]
Yes

**Comment by raphamorim** [comment]
@bruisedsamurai is this happening with latest version? (because now we are using wgpu 0.18 and that error is 0.17 based)

**Comment by bruisedsamurai** [comment]
It’s fixed. There is an initial flicker though. Where some portion of windows become white.
