### ISSUE TITLE
Nerd fonts scaling

### ISSUE THREAD

**Issue by karesztrk** [raphamorim/rio#272]
There is an issue with Nerd Fonts scaling and glyph rendering in general. 
On the screenshot, you can see that the Font icons are tiny (they are not in Alacritty) and the glyphs from [Zellij](https://github.com/zellij-org/zellij) are padded.
![nerd_font_issue](https://github.com/raphamorim/rio/assets/5886428/360f6ebc-30df-4dfe-8417-b44d675bd4dc)

**Comment by raphamorim** [comment]
Hey @karesztrk , thanks for the issue.

Yes is connected to #259

**Comment by karesztrk** [comment]
Okay. In that case, would it make sense to close this issue?

**Comment by raphamorim** [comment]
Sounds good! Once that issue is done should be at least scaled/placed correctly. Closing this one for now
