### ISSUE TITLE
(Question) X11/Wayland dependency is mandatory?

### ISSUE THREAD

**Issue by hardBSDk** [raphamorim/rio#273]
I saw that Rio uses `winit`, this crate support other display servers beyond X11/Wayland, why they are mandatory on the build documentation?

**Comment by raphamorim** [comment]
Hey @hardBSDk thanks for the issue,

It is not mandatory, I think the docs kept the way it was written a year ago please feel free to update if you want to 🙏 

Closing this issue for now
