### ISSUE TITLE
Text copy (OSC 52) is broken (tmux, zellij)

### ISSUE THREAD

**Issue by awoimbee** [raphamorim/rio#276]
Hi,
I don't know the intricacies, but when I try to copy text directly from ZSH it works, but from zellij or tmux it doesn't (the clipboard is not updated).

```bash
$ rio --version
rioterm 0.0.22
```

**Comment by tranzystorek-io** [comment]
https://zellij.dev/documentation/faq#copy--paste-isnt-working-how-can-i-fix-this, haven't checked if rio supports OSC 52, but likely not

**Comment by raphamorim** [comment]
It should have support for OSC 52, will mark to take a look on it 👍

**Comment by raphamorim** [comment]
https://github.com/raphamorim/rio/blob/15a2afdc83b6afbd33518502f42e63a8b0303b63/rio/src/performer/handler.rs#L687-L697

**Comment by raphamorim** [comment]
@awoimbee what's your TERM value?

**Comment by awoimbee** [comment]
In rio, `echo $TERM` prints "`rio`", in alacritty it's "`alacritty`".
Seems like the issue is OSC52 handling, I tried `printf "\033]52;c;Y29weXBhc3RhIQ==\a\n"` (from [here](https://seankhliao.com/blog/12020-05-14-osc-52/)) and it doesn't work in rio (in zsh, bash, zellij and tmux).

**Comment by raphamorim** [comment]
ah... I know what it is 🤦

**Comment by raphamorim** [comment]
When I refactored to support multiwindow long time ago I've lost the event handlers, one sec will push the fix.

**Comment by raphamorim** [comment]
Fixed at main <img width="412" alt="Screenshot 2023-10-09 at 00 13 51" src="https://github.com/raphamorim/rio/assets/3630346/373092eb-957a-4938-afad-99029975f3ad">
