### ISSUE TITLE
Scroll to fast in vim and nano

### ISSUE THREAD

**Issue by DanielTolentino** [raphamorim/rio#278]
Hi, I've encountered this issue on multiple Linux distributions while using Wayland with both a touchpad and a mouse. Is there any configuration change I can make to make it behave like other terminals? Thanks.

**Comment by raphamorim** [comment]
Hey @DanielTolentino thanks for the issue,

Just to confirm, you meant scroll too fast right? If yes, then I think maybe writing a configuration property to modify scroll speed.

**Comment by DanielTolentino** [comment]
The scrolling in rio is too fast, what config can I change to make it properly behave like other terminals?
I can't record the screen right now

**Comment by raphamorim** [comment]
Ah gotcha! ok, there's no configuration yet to control it.

Although I think is a simple change, might need to tweak this code https://github.com/raphamorim/rio/blob/main/rio/src/screen/mouse.rs#L36 to make multiplier comes from configuration file.

**Comment by DanielTolentino** [comment]
Nice. I don't know if I can make a working PR on this, but I'll try to change the multiplier and build from source afterwards.
Thanks!

**Comment by raphamorim** [comment]
If you would like to create a PR for it, feel free to create a draft version and we can iterate together :D

**Comment by DanielTolentino** [comment]
Awesome, I'll work on it soon after I get home 😊

**Comment by inudev5** [comment]
@raphamorim @DanielTolentino what should the default modifier value be? any suggestions?

**Comment by inudev5** [comment]
the scroll multiplier is being applied in the shell, i can confirm. 
but the scroll behavior is not applied inside any programs or editors. i think it should be applied inside other programs also. 
@raphamorim

**Comment by raphamorim** [comment]
Part of the problem of the quick scroll as well is that rio does render as soon is possible, probably we will need to move scroll to use scheduler.rs file (as have for render)

**Comment by raphamorim** [comment]
Added a new property to next version:

```toml
[scroll]
multiplier = 1.0
divider = 2.0
```

scroll calculation will be based on `(accumulated scroll * multiplier / divider)` so if you want quicker scroll, keep increasing the multiplier if you want to reduce you increase the divider. Can use both properties also to find the best scroll for you

Example below with multiplier 1.0 and divider 2.0

![scroll-mul-1-div-2](https://github.com/raphamorim/rio/assets/3630346/01ef7f01-5eaa-4016-b79f-7a0ab0c1550e)

Note: This should fix for canonical terminal behavior, for tmux/nvim/vim cases I am still working around

**Comment by raphamorim** [comment]
I've also found a bug for scroll implementation in rio with tmux/zellij and other multiplexer and patched as well

Before 

![tmux-before](https://github.com/raphamorim/rio/assets/3630346/806c4029-7ea1-4eea-87fa-9ba073f01333)

After

![tmux-after](https://github.com/raphamorim/rio/assets/3630346/3c746de1-025b-4554-8d92-aacf50a460e3)

**Comment by raphamorim** [comment]
Will close this issue for now but if have any issues with the new property I can reopen here as well. It will be patched to 0.0.29 but you can test in main branch
