### ISSUE TITLE
while building cargo project in a tab, <F3> is pressed in another tab

### ISSUE THREAD

**Issue by nerdyinu** [raphamorim/rio#281]
<img width="409" alt="image" src="https://github.com/raphamorim/rio/assets/84079237/8ce36fb0-e72d-493a-b674-9828a3d80983">

it seems that this is reproduced only when i am actually typing / pressing keystroke in other tabs. when i am not typing, F3 is not typed neither. 

this is kind of 'draft' issue, sorry. i will improve further on this later.

**Comment by raphamorim** [comment]
Can you check if this reproduceable with latest main?

**Comment by raphamorim** [comment]
This should be able to reproduce anymore with the route_id parameter on event proxy. Closing this issue but let me know anything
