### ISSUE TITLE
Function keys are not properly handled on macos

### ISSUE THREAD

**Issue by spoutn1k** [raphamorim/rio#282]
Hey,

I cannot use function keys on macos for some reason. The easiest test I came up with is to press an F key in vim. In the Terminal app, I get `<F[1-9]>`, while in Rio I get some weird characters.

3x F8 and 3x F9 in vim/Terminal:
```
~ % xxd ftest.txt 
00000000: 3c46 383e 3c46 383e 3c46 383e 0a3c 4639  <F8><F8><F8>.<F9
00000010: 3e3c 4639 3e3c 4639 3e0a                 ><F9><F9>.
```

The same keystrokes in Rio:
```
~ % xxd f9.txt 
00000000: ef9c 8bef 9c8b ef9c 8b0a ef9c 8cef 9c8c  ................
00000010: ef9c 8c0a                                ....
```

Kinda annoying when my vim plugins are bound to function keys. I could not find an issue mentioning function so I hope this is not a duplicate.

**Comment by spoutn1k** [comment]
Forgot to mention this is on mac silicon installed using brew casks.

**Comment by raphamorim** [comment]
Hey @spoutn1k 

thanks for the issue. Not sure if is connected to #281 , will take a look. Is the version used 0.0.22?

**Comment by spoutn1k** [comment]
0.0.22 is affected but I found about the issue in 0.0.20 iirc so its not a recent regression. Thank you for the quick answer let me know if I can help in any way if you have an idea of where to look !

**Comment by raphamorim** [comment]
will take a look, I think it started once I added the kitty keyboard protocol / upgrade winit to latest

**Comment by raphamorim** [comment]
@spoutn1k could check with latest main?

**Comment by spoutn1k** [comment]
Works for me on a release build using cargo ! Close at will.

**Comment by raphamorim** [comment]
Great!! thanks for reporting @spoutn1k
