### ISSUE TITLE
"Del" Key Not Functioning as Expected in Neovim

### ISSUE THREAD

**Issue by tarcisiodelmondes** [raphamorim/rio#293]
I'm using version 0.0.22 of Rio Term. I built "Rio" using the following command: `cargo build --release --no-default-features --features=x11`. In Neovim when I press the "Del" key, instead of deleting text to the right, it's deleting to the left. So far, this issue has only occurred in Neovim. I'm using Linux on an arm64 platform.

**Comment by tarcisiodelmondes** [comment]
> @tarcisiodelmondes can you check with latest main?

Hello, I tested it in the latest main branch, and now the "Del" key is working correctly. Thank you.

**Comment by raphamorim** [comment]
thank you for confirm
