### ISSUE TITLE
Move the Website to a docs format

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#30]
Would be good to build the website straight from Markdown, so we can also reuse in the GH version. Mind is necessary to keep the home similar to the way it's.

Few options are:
- parse md files directly using js (e.g: https://github.com/vercel/hyper-site)
- use rust to build the website
- https://docusaurus.io/
- https://www.docz.site/

Besides the home, also need to have a blog page.

**Comment by giovannism20** [comment]
would be good if we use zola ? https://github.com/getzola/zola - just to follow the project using rust

**Comment by raphamorim** [comment]
I honestly have no preference. Regarding use only Rust, there's the prospect that at some moment JavaScript will be added to Rio due to WebAssembly support and tests. So will end up coexisting with Rust.
