### ISSUE TITLE
Flickering on render and flash of my cursor in wrong position

### ISSUE THREAD

**Issue by bekirisgor** [raphamorim/rio#301]
Currently, on my macos (havent tested in linux yet) have 2 problem when i navigate with 'n' and '{' '}' keys. 

Flicker and flash my cursor at miss place.

I also use tmux. 

Please let me know if you need additional information

**Comment by raphamorim** [comment]
Hey @bekirisgor thanks for the issue,

Which version are you using?

**Comment by bekirisgor** [comment]
Hey  its version 0.0.24 downloaded via brew.

**Comment by enieber** [comment]
I has flickering render in scroll on neovim in version 0.0.26 but in last update 0.0.27 is fixed, @bekirisgor   try update to verify has fixed this bug

**Comment by bekirisgor** [comment]
Yes flickering issue totally fixed thanks for works. Cursor still flashing randomly place but its not a big issue. @raphamorim Feel free the close issue.  I appreciate that

**Comment by raphamorim** [comment]
thank you @enieber for the help with this issue as well 🙏 

> Cursor still flashing randomly place but its not a big issue. 

Mostly because Rio does render with high fps for a term (over >60fps in the macos for example). This should be controllable in the future through configuration.
