### ISSUE TITLE
Site/Documentation is down

### ISSUE THREAD

**Issue by GuiReboucas** [raphamorim/rio#303]
Site is down

**Comment by raphamorim** [comment]
Looks correct for me

<img width="921" alt="Screenshot 2023-10-24 at 08 47 51" src="https://github.com/raphamorim/rio/assets/3630346/8bc8d4bc-abec-459a-849f-e3afb88208b4">

**Comment by GuiReboucas** [comment]
Every browser that i use times out when trying to enter the website.
It's probably just a me thing, but still...
It was working just fine 2 days ago
