### ISSUE TITLE
(Behavior improvement) Make the mouse wheel move the scrollbar

### ISSUE THREAD

**Issue by hardBSDk** [raphamorim/rio#305]
Currently the mouse wheel move the command history (arrow keys already move the command history), most users are accostumed to scrollbar movement.

If you don't like this suggestion, implement an option to enable this.

**Comment by raphamorim** [comment]
Hey @hardBSDk thanks for the issue,

The mouse wheel move the scrollbar (or at least for me), is this happening in which platform and rio version?

**Comment by hardBSDk** [comment]
@raphamorim I'm using Pop OS 22.04 LTS, Rio version 0.0.22

**Comment by hardBSDk** [comment]
@raphamorim I updated to the version 0.0.25, now the default mouse wheel behavior move the scrollbar.

Thanks! I love your terminal.

**Comment by raphamorim** [comment]
Thanks @hardBSDk ! that's great news 🙏
