### ISSUE TITLE
default offset height is above the bottom position since update

### ISSUE THREAD

**Issue by inudev3** [raphamorim/rio#307]
updated from 0.22.0 to 0.24.0,
and
the default offset height is above bottom position
<img width="1201" alt="image" src="https://github.com/raphamorim/rio/assets/84079237/f66265e7-83af-4936-827d-3b7a22ee9f1a">
this happens even inside of a nvim editor
<img width="1214" alt="image" src="https://github.com/raphamorim/rio/assets/84079237/b75c8c24-ad90-4366-b416-c8de0440ef47">

**Comment by raphamorim** [comment]
@inudev5 thank you for the issue,

can you add also the image with the full terminal just for comparison

**Comment by raphamorim** [comment]
This issue should not be able to reproduce with the latest release (v0.1.0), closing this issue for now. In case find anything odd please let me know and we can reopen or create a new issue.
