### ISSUE TITLE
Dimmed colors support

### ISSUE THREAD

**Issue by leo-arch** [raphamorim/rio#308]
Dimmed colors do not seem to be working.

Steps to reproduce:

```sh
echo -e "\x1b[0;31mregular\x1b[2;31mdimmed\x1b[0m"
```

This is supposed to produce two shades of red (regular and dimmed), but only one (regular) is produced in both cases instead.

**Comment by raphamorim** [comment]
wow good finding, before it was only working for indexed colors and not named colors

fixed in main

<img width="729" alt="Screenshot 2023-10-25 at 10 07 45" src="https://github.com/raphamorim/rio/assets/3630346/6333386a-8a57-4206-9d75-0f9c0c404f2b">

**Comment by leo-arch** [comment]
Thanks @raphamorim! Glad to help.
