### ISSUE TITLE
Wrong syntax on key bindings?

### ISSUE THREAD

**Issue by hardBSDk** [raphamorim/rio#314]
I think it should use the `]` symbol on these lines:

https://github.com/raphamorim/rio/blob/main/docs/docs/documentation/key-bindings.md?plain=1#L249

https://github.com/raphamorim/rio/blob/main/docs/docs/documentation/key-bindings.md?plain=1#L260

**Comment by raphamorim** [comment]
Good findining! would you like to update it?

**Comment by hardBSDk** [comment]
@raphamorim My suggestion is correct?

**Comment by raphamorim** [comment]
Yes, it's `[` `]` instead

**Comment by hardBSDk** [comment]
Fixed in https://github.com/raphamorim/rio/pull/315
