### ISSUE TITLE
How can one switch between tabs in Rio?

### ISSUE THREAD

**Issue by jeremiah** [raphamorim/rio#321]
Is there a keyboard combination to switch between tabs? I don't see anything in the configuration file and testing different combinations doesn't produce any results. I've made them 'clickable' but I cannot click on them.

**Comment by raphamorim** [comment]
Do you use linux?

If yes, https://raphamorim.io/rio/docs/documentation/key-bindings

<img width="612" alt="Screenshot 2023-10-30 at 19 46 54" src="https://github.com/raphamorim/rio/assets/3630346/2a02353f-3b64-4a14-9f19-48c9993f048d">

Move to next tab: Control + Shift + RightBracket (])

Move to previous tab: Control + Shift + LeftBracket ([)

Switch tabs by created order: Control + Tab
