### ISSUE TITLE
Translations for documentation (Spanish, Japanese, Polish, Chinese and Portuguese (Brazil))

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#324]
Currently we use https://docusaurus.io/, should look similar to this

<img width="361" alt="Screenshot 2023-11-01 at 09 18 29" src="https://github.com/raphamorim/rio/assets/3630346/7d87987d-2c71-4a7c-9690-9631ff1a4038">

## Translations

- [ ] Spanish
- [ ] Japanese
- [ ] Chinese
- [ ] Polish
- [ ] Portuguese (Brazil)

**Comment by tranzystorekk** [comment]
I can spend some spare time to add a Polish locale

**Comment by ralgozino** [comment]
I volunteer as tribute for the Spanish translation 🏹

**Comment by raphamorim** [comment]
Closing as we started the translation support already
