### ISSUE TITLE
Some font issues

### ISSUE THREAD

**Issue by kls1991** [raphamorim/rio#328]
rio version 0.0.26
os version Windows 11
![rio](https://github.com/raphamorim/rio/assets/32974383/7ee9d192-5aee-4c32-8799-a24163e20449)

1. Lines overlap each other when I use Consolas font.
2. Fonts.extras seems not working, I thought the Chinese characters should be rendererd in the font I specify in line 5.
3. Chinese characters should be bigger, like shown below(Neovide for windows); Nerd fonts should be bigger too in my opinion.
4. Input method floating window is faaaaaaaaaar from my cusor.

![neovide](https://github.com/raphamorim/rio/assets/32974383/a46f0f18-7fa0-4938-b442-61fc2460d987)

Sorry for my bad English, and I may reply quite slow due to timezone difference.

**Comment by raphamorim** [comment]
Hey there @kls1991 thanks for the issue,

The first, second and third point are known issues. Hopefully will fix soon (meanwhile mark this issue as bug). The 4th issue I haven't see it before but I have an idea of why.

> Sorry for my bad English, and I may reply quite slow due to timezone difference.

Your english is perfect :) 

Will take a look on the items and comment here any update

**Comment by kls1991** [comment]
Thank you man, for a long time I can only get proper font fallback from wezterm and neovide on Windows.
Wezterm feels... slow for me, and neovide is not even a terminal emulator.
I'm soooooo exicted when I find rio, can't wait it to be 1.0!

**Comment by ralgozino** [comment]
Testing the new Monaspace fonts from GitHub, I've found that they have the same issue as what reported by @kls1991 using Consolas:
<img width="1312" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/8bc2d74d-d066-44f6-8127-2653ac7b733e">

**Comment by NovaViper** [comment]
The Nerd Fonts also seem to have the same issues, adding MesloLGS to the family to use makes symbols not align properly

Without 'MesloLGS Nerd Font' in config
![image](https://github.com/raphamorim/rio/assets/7191115/c5f1f53d-df1d-4c5d-97e4-528c2534d1c5)

With 'MesloLGS Nerd Font' in config
![image](https://github.com/raphamorim/rio/assets/7191115/feb154c9-331b-4465-a47a-c2f1176eec11)

**Comment by raphamorim** [comment]
This issue should not be able to reproduce with the latest release (v0.1.0), closing this issue for now. In case find anything odd please let me know and we can reopen or create a new issue.
