### ISSUE TITLE
Bold and italic text style

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#33]
Nowadays, Sugarloaf completely ignore if font is bold but the square has the information if the is bold and we can also load the bold font in sugarloaf/font mod.

**Comment by gaoDean** [comment]
This would be very nice! As one of the few terminals that support proportional fonts, it would be great to make this a complete writing environment with bold and italic styles.

**Comment by raphamorim** [comment]
Implemented in [5555048](https://github.com/raphamorim/rio/commit/5555048de486a1fc1fa9d17498ab5b06485ba451)

<img width="786" alt="demo-text-styles" src="https://github.com/raphamorim/rio/assets/3630346/473c2777-583c-4679-9fc4-decee7e4c277">
