### ISSUE TITLE
Unable to get images working as expected

### ISSUE THREAD

**Issue by lypanov** [raphamorim/rio#335]
I've been trying to get the kitty/iTerm2 protocol support working and have tried timg (https://github.com/hzeller/timg) and imgcat script from iTerm2 itself but to no avail. I just see a single empty line instead of the image. Configuration: x11. Running from HEAD. Is there some TERM magic I'm missing maybe?

**Comment by raphamorim** [comment]
Hey there @lypanov,

iTerm2 and kitty image protocol are coming to the next version only (I am still wrapping up the branch work before merge). ~Although the docs are showing there's image protocol available (my fault)~

**Comment by lypanov** [comment]
Ah! That explains. Okay I'll await the branch then and continue using xfce4-terminal for his use case for now then switch that too in time.

Thanks for all the work on this. I'm running Rio via UserLand + Ubuntu on a Samsung Tab S6 and it works flawlessly for my needs.

**Comment by raphamorim** [comment]
Next version will include an initial version of sixel and iterm2 protocol. Regarding kitty image protocol I will work in the future.
