### ISSUE TITLE
Kitty-keyboard-protocol causes Backspace to delete 2 characters.

### ISSUE THREAD

**Issue by gyreas** [raphamorim/rio#344]
Hi, 
I'm trying out Rio first time, so after installation, I enabled some fancy-looking options, after which backspace begins to delete 2 characters instead of one. By process of elimination, `use-kitty-keyboard-protocol = true` turned out to be the culprit, without which the default value `false` works well.

To reproduce:
1. Create a temp config with cursor, blinking-cursor, use-kitty-keyboard-protocol=true and performance="high" options set
2. Open a new Rio with that config
3. Type some random characters on the cmdline and press backspace once
Observation: **Two characters before the cursor are deleted.**
Expected Outcome:  **The character before the cursor is deleted.**

**Comment by raphamorim** [comment]
@gyreas thanks for the issue, are you using Rio in which version and platform?

**Comment by raphamorim** [comment]
Should be fixed after @hougesen fix, let me know anything
