### ISSUE TITLE
Variable fonts support - bold text doesn't render as bold

### ISSUE THREAD

**Issue by bagasme** [raphamorim/rio#345]
Hi,

On my Rio config (`~/.config/rio/config`), I use locally installed variable font (here GitLab Mono):

``` toml
...
[fonts]
family = "GitLab Mono"
size = 18
...
```

When I run vttest no. 2 (`Test of screen features`), bold texts are displayed as regular weight instead of bold:
![Rio vttest](https://github.com/raphamorim/rio/assets/40219486/dc499e7f-89a2-49eb-9b69-aece7d9b404d)

On another terminal (e.g. `kgx` aka GNOME console), these render correctly:
![kgx vttest](https://github.com/raphamorim/rio/assets/40219486/5f18c1c3-d3c9-4bc2-bc53-efb3664c8033)

It seems like Rio (especially underlying sugarloaf library) treats variable fonts as static regular fonts (or does Rio not support variable fonts?). These can be confirmed when running Rio with debugging logs (`RIO_LOG_LEVEL=debug rio`). The log excerpt have:

```
...
[INFO] sugarloaf::font Font search: family 'GitLab Mono' with style 'normal' and weight '400'
[WARN] sugarloaf::font Font 'GitLab Mono' found in /home/bagas/.local/share/fonts/GitLabMono/GitLabMono.ttf
[INFO] sugarloaf::font Font search: family 'GitLab Mono' with style 'italic' and weight '400'
[WARN] sugarloaf::font Font 'GitLab Mono' found in /home/bagas/.local/share/fonts/GitLabMono/GitLabMono-Italic.ttf
[INFO] sugarloaf::font Font search: family 'GitLab Mono' with style 'normal' and weight '800'
[WARN] sugarloaf::font Font 'GitLab Mono' found in /home/bagas/.local/share/fonts/GitLabMono/GitLabMono.ttf
[INFO] sugarloaf::font Font search: family 'GitLab Mono' with style 'italic' and weight '800'
[WARN] sugarloaf::font Font 'GitLab Mono' found in /home/bagas/.local/share/fonts/GitLabMono/GitLabMono-Italic.ttf
...
```

[Here is the complete gzipped log of Rio session](https://github.com/raphamorim/rio/files/13414999/rio.log.gz).

**Comment by raphamorim** [comment]
Hey @bagasme,

Thanks for the issue. Does it work when you use other font?

**Comment by bagasme** [comment]
> Hey @bagasme,
> 
> Thanks for the issue. Does it work when you use other font?

I don't have this issue when using traditional static fonts (like Source Code Pro). I can also reproduce this issue with another variable font (I test with Victor Mono).

![Victor Mono vttest](https://github.com/raphamorim/rio/assets/40219486/81c09cbf-66ff-4c1f-baf5-d965812d19db)

**Comment by raphamorim** [comment]
Hmm, looks Rio isn't finding the correct bold font then. Marking as a bug

**Comment by raphamorim** [comment]
Implemented support to auto bold and italic on main

![Image](https://github.com/user-attachments/assets/8278468f-249b-4b25-a2f1-60e86d80f1e5)
