### ISSUE TITLE
Touchpad scroll under Wayland, with multiplexer (zellij) is far too fast

### ISSUE THREAD

**Issue by colemickens** [raphamorim/rio#347]
Hi,

This short video demonstrates the issue: https://www.youtube.com/watch?v=qnE1r-9FCO8 (`alacritty` on the left, `rio` on the right)

When I scroll a small amount in Alacritty, with Zellij, it scrolls a normal amount. Under Rio, it's extreme and feels sporadic.

I wonder if this relates to smaller, more frequent scroll events from wayland/toolkit and them not getting properly "filtered" or transformed, before being given to an application, like Zellij, running in the terminal.

**Comment by raphamorim** [comment]
> loved that you added a video!

Yes this is something I will work on soon, Rio is scrolling as soon as possible while alacritty and other terminals doesn't scroll this way.

This issue is connected to #278 

I plan to revisit the scroll and add a config to control the speed as well

**Comment by raphamorim** [comment]
Ok, adding a new property to next version:

```toml
[scroll]
multiplier = 1.0
divider = 2.0
```

scroll calculation will be based on `(accumulated scroll * multiplier / divider)` so if you want quicker scroll, keep increasing the multiplier if you want to reduce you increase the divider. Can use both properties also to find the best scroll for you

Example below with multiplier 1.0 and divider 2.0

![scroll-mul-1-div-2](https://github.com/raphamorim/rio/assets/3630346/414d24f3-183d-4bd0-8319-674b0ff205a9)

**Comment by raphamorim** [comment]
Found a bug with tmux scroll implementation in rio and patched as well

Before 

![tmux-before](https://github.com/raphamorim/rio/assets/3630346/806c4029-7ea1-4eea-87fa-9ba073f01333)

After

![tmux-after](https://github.com/raphamorim/rio/assets/3630346/3c746de1-025b-4554-8d92-aacf50a460e3)

**Comment by colemickens** [comment]
@raphamorim do you mind linking me to the "main fix"? For context, I'm curious if the fix applied to `rio` could help inspire a similar fix for `wezterm`. I realize they're different stacks, but maybe it could still be a hint?
