### ISSUE TITLE
Homebrew packaging

### ISSUE THREAD

**Issue by silopolis** [raphamorim/rio#353]
Make this sweet ale just a command away from all our *nixy boxes

Thanks in advance :pray: 

TY
J

**Comment by silopolis** [comment]
Oh sorry, should have been more precise... I meant homebrew on Linux, actually!

Thanks for your prompt answer

**Comment by raphamorim** [comment]
Ah i see, would you mind opening an issue regarding brew on linux (so would have with a fresh story)?
