### ISSUE TITLE
Changes in config.toml not taken into account

### ISSUE THREAD

**Issue by FACOLOMBANI** [raphamorim/rio#357]
Any changes i make in config.toml is not being applied. 

```
[fonts]
font-size = 12

[navigation]
mode = "NativeTab"
clickable = true
use-current-path = true

[background]
opacity = 0.8

performance = "High"

[window]
background-opacity = 0.8
```

Version of rio used 0.0.27.

**Comment by raphamorim** [comment]
Hey @FACOLOMBANI thanks for the issue,

What changes you are looking to be reflected?

The file have some error first error i see is should be

```toml
[fonts]
size = 12
```

the other problem is `performance = "High"` should be on top of your file

**Comment by raphamorim** [comment]
Great to know! `use-current-path` for NativeTab and `background-opacity` are coming only for next version (0.0.28).

Closing this issue for now
