### ISSUE TITLE
new bug with ansi escape sequences

### ISSUE THREAD

**Issue by colemickens** [raphamorim/rio#364]
Hi, see the video: https://youtu.be/QlLwUvataok

There's a new (recent-ish) regression around ansi escape sequences. `rio` is on the left, `alacritty` on the right, in the video.

The prompt should show my hostname, but instead shows as a opaque block in Rio, and it seems to affect the cursor as well.

It's also visible in this screenshot:
![screenshot-1701566269](https://github.com/raphamorim/rio/assets/327028/c59c0a29-4cc8-4b23-8241-2e697ec235af)

**Comment by raphamorim** [comment]
Hey @colemickens thanks for the issue,

Is this your version Rio 0.0.28? Could share also the configuration file?

**Comment by raphamorim** [comment]
could reproduce and should be fixed in main, please let me know if not. Closing it for now

**Comment by colemickens** [comment]
Can confirm its fixed. Thanks!
