### ISSUE TITLE
How to set wsl to default shell?

### ISSUE THREAD

**Issue by Mumburo** [raphamorim/rio#365]
Hello, I tried several ways to change the default shell in windows from powershell to wsl but I didn't succeed. Could you tell me if there is a way to do it?

**Comment by raphamorim** [comment]
Hey @Mumburo thanks for the issue,

when you mean wsl are you talking about use bash?

**Comment by Mumburo** [comment]
Yes, I want to set Windows Subsytem for Linux by default shell but I think that it´s a route problem because I tried it in the following way:
- shell = { program = "C:\WINDOWS\system32\wsl.exe", args = []}
- shell = { program = "C:\\WINDOWS\\system32\\wsl.exe", args = []}
- shell = { program = "C:/WINDOWS/system32/wsl.exe", args = []}
- shell = { program = "mnt/c/WINDOWS/system32/wsl.exe", args = []}
- shell = { program = "/WINDOWS/system32/wsl.exe", args = []}
- shell = { program = "wsl", args = []}

Rio recognizes these forms:
- shell = { program = "C:\\WINDOWS\\system32\\wsl.exe", args = []}
- shell = { program = "C:/WINDOWS/system32/wsl.exe", args = []}

but when I open the terminal again it still starts with the version of powershell that comes by default in windows. I also tried changing the default shell to the newer version of powershell but that didn't work either

**Comment by srikkant** [comment]
>
> * `shell = { program = "wsl", args = []}`
> 

@Mumburo - can you try it this way? I have been using this for a while. 

```
[shell]
program = "wsl"
args = []
```

**Comment by Saraccostein** [comment]
Thanks @srikkant, that did work

**Comment by raphamorim** [comment]
Great! Thanks for the help @srikkant
