### ISSUE TITLE
support for advaned formatting (squiggly underline?)

### ISSUE THREAD

**Issue by colemickens** [raphamorim/rio#370]
![screenshot-1701892257](https://github.com/raphamorim/rio/assets/327028/84ff0d7a-d115-4082-8105-4a62c2af9cd5)

As seen in the screenshot, alacritty renders some of my editor warnings with a yellow squiggly underline.

That's not present in `rio`, however. I assume this just isn't implemented yet?

**Comment by raphamorim** [comment]
Is not implemented yet in renderer level but implemented in ansi level, but that would be awesome to have. Saving as wishilist.

**Comment by raphamorim** [comment]
Adding more info on it: https://sw.kovidgoyal.net/kitty/underlines/

**Comment by raphamorim** [comment]
```bash
echo -e "\e[4:1mstraight underline\e[0m"
echo -e "\e[4:2mdouble underline\e[0m"
echo -e "\e[4:3mcurly underline\e[0m"
echo -e "\e[4:4mdotted underline\e[0m"
echo -e "\e[4:5mdashed underline\e[0m"
```

<img width="266" alt="Screenshot 2024-06-07 at 19 37 54" src="https://github.com/raphamorim/rio/assets/3630346/73f30fe5-ce0a-4b60-a561-79a32486953d">

**Comment by raphamorim** [comment]
Implemented in main 👌 closing it for now

<img width="912" alt="Screenshot 2024-08-12 at 20 16 56" src="https://github.com/user-attachments/assets/7ba2c757-b1db-419b-ba03-d971cbe60443">
