### ISSUE TITLE
macOS - Configuration breakage when using font settings in config.toml

### ISSUE THREAD

**Issue by ehjmx** [raphamorim/rio#372]
Hey @ehjmx I think had a regression with this the error UI functionality (isn't the firs time I heard it). Would you mind create an issue?

_Originally posted by @raphamorim in https://github.com/raphamorim/rio/issues/202#issuecomment-1791062727_

It took me a while but finally I managed to create this new issue as requested. 

As soon as I edit one single line in the [fonts] section of the attached rio config.toml the following shell configuration breaks

`shell = { program = "/opt/local/bin/bash", args = ["--login"] }`

I don't get an error message that something is wrong within my config.toml  as shown and implemented in issue #202. However I do get an error if I use those lines
```
[fonts]
family = "CommmitMonno"
```

I initially thought it might be related to me using [ble.sh](https://github.com/akinomyoga/ble.sh) but even when I disable using ble.sh the issue persists and vice versa not using the fonts section in the config.toml leads to respecting the shell configuration and bash starts.

macOS: 13.6.1
font: Commit Mono/Fira Code/Red Hat Mono/Victor Mono/Red Hat Mono it makes no difference. Commit Mono is the font where I know the weight for sure. For every other font listed here I tried the various weight info I found but to no success. 
bash 5.2.21 installed via macports but /bin/bash that comes with macOS is also ignored. 

[rio_030.log](https://github.com/raphamorim/rio/files/13628341/rio_030.log)
[rio_config_2023-12-10.txt](https://github.com/raphamorim/rio/files/13628342/rio_config_2023-12-10.txt)

**Comment by raphamorim** [comment]
@ehjmx is this still happening on 0.1.7?

**Comment by andrewcrook** [comment]
If it helps, I use the following with macOS 14.6.1 and Rio 0.1.10 without issue.

```
[fonts]
family = "FiraCode Nerd font”
size = 11
```

**Comment by raphamorim** [comment]
Thank you for testing it @andrewcrook !
I will close this issue for now but anything let me know
