### ISSUE TITLE
macOS - Configuration breakage when using Window configuration settings in config.toml

### ISSUE THREAD

**Issue by ehjmx** [raphamorim/rio#373]
I don't know if this issue is related to issue #372 or not but it has the same effect.

As soon as I edit one single line in the [window] section of the attached rio config.toml the following shell configuration breaks

shell = { program = "/opt/local/bin/bash", args = ["--login"] }

The difference to issue #372 is that as soon as I comment out the entries below [window] and restart rio the shell settings are respected and bash is loaded. 

macOS: 13.6.1
bash: 5.2.21 installed via macports

[rio_030.log](https://github.com/raphamorim/rio/files/13628402/rio_030.log)
[rio_config_2023-12-10.txt](https://github.com/raphamorim/rio/files/13628403/rio_config_2023-12-10.txt)

**Comment by raphamorim** [comment]
This should be fixed on this current main version (v0.2.0), please lemme know anything and I can reopen.
