### ISSUE TITLE
ERROR: couldn't find a Compose file for locale "en_US.UTF-8"

### ISSUE THREAD

**Issue by 0323pin** [raphamorim/rio#376]
Hi,

Hope you don't mind a few things in the same issue.

After a few patches (I can submit a PR at later stage if, we get this sorted), I've managed to build `rio` on NetBSD. Although, at launch it simply flashes and crashes with the following error:
```
xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.UTF-8" (mapped to "en_US.UTF-8")
```

The output of `locale` on my system is as follows:
```
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="C"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=""
```

With the patches, it builds fine with Rust-1.74.1 but it outputs some warnings.
You might be aware of these already but, leaving them here for information:
```
[...]
warning: unused variable: `utf8`
   --> teletypewriter/src/unix/mod.rs:264:21
    |
264 | pub fn create_termp(utf8: bool) -> libc::termios {
    |                     ^^^^ help: if this is intentional, prefix it with an underscore: `_utf8`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: `teletypewriter` (lib) generated 1 warning (run `cargo fix --lib -p teletypewriter` to apply 1 suggestion)
   Compiling regex v1.10.2
   Compiling tokio-macros v2.1.0
   Compiling mio v0.8.9
   Compiling filetime v0.2.22
   Compiling num_cpus v1.16.0
   Compiling base64 v0.21.5
   Compiling tokio v1.33.0
   Compiling notify v6.1.1
   Compiling clap v4.4.7
   Compiling wa v0.0.30 (/usr/pkgsrc/wip/rio/work/rio-0.0.30/wa)
   Compiling rio-backend v0.0.30 (/usr/pkgsrc/wip/rio/work/rio-0.0.30/rio-backend)
warning: `&` without an explicit lifetime name cannot be used here
  --> rio-backend/src/config/navigation.rs:32:22
   |
32 |     const PLAIN_STR: &str = "Plain";
   |                      ^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #115010 <https://github.com/rust-lang/rust/issues/115010>
   = note: `#[warn(elided_lifetimes_in_associated_constant)]` on by default
help: use the `'static` lifetime
   |
32 |     const PLAIN_STR: &'static str = "Plain";
   |                       +++++++

warning: `&` without an explicit lifetime name cannot be used here
  --> rio-backend/src/config/navigation.rs:33:30
   |
33 |     const COLLAPSED_TAB_STR: &str = "CollapsedTab";
   |                              ^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #115010 <https://github.com/rust-lang/rust/issues/115010>
help: use the `'static` lifetime
   |
33 |     const COLLAPSED_TAB_STR: &'static str = "CollapsedTab";
   |                               +++++++

warning: `&` without an explicit lifetime name cannot be used here
  --> rio-backend/src/config/navigation.rs:34:24
   |
34 |     const TOP_TAB_STR: &str = "TopTab";
   |                        ^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #115010 <https://github.com/rust-lang/rust/issues/115010>
help: use the `'static` lifetime
   |
34 |     const TOP_TAB_STR: &'static str = "TopTab";
   |                         +++++++

warning: `&` without an explicit lifetime name cannot be used here
  --> rio-backend/src/config/navigation.rs:35:27
   |
35 |     const BOTTOM_TAB_STR: &str = "BottomTab";
   |                           ^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #115010 <https://github.com/rust-lang/rust/issues/115010>
help: use the `'static` lifetime
   |
35 |     const BOTTOM_TAB_STR: &'static str = "BottomTab";
   |                            +++++++

warning: `&` without an explicit lifetime name cannot be used here
  --> rio-backend/src/config/navigation.rs:39:27
   |
39 |     const BREADCRUMB_STR: &str = "Breadcrumb";
   |                           ^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #115010 <https://github.com/rust-lang/rust/issues/115010>
help: use the `'static` lifetime
   |
39 |     const BREADCRUMB_STR: &'static str = "Breadcrumb";
   |                            +++++++
[...]
```

As mentioned, I can submit a PR adding support for NetBSD if we can fix the crashes.
Regards

**Comment by 0323pin** [comment]
For reference, http://mail-index.netbsd.org/pkgsrc-wip-changes/2023/12/10/msg028800.html

**Comment by raphamorim** [comment]
Hey @0323pin thanks for the issue,

> The output of locale on my system is as follows:

Hmm, the env does look correct. (cc @orhun do you have an idea what could be?)

>  You might be aware of these already but, leaving them here for information:

Ah thanks! Rio is using 1.73 right now but is good to know what I will need to update for the next versions.

**Comment by orhun** [comment]
Yeah the env looks correct to me as well, I have the following env:

```
LANG=en_US.utf-8
LC_CTYPE="en_US.utf-8"
LC_NUMERIC="en_US.utf-8"
LC_TIME="en_US.utf-8"
LC_COLLATE="en_US.utf-8"
LC_MONETARY="en_US.utf-8"
LC_MESSAGES="en_US.utf-8"
LC_PAPER="en_US.utf-8"
LC_NAME="en_US.utf-8"
LC_ADDRESS="en_US.utf-8"
LC_TELEPHONE="en_US.utf-8"
LC_MEASUREMENT="en_US.utf-8"
LC_IDENTIFICATION="en_US.utf-8"
LC_ALL=en_US.utf-8
```

And I get the following error when I launch `rio` (no crashes):

```
xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.utf-8" (mapped to "en_US.utf-8")
```

I looked around the internet about this error and [what I found](https://forum.endeavouros.com/t/kwin-xkbcommon-xkb-couldnt-find-a-compose-file-for-locale-en-in-mapped-to-en-in-iso8859-1/41943) was hilarious:

> If you machine is running OK - ignore. KDE is overly “verbose” and really needs to STFU :rofl:

> I simply changed to en_US from language settings, can’t waste much time in this thing

Famous last words on some [Manjaro forum](https://forum.manjaro.org/t/kwin-xkbcommon-xkb-couldnt-find-a-compose-file-for-locale-en-in/77141):

> Thank you Sir for your advice. I shall check and update here soon.

- https://github.com/davatorium/rofi/issues/400
> Fix your locale to en_US.UTF-8. :-)

So I have no idea about what is going on.

**Comment by 0323pin** [comment]
Thank you both.
I did find some of those links also but ...

> And I get the following error when I launch rio (no crashes):

Exactly what I would expect, it shouldn't crash but, I get no other output.
I'll try playing around with linking `libxkbcommon` and see if that helps. Maybe adding `xkeyboard-config` and/or `xkbcomp` into it as well.

**Comment by raphamorim** [comment]
> EDIT: would you expect it to crash if a config file is not present?

Wan't supposed to crash.

> I'll try playing around with linking libxkbcommon and see if that helps. Maybe adding xkeyboard-config and/or xkbcomp into it as well.

Let me know how it goes, Rio considers that libxkbcommon is a dep (https://raphamorim.io/rio/docs/install/build-from-source)

<img width="645" alt="Screenshot 2023-12-11 at 11 52 55" src="https://github.com/raphamorim/rio/assets/3630346/1936c519-d1a3-4fc3-8225-f1e2f8104f0a">

**Comment by 0323pin** [comment]
@raphamorim I'll try again tomorrow, I simply don't have time today.

Would you happen to know what's the minimum required version of `Mesa`?

**Comment by raphamorim** [comment]
Last time I ran with latest if I am not mistaken, but good to remind that mesa-* are only required by non-NVIDIA GPUs

**Comment by 0323pin** [comment]
> Last time I ran with latest if I am not mistaken, but good to remind that mesa-* are only required by non-NVIDIA GPUs

This is not consistent with the documentation, quoting
> If you're running Wayland with an Nvidia GPU, you'll likely want the EGL drivers installed too (these are called libegl1-mesa-dev on Ubuntu).

I don't have a NVIDIA GPU, is `mesa` needed or, not?

**Comment by 0323pin** [comment]
@raphamorim I've just bumped the wip (work in progress) package to 0.0.33 and added a few dependencies and explicit compiler linkage to see if I could fix the crashes.

But, I'm still having the same issue 😞 

Is there a way to get some more verbose output in order to debug this?

One build warning in case you are interested:
```
warning: unused variable: `utf8`
   --> teletypewriter/src/unix/mod.rs:264:21
    |
264 | pub fn create_termp(utf8: bool) -> libc::termios {
    |                     ^^^^ help: if this is intentional, prefix it with an underscore: `_utf8`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: `teletypewriter` (lib) generated 1 warning (run `cargo fix --lib -p teletypewriter` to apply 1 suggestion)
```

**Comment by 0323pin** [comment]
Another observation @raphamorim and @orhun, `rio` doesn't actually crash, it simply exits with `exit code 0` and there's nothing in `stdout/stderr`. I've tried piping `rio -e <some CLI app>` to a file but, it outputs **nothing**. It's very difficult to debug when it exits without printing a reason.

**Comment by orhun** [comment]
FWIW just realized I get the same warning/error with `alacritty` as well.

**Comment by 0323pin** [comment]
> FWIW just realized I get the same warning/error with `alacritty` as well.

Thanks. I use `alacritty` myself

![2024-01-12-224320_959x368_scrot](https://github.com/raphamorim/rio/assets/90570748/88fed35d-872b-4672-9275-8fb60003cb1e)

and, didn't notice it. But, you are right, it outputs the same warning.
It doesn't exit, though.

**Comment by 0323pin** [comment]
I've updated to 0.0.34 but, the same happens. I'm convinced this has nothing to do with locale but, I'm lost on how to debug this when there are no coredumps or logs to go through.

The terminal simply flashes for a fraction of a second, I can see the colors and the message "Welcome to rio ..."
