### ISSUE TITLE
Rio frozen and unresponsive on Arch Linux Wayland (nvidia)

### ISSUE THREAD

**Issue by zackartz** [raphamorim/rio#380]
Hello! 

I have been trying to get rio working on arch linux & hyprland with no luck. [debug log here](https://gist.github.com/zackartz/6f3652236513e7241314dc6ec7e0e78f). If anyone knows what to do to fix this I would appreciate it!

**Comment by raphamorim** [comment]
Hey @zackartz thanks for the issue,
I suppose it renders but then get stuck right?

**Comment by zackartz** [comment]
@raphamorim yeah, it renders one frame and gets stuck, i have done a little digging and i believe this is an upstream winit issue as their examples don't seem to be working for me, and lapce also behaves similarly

**Comment by zackartz** [comment]
interestingly, neovide works fine, and uses the same winit version (0.29.4)

**Comment by raphamorim** [comment]
Hey @zackartz is this still happening in the 0.0.34?

**Comment by henriquekirchheck** [comment]
Same thing here in NixOS and Hyprland on Nvidia. I have some logs from the app when I ran it with `RIO_LOG_LEVEL=debug`

[logs.txt](https://github.com/raphamorim/rio/files/13955506/logs.txt)

**Comment by zackartz** [comment]
i added a `println!` on the render event in the main event loop, and it is only called once

**Comment by zackartz** [comment]
adding a `println!` to the top of the event loop, logging each event, outputs this before freezing.
[log.txt](https://github.com/raphamorim/rio/files/13979821/log.txt)

**Comment by raphamorim** [comment]
Wonder if replace clipboard with https://crates.io/crates/copypasta will fix this issue.

**Comment by yofriadi** [comment]
I also experienced this with RiverWM, also it doesnt get resized when I try resize it.

**Comment by TitanNano** [comment]
I'm also experiencing this on Fedora 39. Both on `master` and on `0.0.x`

**Comment by zackartz** [comment]
Did some digging, [looks like its stuck waiting to grab a new texture](https://github.com/raphamorim/rio/blob/main/sugarloaf/src/sugarloaf.rs#L359). Maybe a VSYNC related issue?

**Comment by johnghall** [comment]
Also experiencing this on Sway + nvidia

**Comment by zackartz** [comment]
found it! This is a wgpu issue [gfx-rs/wgpu/#4775](https://github.com/gfx-rs/wgpu/issues/4775), and while the issue is still open, if you change the Cargo.toml to pull wgpu from git the problem goes away.

**Comment by raphamorim** [comment]
wow, such a good finding! Is the fix in the main branch?

**Comment by postsolar** [comment]
I can confirm that the fix suggested by @zackartz works.
Input latency is very high though. I used the flake provided in this repo to build Rio.

**Comment by zackartz** [comment]
@raphamorim i did some more testing, it looks like it works as long as wgpu is called from git, i tested the branch `trunk`, as well as tags from `1.19.3` to `1.18.2` (anything older wouldn't build) and they all perform about the same. I can also confirm the high input latency.
