### ISSUE TITLE
Frameless windows on Windows

### ISSUE THREAD

**Issue by melMass** [raphamorim/rio#384]
Hi,

Would it be possible to add support for frameless windows on Windows?
I use a WM and loose precious spaces from those bars, alacrity does but I have other issues with it on windows that I don't have in rio.

On a similar note I get a "spawn" delay when creating multiple rio windows as seen in the recording:

https://github.com/raphamorim/rio/assets/7041726/1588706a-921e-4bed-a128-0fdf58daf9fc

Btw I also made a scoop recipe for rio [here](https://github.com/melMass/scoop-mtb/blob/master/bucket/rio.json)

**Comment by raphamorim** [comment]
Hey @melMass thanks for the issue,

I think is possible, could you send a screenshot how alacritty is with frameless borders?

**Comment by melMass** [comment]
Yep here you go :)


https://github.com/raphamorim/rio/assets/7041726/a453680c-0ea1-4700-ae43-27903713f952

**Comment by raphamorim** [comment]
I've pushed a commit to main that allows specify the windows decoration, you can set 

```toml
[window]
decorations = "Disabled"
```

Should look like this

<img width="340" alt="Screenshot 2023-12-13 at 18 36 54" src="https://github.com/raphamorim/rio/assets/3630346/5f5d6816-96ed-4052-b169-2bb6648a5ed6">

For now I am closing this issue, but will add this property to next release

**Comment by melMass** [comment]
You rock!! Thanks a lot
