### ISSUE TITLE
fonts.extras not effect

### ISSUE THREAD

**Issue by shenghui0779** [raphamorim/rio#395]
[version]
0.0.33

[MacOS]
Monterey

[description]
<img width="927" alt="image" src="https://github.com/raphamorim/rio/assets/67535398/8c9498bd-13da-4642-b613-e240c4e3c195">

**Comment by raphamorim** [comment]
Hey @shenghui0779 sorry for the delay, could you try using the version 0.1.6?

Is the font family you are looking for installed right?
