### ISSUE TITLE
Background Opacity breaks black text with background color

### ISSUE THREAD

**Issue by TitanNano** [raphamorim/rio#403]
As soon as I set the `background_opacity` to something lower than `1.0`, text that is black and has a background color is no longer visible.

<img width="1026" alt="image" src="https://github.com/raphamorim/rio/assets/4500858/65fcc90c-c34b-44d9-afd5-6b2f5588af3f">

**Comment by raphamorim** [comment]
Hey there @TitanNano thanks for the issue, isn't `background-opacity` (with `-`)?

Hmm, will try to reproduce, which version is that?

**Comment by TitanNano** [comment]
> isn't `background-opacity` (with `-`)?

yes right.

> which version is that?
0.0.33

**Comment by mycraftmw** [comment]
same issue on archlinux with rioterm 0.0.34

**Comment by Brianalmeida** [comment]
Same issue on SLES 15 SP6. Oddly enough, when spawning a new term in Sway, the first terminal has a black background, but when you exec rio in the terminal, it then picks up the background opacity. Not sure if y'all see this behavior, too.

Environment:
- Rio version 0.0.34
- SLES 15 SP6
- SwayWM (1.6.1)

**Comment by TitanNano** [comment]
@raphamorim this is fixed in rio 0.0.39
