### ISSUE TITLE
Feature Request: Allow Setting Window Class and/or Title

### ISSUE THREAD

**Issue by Airradda** [raphamorim/rio#405]
It would be nice to be able to declare the window class/title (i.e Alacritty's `--class`/`--title`) as it allows window managers to handle a specific window when multiple are open.

**Comment by raphamorim** [comment]
Hey @Airradda thanks for the issue,

Is that feature available for linux only?

**Comment by Airradda** [comment]
I believe so. I don't know if Window's has a similar or slightly different concept.
