### ISSUE TITLE
Text isn't rendering on input after new tab creation

### ISSUE THREAD

**Issue by hougesen** [raphamorim/rio#409]
I am unsure whether this is me, rio or because main isn't meant to be used. But text rendering seems to be broken after opening new tabs.

I am running rio (legacy) built from source (98ec897) on Wayland && Ubuntu 23.10. I haven't deep dived the issue, but it seems to be present as far back as 3d320a7.

I am not able to replicate the issue on the `0.0.x` branch using b79611e.

[Screencast from 2024-01-12 23-56-53.webm](https://github.com/raphamorim/rio/assets/56034786/0f7edad9-9a90-4f6b-bd1d-011859c69cf2)

**Comment by raphamorim** [comment]
Ah thanks for reporting it, I know what it's. The new version starts with column 2/rows 1 and then run a resize event, but I haven't fixed that yet.

**Comment by raphamorim** [comment]
@hougesen could you try again? it fixed for me locally now

**Comment by hougesen** [comment]
It works perfectly now.

Was about to make a PR myself. The issue was pretty easy to locate after I got this error message 😅 

![image](https://github.com/raphamorim/rio/assets/56034786/56e4c0f3-76d2-466d-b74d-2aab7bc59031)

**Comment by raphamorim** [comment]
Thank you for reporting! completely forgot to update it after merge 0.0.x into main 🙏
