### ISSUE TITLE
Rio is damaged and can't be opened

### ISSUE THREAD

**Issue by leandromoreira** [raphamorim/rio#41]
<img width="910" alt="image" src="https://github.com/raphamorim/rio/assets/55913/d9b664f9-14ca-4bde-af3f-ea67ff51e1b1">

I can't run Rio, it keeps crashing when I try to open it.

**Comment by tfmoraes** [comment]
Try to follow this tutorial https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

**Comment by alexmhansen** [comment]
> Try to follow this tutorial https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

This worked for me on M1 (arm64). Specifically this instruction:

`xattr -d com.apple.quarantine /path/to/app.app`

**Comment by raphamorim** [comment]
> Try to follow this tutorial https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

Yes, is also in the documentation https://raphamorim.io/rio/download/

<img width="974" alt="Screenshot 2023-05-25 at 05 50 39" src="https://github.com/raphamorim/rio/assets/3630346/ff60790d-3306-4819-a5f6-614ba9f0055f">

Although not the best solution, hopefully will notarize it soon. Closing this issue for now.

**Comment by raphamorim** [comment]
For reference, notarized the application. Adding it to homebrew https://github.com/Homebrew/homebrew-cask/pull/149824
