### ISSUE TITLE
rioterm-beta crate build failure (E0601)

### ISSUE THREAD

**Issue by bagasme** [raphamorim/rio#416]
Hi,

I'm trying to build Rio on latest main (commit 063f6f55fd16607f6932aed00cead3dd30436f4b) on my Arch Linux system.
I use cargo from rustup and follow [the build instructions](https://raphamorim.io/rio/docs/install/build-from-source)
(I build by `cargo build --release`). The build errored out on rioterm-beta crate, where the output was:

```
...
   Compiling rioterm-beta v0.1.0 (/home/bagas/repo/rio/frontends/rioterm-beta)
   Compiling rioterm v0.0.35 (/home/bagas/repo/rio/frontends/rioterm)
error[E0601]: `main` function not found in crate `rio_beta`
   --> frontends/rioterm-beta/src/main.rs:138:2
    |
138 | }
    |  ^ consider adding a `main` function to `frontends/rioterm-beta/src/main.rs`

For more information about this error, try `rustc --explain E0601`.
error: could not compile `rioterm-beta` (bin "rio-beta") due to previous error
...
```

But indeed (to my naive eyes), there already existed `main()` function in the culprit file mentioned in above error:

``` rust
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    ...
}
```

Maybe cargo doesn't really see above `main()`?

**Comment by raphamorim** [comment]
ah sorry you are trying to build rioterm right (reopened the issue), you need to exclude rioterm-beta from the build either using `--workspace --exclude rioterm-beta` or use `-p rioterm`
