### ISSUE TITLE
[BUG] Background opacity 

### ISSUE THREAD

**Issue by undefusr** [raphamorim/rio#422]
Background opacity just working after changes in config or openning another rio window as you see on video below.

I tried a lot of combinations in config and nothing its working.

https://streamable.com/9ov3t3

https://veed.io/view/985b7311-07e6-44c9-a116-acfa9bcdc296

**Comment by Trevor-Opiyo** [comment]
I have had this issue for a while but the [latest beta](https://github.com/raphamorim/rio/releases/tag/nightly) seems to fix it for me.

**Comment by undefusr** [comment]
@Trevor-Opiyo whats the version that you use? and whats your OS?

**Comment by undefusr** [comment]
Its solved now in the last beta version. I would suggestion to create --HEAD formula to use nightly build. WDYT? @raphamorim

**Comment by Trevor-Opiyo** [comment]
@undefusr I would also not suggest a --HEAD formula as the nightly is unstable. These changes eventually filter down to the release builds as they are tested and verified.

**Comment by raphamorim** [comment]
This issue should not be able to reproduce with the latest release (v0.1.0), closing this issue for now. In case find anything odd please let me know and we can reopen or create a new issue.

**Comment by httyd98** [comment]
Background Opacity not working on Rio Version 0.1.17 (20230528.115631), MacOS Sequoia 15.0.1 (24A348).
