### ISSUE TITLE
Rio not rendering text starting from tag 0.0.22

### ISSUE THREAD

**Issue by tranzystorekk** [raphamorim/rio#429]
Did a quick bisect and a tag 0.0.21 the text still renders normally:

![image](https://github.com/raphamorim/rio/assets/5671049/14d356aa-ebc4-4a9a-9808-0554e5170a60)

And at least from commit https://github.com/raphamorim/rio/commit/1ed56c334a192d14516e4372491459f3c69d91bb :

![image](https://github.com/raphamorim/rio/assets/5671049/8633d269-4139-4dee-ba41-ef22b6fe6d23)

Tested on a Vmware virtual machine with a wayland compositor (`labwc 0.6`)

**Comment by tranzystorekk** [comment]
Logs with `RIO_LOG_LEVEL=info`:

Log with the issue present: [log-bad.txt](https://github.com/raphamorim/rio/files/14013975/log-bad.txt)

Log without the issue: [log-good.txt](https://github.com/raphamorim/rio/files/14013976/log-good.txt)

**Comment by tranzystorekk** [comment]
Unless wgpu and/or vmware get their sh*t together, I'm not sure if there's a viable fix for this :/

**Comment by tranzystorekk** [comment]
At least when using the mesa drivers, a reliable workaround seems to be setting `LIBGL_ALWAYS_SOFTWARE=1` to force software rendering.

**Comment by raphamorim** [comment]
Good finding! Looks related as well https://github.com/gfx-rs/wgpu/issues/1443 , https://github.com/microsoft/wslg/issues/469
