### ISSUE TITLE
"focus event" handling for tab/window navigation

### ISSUE THREAD

**Issue by mfbolus** [raphamorim/rio#434]
Thank you for your great work on this project!

I am not entirely sure if I am asking this the right way, but I use an editor from the terminal (currently playing with helix) which I have set to do things like save/format an active buffer when "focus" is moved away from the tab/window. This feature works in Alacritty, for example. I also see [on the helix wiki](https://github.com/helix-editor/helix/wiki/Terminal-Support#focus-events) that rio nominally supports this. 

For whatever reason, while this feature works when I am using Alacritty, nothing gets triggered by focus events when I am editing within rio. I am not sure if there is a rio configuration I am missing. Has anyone else noticed this issue? Do you have any suggestions for where to start in debugging this behavior?

Best, 
MFB

**Comment by hougesen** [comment]
Is [`use-kitty-keyboard-protocol`](https://raphamorim.io/rio/docs/features/kitty-keyboard-protocol/) enabled in your config?

**Comment by mfbolus** [comment]
I did not have it enabled, but I just set this to 'true', relaunched rio, and am getting the same behavior (or lack of) as before. MFBOn Jan 26, 2024, at 08:51, Mads Hougesen ***@***.***> wrote:﻿
Is use-kitty-keyboard-protocol enabled in your config?

**Comment by raphamorim** [comment]
Thank you for the issue, @mfbolus!

Which version are you using and which OS?

**Comment by mfbolus** [comment]
@raphamorim , yes that would be useful information, wouldn't it?!

rio v0.0.34
macOS v14.3

**Comment by raphamorim** [comment]
> @raphamorim , yes that would be useful information, wouldn't it?!

haha sometimes not 😆 

Will take a look, I think i have ported it from Alacritty. will check and update her

**Comment by raphamorim** [comment]
I figured out, it was not implemented. I've added the support to windows and linux here https://github.com/raphamorim/rio/commit/4ad69ffd5402cebd34e6acfe04bb0e6dd05f1752 but still need to port to the new macos client (upcoming 0.1.0)

**Comment by mfbolus** [comment]
Wow, that was fast! Nice work. Thank you
