### ISSUE TITLE
Ability to overwrite / uninstall keybindings

### ISSUE THREAD

**Issue by mt-inside** [raphamorim/rio#460]
Similar to #419 - currently adding a keybinding with the same keys as a built-in one doesn't replace it, it seems to add it to a list.
I can see why this behaviour is useful, but I also think the ability to override built-ins in a must. I also plain want to remove some built-in ones, like cmd+W on the mac - just closes the window without confirmation, bang, work gone! It's so easy to hit it when you're going for Ctrl+W (readline delete word). I've lost so much work I've nearly stopped using Rio.

Maybe the solution is a config command that clears the current action(s) for a key
`{ key = "w", with = "super", action = "Clear" }`

I then have maximum flexibility to:
* Remove built-in binding, leaving key combo doing nothing
* Remove built-in and add one or more of my own instead
* Add my own on top of the built-in

I someone wanted to build the partial feature quickly, just changing the behaviour to overwrite (maybe a config option for this) would let me re-configure cmd+W to type "idiot" or something for now 😅

**Comment by raphamorim** [comment]
Hey @mt-inside thanks for the issue,

Actions `None` or `ReceiveChar` doesn't fit for your case? https://raphamorim.io/rio/docs/key-bindings#overwriting

**Comment by raphamorim** [comment]
Regarding the configuration, if you don't use tmux or similar you can use `navigation` as plain https://raphamorim.io/rio/docs/navigation#plain

**Comment by mt-inside** [comment]
> Hey @mt-inside thanks for the issue,
> 
> Actions `None` or `ReceiveChar` doesn't fit for your case? https://raphamorim.io/rio/docs/key-bindings#overwriting

Thanks for the reply!

`Action="None"` does indeed remove the keybinding. This is great, just what I needed, dunno how I missed that part of the docs.

However I think the docs are a little wrong. Because I hadn't seen Action=None, I was using `text="Idiot"` just to try to have something intercept Super+W and do something other than close the window. That does add to the existing binding - if I have Rio running tmux, and press Super+W, bang the window's gone, and when I reattach to that tmux, there's the text "Idiot". Is it possible that the overwrite behaviour is matching all three fields (`key`, `with`, and `action`) rather than just `key` and `with` ?

**Comment by mt-inside** [comment]
> Regarding the configuration, if you don't use tmux or similar you can use `navigation` as plain https://raphamorim.io/rio/docs/navigation#plain

Ah cool, I'd missed that too. Do "tabbing" keybindings include Super+Q and Super+W though? I'm fine now because I have the action=None solution, but probably worth clarifying in the docs.

**Comment by raphamorim** [comment]
>  Do "tabbing" keybindings include Super+Q and Super+W though?

Yes! :D  but you can disable with `None`

Closing this issue for now, sorry for late reply!
