### ISSUE TITLE
bug: vi mode on Windows

### ISSUE THREAD

**Issue by yofriadi** [raphamorim/rio#462]
on Windows, when Vi mode key pressed `Alt + Shift + Space`, it will launch menu instead.
![image](https://github.com/raphamorim/rio/assets/24536844/349dde3c-a866-4c0e-8bcb-f5ae7dc39f62)

Alacritty handle this well on Windows, but it have `Ctrl + Shift + Space` shortcut instead.

note: since I use tmux, this basically unneeded since in tmux there is copy mode

**Comment by raphamorim** [comment]
Ah, yes.. it does make sense to be Cntrl+Shift+Space. Marking it as a bug, thanks for the report
