### ISSUE TITLE
BottomTab does not update on windows when switching tab and exit immediately

### ISSUE THREAD

**Issue by neeraj9** [raphamorim/rio#473]
rioterm 0.0.31

Issue:
- There are times when the bottom (maybe top as well but not tested) tab view do not update immediately.

Steps:
1. Start Rio
2. create a new tab via "ctrl+shift+T"
3. switch back to original tab via "ctrl+shift+tab"
4. exit

Notice that the tab view do not update immediately. If I press enter then sometimes it updates.

**Comment by raphamorim** [comment]
Hey @neeraj9 sorry for the delay,

All tabs have a delay to update to reduce CPU consumption, but I think might be a good idea to allow users to customize it by a configuration property

**Comment by raphamorim** [comment]
This was fixed on v0.1.17 (it will update whenever is idle and have updates), closing this issue for now.
