### ISSUE TITLE
Are ligatures actually supported in 0.0.36?

### ISSUE THREAD

**Issue by driverkt** [raphamorim/rio#488]
I'm running 0.0.36. It says on the website that ligatures are supported. I didn't see anything specific in the docs about enabling them, but I did see in the example config that `[renderer] level = 1` might enable them? I cannot seem to get them to work. I'm using JetBrainsMono Nerd Font.

**Comment by raphamorim** [comment]
Hey @driverkt,

Thanks for the issue! Ligatures will be available in the 0.1.x version which are currently under development in the main. I apologize the confusion, mostly because I am updating the website to match with 0.1.x but doesn't have a filter to versions yet in the website.
