### ISSUE TITLE
Changing zellij pane with <alt> + arrow does not work

### ISSUE THREAD

**Issue by mpizenberg** [raphamorim/rio#501]
I’m using rio v0.0.37 in macos (both are new for me).
I’ve set `option-as-alt = 'left'` which works for creating new panes with `<alt>+N`, but the `<alt>+arrow` shortcut do not seem to work. Any advice on how to make it work?

**Comment by mpizenberg** [comment]
Thanks for the advice @raphamorim it seems to work!

I had only tried with `true` thinking `false` was already the default as it was the commented setting in the template config.

**Comment by raphamorim** [comment]
Ah that's great to know! It's `true` only on macos to match with Terminal.App behaviour.

Will close this issue for now, lemme know anything!
