### ISSUE TITLE
cursor hidden on htop

### ISSUE THREAD

**Issue by avelino** [raphamorim/rio#51]
the cursor is always visible when you open htop

<img width="947" alt="Screenshot 2023-05-25 at 10 18 53" src="https://github.com/raphamorim/rio/assets/31996/3f3fb47b-a352-41c8-b276-aaa2a604a45a">

**Comment by raphamorim** [comment]
Fixed in de03d64

<img width="912" alt="Screenshot 2023-05-27 at 08 22 02" src="https://github.com/raphamorim/rio/assets/3630346/0962806c-8811-4b26-b5b5-e57c2904e87a">
