### ISSUE TITLE
When init ssh session backspace and navigation with ctrl dont work as expected

### ISSUE THREAD

**Issue by iagocavalcante** [raphamorim/rio#511]
When I'm logged into an SSH session on another machine, the backspace and cursor navigation don't work. It's strange behavior.

**Comment by raphamorim** [comment]
Hey @iagocavalcante thanks for the issue,

Would this fix your issue https://raphamorim.io/rio/docs/next/frequently-asked-questions/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-dont-work ?

**Comment by iagocavalcante** [comment]
Yeaaah, thanks <3
