### ISSUE TITLE
Visible lines on transparent background

### ISSUE THREAD

**Issue by orhun** [raphamorim/rio#512]
Hey, just built the latest version of `rio` (`0.39.0`) for Arch repos.

For some reason there are some black lines in the transparent background:

![image](https://github.com/raphamorim/rio/assets/24392180/8001425f-da34-4331-8a51-a8cadbc00cef)

vs `0.37.0`

![image](https://github.com/raphamorim/rio/assets/24392180/246dd8d8-6e9c-482d-8425-e2d02a7b3d21)

I guess I will hold updating the package to the latest version until we figure out what is going on 🐻

**Comment by raphamorim** [comment]
Good call, you are using default configuration but with transparency on right?

**Comment by orhun** [comment]
Yup

**Comment by sandeepkalra** [comment]
@raphamorim I want to add something that may help you narrow this down or maybe this is a different bug with same outcome.
  I am seeing this same issue on my setup(w/ ver 0.0.39) as well, but there is one slight difference. This is only happening on external monitor (Dell, with all frequencies 144Hz to 60Hz) and not on Mac default screen (or at least not visible to me). And this does not go away if I swap HDMI (8k) with USB-C/DisplayPort Cable.

**Comment by orhun** [comment]
This issue is fixed in `0.0.x` branch for me.

**Comment by raphamorim** [comment]
Thanks @orhun for testing,

This issue should not be able to reproduce with the latest release (v0.1.0), closing this issue for now. In case find anything odd we can reopen or create a new issue.
