### ISSUE TITLE
Backspace key inserts blank character instead of deleting in SSH session

### ISSUE THREAD

**Issue by jdedea** [raphamorim/rio#524]
When hitting the backspace key in an SSH session, instead of deleting previous characters it creates a blank character in the terminal but on the server registers it as deleted. This happens in all SSH sessions.

Rio Version: 0.0.39
OS: Mac Sonoma 14.5
Model: Apple M3 Pro

![Screenshot 2024-06-06 at 11 51 07 AM](https://github.com/raphamorim/rio/assets/71328887/60f11195-5ae2-400d-9c68-a1964b7c97ed)

**Comment by raphamorim** [comment]
Hey @jdedea thanks for the issue,

I believe is related to your terminfo ins’t installed in the server you are connecting with. More info here https://raphamorim.io/rio/docs/next/frequently-asked-questions/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-dont-work

**Comment by jdedea** [comment]
You were 100% correct! Thank you so much for the help!

**Comment by raphamorim** [comment]
glad it worked well 🙏

**Comment by morihaya** [comment]
Although this issue is already closed and the link provided in the answer is not found, I was able to resolve the problem with the following setting. I'm leaving this note here for reference:

```sh
export TERM=xterm-256color
```
