### ISSUE TITLE
powershell argument "-nologo" not working

### ISSUE THREAD

**Issue by TheAjaykrishnanR** [raphamorim/rio#531]
currently on v0.0.38

using the following config :

```
[shell]
program = "pwsh"
args = ["-nologo"]
```

Expected behavior : 

No powershell startup message

However the startup message still shows

**Comment by ahaoboy** [comment]
Try this?
```
[shell]
program = "pwsh -nologo"
args = []
```

**Comment by TheAjaykrishnanR** [comment]
That seems to have fixed it !
