### ISSUE TITLE
Vertical line box-drawing characters, aren't straight

### ISSUE THREAD

**Issue by yavko** [raphamorim/rio#534]
The title pretty much says it all, here is a screenie I took in helix, to show this.
I looked at each open issue title, and couldn't find one similar, but I could be wrong, so sorry if its a duplicate.
<details>
<summary>screenies</summary>

![image](https://github.com/raphamorim/rio/assets/15178513/a88da751-49aa-46b3-b455-539d0b20d494)
![image](https://github.com/raphamorim/rio/assets/15178513/d8b83294-ee71-4226-87bc-4220fbc2d193)

</details> 

Seems to also occur with these characters too
<details>
<summary>similar characters</summary>

![image](https://github.com/raphamorim/rio/assets/15178513/e237f231-8a91-4e97-93fb-60c39eff02a2)

</details> 
I don't know how to copy characters in a visual editor in rio, so I can't copy them into here

EDIT: btw im using `0.1.0`

**Comment by raphamorim** [comment]
Thanks for the issue @yavko ! Yes, this is a known issue (in my head at least haha) for 0.1.0 (although it was fixed in 0.0.x version). The cells in 0.1.0 version aren't following the strict dimensions, I plan to fix it for the next versions but allow the cell dimensions behavior to be configurable via config.

**Comment by MrPandir** [comment]
I will also add that this broke many cli applications, in my case `btop` and `superfile`

<img width="1423" alt="Screenshot 2024-06-11 at 09 48 24" src="https://github.com/raphamorim/rio/assets/137798474/93f2f563-b506-4492-bc30-6057ecc6477e">
<img width="1423" alt="Screenshot 2024-06-11 at 09 48 59" src="https://github.com/raphamorim/rio/assets/137798474/1ab39a19-3090-4b83-b201-2cf987e24c34">

**Comment by raphamorim** [comment]
Ah thanks for the CLIs you shared @yavko , I was having a tough time debugging this issue   
<img width="940" alt="Screenshot 2024-06-11 at 11 19 22" src="https://github.com/raphamorim/rio/assets/3630346/9f13d1c8-b431-4564-8d61-a1c1f1d25f30">

I figured out how to fix (i believe at least) ^, but will do a proper fix to main branch

**Comment by cavivie** [comment]
I would also like to add that this problem can also occur when there are Chinese or other languages ​​​​in the directory (I have not tested other languages ​​​​).

**Comment by raphamorim** [comment]
This should be fixed on 0.1.2, closing it for now. Please let me now anything.

<img width="709" alt="Screenshot 2024-07-21 at 13 25 37" src="https://github.com/user-attachments/assets/3494be96-db59-469f-8397-464279385074">
<img width="900" alt="Screenshot 2024-07-21 at 13 26 19" src="https://github.com/user-attachments/assets/439d1284-b8c2-49f7-b2e3-e9fae2fafa49">
