### ISSUE TITLE
[Bug] select one line above

### ISSUE THREAD

**Issue by MrPandir** [raphamorim/rio#535]
This behavior was introduced in version `0.1.0`

https://github.com/raphamorim/rio/assets/137798474/c796e6a1-5f4c-470d-9dd8-c4740931abfb

**Comment by TitanNano** [comment]
I have also come across this issue, but only when choosing something other than `BottomTab`.

**Comment by serverwentdown** [comment]
Similar here

**Comment by hustcer** [comment]
Same here in `CollapsedTab` mode

**Comment by MrPandir** [comment]
This was fixed in version https://github.com/raphamorim/rio/releases/tag/v0.1.3.


https://github.com/user-attachments/assets/6ecb35a0-33ee-44fc-a32d-f23272d28554

**Comment by serverwentdown** [comment]
Amazing work @raphamorim! Really enjoying the terminal
