### ISSUE TITLE
[Bug] switch tabs doesn't work

### ISSUE THREAD

**Issue by MrPandir** [raphamorim/rio#536]
The keyboard shortcut `command` + number does not work in version `0.1.0`

**Comment by jdedea** [comment]
Weirdly enough for me I am able to get it working but only after I click. (ex: Cmd + 1 then left click works)

**Comment by raphamorim** [comment]
Hey there! Thanks for the issue @jdedea !

I am not able to reproduce this issue, is the window focused when the keybinding is triggered?
