### ISSUE TITLE
Switching Monitors Causes Text to Disappear

### ISSUE THREAD

**Issue by jdedea** [raphamorim/rio#538]
When switching between monitors on a Macbook Pro M3, the text disappears and does not get rendered even after typing, resizing, etc. 

Rio Version: 0.1.0
Mac Version: MacOS 15 Sequoia Developer Beta (could be the problem itself, will check on another PC later and provide an update if able to).

Here is how it looks on monitor one:
![Screenshot 2024-06-11 at 6 48 24 am](https://github.com/raphamorim/rio/assets/71328887/5fa6d5b1-db68-4b9d-a153-e7a47141b841)

Here is how it looks when moved:
![Screenshot 2024-06-11 at 6 48 36 am](https://github.com/raphamorim/rio/assets/71328887/c91b0c9d-525e-4008-be99-17b19882cb16)

Commands still work (ex using "clear"): 
![Screenshot 2024-06-11 at 6 48 43 am](https://github.com/raphamorim/rio/assets/71328887/407b4796-6bc7-488a-8c38-b0934700373e)

**Comment by raphamorim** [comment]
thanks for the issue @jdedea ,

wow never saw that happening before tbh, I will try to update my macos version to debug it

**Comment by raphamorim** [comment]
Hey there, is this happening on 0.1.3?

**Comment by jdedea** [comment]
Not anymore! Seems to be fixed, including the re-rendering when switching between monitors and resizing the window!

**Comment by raphamorim** [comment]
Yahooo! Thanks for testing
