### ISSUE TITLE
bash: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)

### ISSUE THREAD

**Issue by div002123** [raphamorim/rio#541]
system: macos 14.5 (m3)
 
Every time I execute a Git operation, I get this error. I don't have this issue when I use the system's built-in terminal.

```sh
bash: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
```

**Comment by MrPandir** [comment]
@div002123 I think this is not a terminal issue, but rather your configuration. The Mac Terminal configures this for you, for easy use.

This may help you solve the problem: [os-x-terminal-bash-warning-setlocale-lc_ctype-cannot-change-locale](https://www.cyberciti.biz/faq/os-x-terminal-bash-warning-setlocale-lc_ctype-cannot-change-locale/)

**Comment by div002123** [comment]
@MrPandir Thanks！
I comment this in `/etc/ssh/ssh_config` and problems solved:
```
# Host *
#    SendEnv LANG LC_*
```
