### ISSUE TITLE
[Bug] Rendering freezes quickly after starting

### ISSUE THREAD

**Issue by lukeh990** [raphamorim/rio#545]
rio version 0.1.0
Arch Linux kernel version 6.9.4

Rio has been my favorite terminal emulator for quite some time now. I don't recall if this issue started after a recent update but now quickly after starting rio the whole interface freezes. No blinking cursor and no response to typing. The only way I know the shell isn't frozen is when I issue a command to create a new tab a new tab is created but there is no prompt. When switching between tabs you can see all the input that was missed. I don't know any way to do debugging with rio so I have no clue what is happening.

**Comment by pm-in-dss** [comment]
Same issue, additional information in the logs.

https://github.com/raphamorim/rio/assets/131114076/32371c82-fb1e-4f3d-bf62-032994054f1c

**Comment by raphamorim** [comment]
Hey @lukeh990 thank you for the issue and sorry for the inconvenience.

The 0.1.0 release came with more issues than I expected, I am still fixing some for the 0.1.1 meanwhile I would advise just keep with 0.0.x.

Also could you confirm if is happening for you on wayland? I saw the video that @pm-in-dss shared and it was a wayland debug. I am assuming that is the same?

**Comment by pm-in-dss** [comment]
I'm using wayland

**Comment by lukeh990** [comment]
@raphamorim Yes, I am using Wayland.

**Comment by raphamorim** [comment]
This issue was fixed in 0.1.3 🙏 closing it for now
related: #566
