### ISSUE TITLE
Application crash if dump the content of binary file

### ISSUE THREAD

**Issue by siygle** [raphamorim/rio#546]
Just found a strange situation and can always reproduce it with the following steps:

1. Dump any binary file's content to the Rio's screen.
2. Something the app will crash at this step. If not, keep going through the following steps.
3. Resize the Rio's window size.
4. The app will crash soon after the window resizes to a larger size.

I also take a screenshot for both crash cases:

Crash at step 2 (rust-hello is a Rust hello world example)

https://github.com/raphamorim/rio/assets/173408/b51e65f6-5271-4a6d-8656-4b5303ec886e

Crash at step 4 (rust-playground is a little more complex Rust code)

https://github.com/raphamorim/rio/assets/173408/bff7759d-65b5-4aec-bfa8-86875696894d

My environment:
Version: Rio 0.1.0
Platform: MacOS 14.5

Not quite sure if it's the Rio issue or others, so I am reporting the issue here first. Thanks.

**Comment by raphamorim** [comment]
Released the fix for it in v0.1.1, closing it for now but please let me know anything! 🙏 
https://github.com/raphamorim/rio/releases/tag/v0.1.1
