### ISSUE TITLE
Any interest in supporting stylistic-sets and/or character variants?

### ISSUE THREAD

**Issue by driverkt** [raphamorim/rio#548]
Very excited about ligature support shipping in 0.1.0!

I was curious if you have plans to support [stylistic-sets and/or character variants](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets). 

Thanks!

**Comment by raphamorim** [comment]
Hey @driverkt thanks for the issue!

Yes, I think the terminal already support that but isn't allowed to customize yet. Will try to look on it eventually 🙏

**Comment by raphamorim** [comment]
Implemented on main, closing it for now. It will be released on v0.1.3.

![image](https://github.com/user-attachments/assets/e56ffb9d-52ef-4eff-8bcf-e7bcf7d70773)

```
[fonts]
family = "fira code"
features = ["ss02", "ss03", "ss05", "ss19"]
```

<img width="412" alt="Screenshot 2024-07-27 at 12 10 44" src="https://github.com/user-attachments/assets/75351836-91de-41d7-a3fb-afbf887ce98b">

```
[fonts]
family = "fira code"
```

<img width="412" alt="Screenshot 2024-07-27 at 12 11 53" src="https://github.com/user-attachments/assets/0e5b27d6-0770-4091-bb5f-1d0c264e5258">

**Comment by AndydeCleyre** [comment]
I'd love to see `frac` supported as well.

**Comment by raphamorim** [comment]
@AndydeCleyre could you open an issue about it? 🙏
