### ISSUE TITLE
How does `rio` compare to other rust-based terminals?

### ISSUE THREAD

**Issue by StrictlyMonad** [raphamorim/rio#55]
Not trying to discourage you nor anyone else trying to commit to this project. By all means, this project is wonderful and keep up the great work! :blush: 

A curious thought, how does `rio` compare to `alacritty` and `wezterm`?

**Comment by raphamorim** [comment]
Hey there, I don't think there's anything to compare yet. Rio doesn't provide any feature and still unavailable for platforms than macOs. This repo is still in development and a lot of ideas that exists in the backlog haven't even started being implemented, that being said I believe still to early to compare with any of those terminals. Let's wait for a stable release and then run a comparison. Closing this issue for now.

**Comment by StrictlyMonad** [comment]
Awesome! Looking forward to the future of this project and hopefully when my Rust-lang info is mature enough I can also help contribute to the project. :)

**Comment by tqwewe** [comment]
Bump a year later. Just came across this, and my thoughts are, if it uses a lot of alacritty's code, then why is it doesn't, and how does the goals of this project differ from alacritty?

**Comment by raphamorim** [comment]
Fair question, I completely forgot about this issue tbh.

I plan to release a public roadmap next year in February but talked briefly about the future of Rio here -> https://www.youtube.com/watch?v=bxcYj78UNPU
