### ISSUE TITLE
[Linux] Color automation does not work

### ISSUE THREAD

**Issue by raelmax** [raphamorim/rio#552]
Hi, I just built Rio from the source code, and after configuring the navigation with a color-automation based on the path I could not make it work. There's something else that should be done to make it work?

My [navigation] section:

```
[navigation]
  mode = "BottomTab"
  clickable = false 
  use-current-path = false
  color-automation = [
    { path = "/full/path/to-my-dir/", color = "#14D64D" } 
  ]
```

**Comment by raphamorim** [comment]
I've talked with @raelmax and looks it's working again. closing this issue for now
