### ISSUE TITLE
[Windows]Abnormal font display and incomplete Navigation content display

### ISSUE THREAD

**Issue by luckzylp** [raphamorim/rio#554]
Hi，RIO is a great terminal program that found two problems on windows 11 in the new v0.1 or above compared to version v0.0.39，
![rio](https://github.com/raphamorim/rio/assets/40359079/79f7df93-ddef-4bca-b0bb-75b23525329e)

1. When the `Navigation` mode is set to `TopTab`, the tab content will not be displayed completely on windows11, but will be displayed normally on version v0.0.39 (as shown in the figure above).
2. On windows11, use `PowerShell 7 (x64)` as the default shell, after entering the command to start the automatic incomplete powershell, the RIO cursor is displayed abnormally, and it is displayed normally in version v0.0.39 (as shown in the figure above).

**System information**,
CPUs | 12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_graphite: disabled_off video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) |  
Memory (System) | 15.69GB (7.45GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by stephanlamoureux** [comment]
this happens to me on arch/hyprland as well among a bunch of other issues.

**Comment by luckzylp** [comment]
![image](https://github.com/user-attachments/assets/e97b5336-4f2e-42d4-9dcb-d61d73833fba)

On version V0.12, windows11, these two problems still exist.

**Comment by raphamorim** [comment]
Related to #543 
Pushed a fix to main
