### ISSUE TITLE
Computer slows down when running mpv over a mounted sshfs folder

### ISSUE THREAD

**Issue by ludblom** [raphamorim/rio#562]
I have a remote server mounted over sshfs and try to watch a movie with mpv. The computer then almost slows down to a halt, however running htop just show about 10% CPU% usage and that is not that much.

Just tell me what would be needed to pinpoint what the problem may be. Have tried with a handful och different terminal emulators and then the problem is not present, so I know it is for some reason because of rio.

**Comment by raphamorim** [comment]
Hey @ludblom thanks for the issue,

I will try to reproduce locally, are you using either 0.1.0 or 0.1.1 versions? Because the renderer isn't completely stable and slower than 0.0.x versions

**Comment by ludblom** [comment]
Thank you for looking into it @raphamorim! I run version 0.1.1.

Worth noting is that I experienced the same issue on my laptop after updating from 0.1.0 to 0.1.1 (I believe). So the issue is probably somewhere in the latest release.

**Comment by raphamorim** [comment]
Hey @ludblom sorry for the delay, could you try with 0.1.6?

**Comment by ludblom** [comment]
Sorry also for long delay @raphamorim! Yes I tried it out now with version 0.1.13 and it works wonders! When I have time I can try to go over the different versions and pinpoint which one solved the issue.

Thank you!

Will mark this issue as fixed.

**Comment by raphamorim** [comment]
Thank you for testing it 🙏 
Glad it is working now
