### ISSUE TITLE
Configuration for last window close behaviour

### ISSUE THREAD

**Issue by mnot** [raphamorim/rio#565]
Roi will switch away from the app the last window is closed. This means that if I intend to close the last window and then quit the app, I end up quitting a *different* app, because Rio has switched away.

I have pretty severe muscle memory around this pattern, so a preference to configure this behaviour would be appreciated.

**Comment by raphamorim** [comment]
Hey @mnot thanks for the issue,

Currently, Rio have this configuration https://raphamorim.io/rio/docs/next/configuration-file#confirm-before-quitting but I assume you are talking about quit the last window and keep Rio running in background either way, right?

Other question I have: are you using MacOS?

**Comment by mnot** [comment]
Yep - I am on MacOS (sorry).

I think this is a slightly different issue. If Rio is open with one window, and I press Apple-W, it does two things right now:

1. Closes the window
2. Shifts focus to another app

(1) is intuitive behaviour on MacOS, but (2) is not -- if the next keypress is Apple-Q, it will quit that other app, rather than Rio.

**Comment by raphamorim** [comment]
This has been fixed from 0.1.13, sorry for late update.

Closing this issue, please let me know anything

**Comment by mnot** [comment]
Thanks!
