### ISSUE TITLE
No input after first run

### ISSUE THREAD

**Issue by rdbo** [raphamorim/rio#566]
OS: Alpine Linux
Rio Version: 0.1.1
WM: river 0.3 (Wayland)

After the first run of `rio`, I could not type or do any input anymore in the terminal
I noticed that  if I delete `.config/rio`, it starts working again

![image](https://github.com/user-attachments/assets/07a4adaf-b953-4295-9b0f-536dbc7f579a)

This is how it looks after the first run, I can't seem to be able to do anything

**Comment by zh4ngx** [comment]
Good find. I'm on NixOS and it looks like I needed to unset the config, start rio and go through the "press enter" screen. This happened after upgrading from 0.0.39 -> 1.0. @raphamorim is config being handled differently in this version?

**Comment by raphamorim** [comment]
Hey there! Thanks for the issue!

Wayland isn't working properly with 0.1.x versions yet 😢 I am working on a fix for it

**Comment by zh4ngx** [comment]
> Hey there! Thanks for the issue!
> 
> Wayland isn't working properly with 0.1.x versions yet 😢 I am working on a fix for it

Noobie `home-manager` question here if you happen to know the answer -> what's the cleanest way to override the version? Do I need to pass in a different `nixpkgs` version tag at the flake level, or can I do something like set `programs.rio.package=something` in `home.nix`?

**Comment by raphamorim** [comment]
Pushed the fix for this issue on main, should be released on v0.1.3. Closing this issue for now but let me know anything.

> Noobie home-manager question here if you happen to know the answer -> what's the cleanest way > to override the version? Do I need to pass in a different nixpkgs version tag at the flake 
> level, or can I do something like set programs.rio.package=something in home.nix?
>

@zh4ngx no idea tbh, maybe you should ask in the rio discord (most of peeps use nix there 🙆‍♂️ )

**Comment by zh4ngx** [comment]
:pray: much appreciated!
