### ISSUE TITLE
[macos] Allow Rio install by Homebrew

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#57]
Would be great if could distribute Rio with brew using casks (as Alacritty does https://formulae.brew.sh/cask/alacritty). Might need to revisit the way Rio build binaries to put in release.

Some references:
- https://docs.brew.sh/Adding-Software-to-Homebrew#casks
- https://docs.brew.sh/Cask-Cookbook
- https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask
- https://github.com/Homebrew/homebrew-cask/blob/master/Casks/alacritty.rb

**Comment by raphamorim** [comment]
Ref https://github.com/Homebrew/homebrew-cask/pull/148888

**Comment by avelino** [comment]
@raphamorim it was not accepted, should we open the issue again?

**Comment by raphamorim** [comment]
The thing is that to be accepted Rio terminal needs to be notarized, which isn't the case today. Not planning to notarize the binary any time soon tbh.

**Comment by raphamorim** [comment]
PR made with notarization: https://github.com/Homebrew/homebrew-cask/pull/149824
