### ISSUE TITLE
Regression: slower rendering and hangs

### ISSUE THREAD

**Issue by TitanNano** [raphamorim/rio#578]
While testing the latest main today, I noticed that the application was rending much slower than the latest stable build of v0.1.3. When scrolling in `helix` the terminal even hangs, and I get a beach ball on macOS for a few seconds. 

Stable release:
<video src="https://github.com/user-attachments/assets/b0f3c636-f4d8-4b80-8a3d-fc42370ad864"></video>

Latest Main: 

<video src="https://github.com/user-attachments/assets/50eda22a-b932-4d3c-adb7-57ed51e2b075"></video>

Bisecting the recent changes since v0.1.3 identified this as the first bad commit: 9ec0b5f250e8596dc5e5d81ca42e5dcdd2b3dde4

**Comment by raphamorim** [comment]
Good catch! will take a look on it 🙏 
Thank you for testing and open the issue

**Comment by raphamorim** [comment]
@TitanNano can you test on main if fixed?

**Comment by TitanNano** [comment]
@raphamorim yes behaves like 0.1.3 again. 👍

**Comment by raphamorim** [comment]
Great! Thanks for testing!
