### ISSUE TITLE
[Bug] cell disappearance

### ISSUE THREAD

**Issue by MrPandir** [raphamorim/rio#579]
Some characters in `btop` were not rendered and caused TUI to be offset. At the end on the right side, it caused offset by 2 columns of cells. In the middle, it caused offset of the `User` column.
<img width="1401" src="https://github.com/user-attachments/assets/2d96bba0-4d5e-4d04-ae85-a3eacaf9d08d">
Here's what it should look like using Alacrity as an example:
<img width="1002" src="https://github.com/user-attachments/assets/4eb36730-83e4-491d-8b12-282538c007e5">
Also some Russian letters cause the last cells in the row to disappear. Probably the same thing happens with the symbols in `btop`. This is [neovim](https://neovim.io) with [kickstart](https://github.com/nvim-lua/kickstart.nvim/).
<img width="412" src="https://github.com/user-attachments/assets/80b0e422-e7ff-494e-ab48-d8fed4726ad4">
Letters for testing:
```
ьeи
ьtь
```

This is version: `0.1.4`. This behavior was introduced in version `0.1.0` and was not fully fixed, described in #534.

**Comment by raphamorim** [comment]
Hey @MrPandir thanks for the issue,

I cannot reproduce it with 0.1.3:

<img width="876" alt="Screenshot 2024-08-06 at 19 27 40" src="https://github.com/user-attachments/assets/39dafa97-6d00-478c-983d-e02cd3867c25">

But 0.1.4 yes,

<img width="929" alt="Screenshot 2024-08-06 at 19 25 36" src="https://github.com/user-attachments/assets/e17b5b5c-4dcc-4c12-85bb-d3e2c298a1fc">

Could you confirm about v0.1.3?

**Comment by raphamorim** [comment]
actually nvm, 0.1.3 is better but still weird compared to what should be. Will take a look on it.

`spf` though looks ok

**Comment by MrPandir** [comment]
@raphamorim on your screenshot with version `0.1.3` it is also reproducible:
<img width="876" src="https://github.com/user-attachments/assets/643a15cb-45d5-44fb-904e-aa1fdcd2d6ec">
This is what it should look like:
<img width="912" src="https://github.com/user-attachments/assets/6ca2c331-ead3-4a49-83d0-909765464011">

**Comment by raphamorim** [comment]
I think pushed a proper fix for it, could you test latest main?

<img width="912" alt="Screenshot 2024-08-07 at 23 11 54" src="https://github.com/user-attachments/assets/6df60822-92cd-4394-97ee-2c8303f578f6">

**Comment by MrPandir** [comment]
Yes, I confirm it has been fixed.
