### ISSUE TITLE
Weird rendering behaviour on setting `padding-x` in config

### ISSUE THREAD

**Issue by diwasrimal** [raphamorim/rio#590]
There's a weird rendering problem after setting `padding-x` value in settings

## System Info:

```
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64
```

## Steps to reproduce

1. Install rio and open
2. Open settings (command + ,)
3. Uncomment line where `padding-x` is set

## Video

http://0x0.st/XWnI.mov

**Comment by raphamorim** [comment]
Thanks for the issue and detailed video! Will take a look 👍

**Comment by raphamorim** [comment]
Hey @diwasrimal, pushed the fix for it in main, should be release in v0.1.7!
