### ISSUE TITLE
[kitty keyboard protocol] Shifted key codes are reported in wrong order

### ISSUE THREAD

**Issue by krobelus** [raphamorim/rio#596]
`ctrl-shift-q` sends ` \e\[81:113\;6u` where it should be ` \e\[113:81\;6u according to https://sw.kovidgoyal.net/kitty/keyboard-protocol/#key-codes

Originally reported as https://github.com/fish-shell/fish-shell/issues/10663#issuecomment-2294856800

**Comment by raphamorim** [comment]
Hey @krobelus thanks for the issue and sorry for delay to reply, will mark to take a look!

**Comment by raphamorim** [comment]
@krobelus made some changes, could you check if it works with latest main?

**Comment by krobelus** [comment]
seems to work, thanks.
BTW to be able to build, I deleted `rust-toolchain.toml`
Before that, `cargo b` failed with `error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.80.1-x86_64-unknown-linux-gnu' toolchain`
I'm using
```
$ cargo --version
cargo 1.80.1 (376290515 2024-07-16)
$ rustup component list| grep cargo
cargo-x86_64-unknown-linux-gnu (installed)
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
1.67.0-x86_64-unknown-linux-gnu
1.74.0-x86_64-unknown-linux-gnu
1.80.1-x86_64-unknown-linux-gnu (override)
1.70-x86_64-unknown-linux-gnu
1.75-x86_64-unknown-linux-gnu
```

**Comment by raphamorim** [comment]
Thank you for testing it!

> BTW to be able to build, I deleted rust-toolchain.toml
Before that, cargo b failed with error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.80.1-x86_64-unknown-linux-gnu' toolchain
I'm using

Weird, will also take it in my notes.

Thanks again!
