### ISSUE TITLE
Offset horizontal text selection when selecting with mouse

### ISSUE THREAD

**Issue by rdbo** [raphamorim/rio#598]
rio version: 0.1.7

Basically, whenever I select with the mouse, the selection is horizontally offset by a few columns
![image](https://github.com/user-attachments/assets/3e1bb08a-fa05-487c-99d8-b2bb3bd0d998)

I noticed that if I start the selection at X = 0, it correctly selects the first column, but as I got to the right, the offset increases a lot and I can select the end of the current line without being near it

**Comment by tukanoidd** [comment]
Got 0.1.7 working (NixOS, nixpkgs version was breaking with zellij (or nushell), not rendering anything and not reacting to key presses, flake used to not build, but did this time), same issue

**Comment by raphamorim** [comment]
@rdbo could you check if is still reproduceable on main?

**Comment by rdbo** [comment]
Fixed in `0.1.11` 💯 

![image](https://github.com/user-attachments/assets/34f368d6-2c9d-4244-b7da-673d71304e78)
