### ISSUE TITLE
hyperlink in url

### ISSUE THREAD

**Issue by avelino** [raphamorim/rio#60]
make the links (http:// and https://) clickable

**example:**
<img width="890" alt="Screenshot 2023-05-27 at 15 11 04" src="https://github.com/raphamorim/rio/assets/31996/38168e69-dcbb-47c6-9b77-b3e50d6a2655">

**Comment by OlshaMB** [comment]
@raphamorim In which version this would be implemented? Does this require some work on sugarloaf? How to implement this in sugarloaf?

**Comment by raphamorim** [comment]
Haven't implemented yet @OlshaMB, the missing piece work that needs to be done is whenever the mouse is over the line, needs to run the regex to check if contains a link and then update the sugar to add underline (is similar of how alacritty works in the source code)

**Comment by OlshaMB** [comment]
Ok, when I have time I will try and implement it

**Comment by hustcer** [comment]
Waiting for this feature

**Comment by raphamorim** [comment]
@OlshaMB alacritty runs the link preview for each draw (to inspire https://github.com/alacritty/alacritty/blob/7ceb638ff80eca99ac63df5fd8cbb2f703d4637a/alacritty/src/display/mod.rs#L813-L840), rio will not do this way since the renderer is not trigger per time interval (unless you use blinking cursor) but for key events and tty updates.

In rio should work like

1. mouse moved, get the current line and run the regex on it (this needs to be iterated in the PR or after the PR, because the link data is saved through lines/cell)
2. add the underline for cells that have the links enabled.

**Comment by raphamorim** [comment]
@OlshaMB did you start? otherwise will pick this issue after the #186 implementation

**Comment by raphamorim** [comment]
fyi started to implement it ![link](https://github.com/raphamorim/rio/assets/3630346/6f2d7e2f-f494-4c8e-9958-41e6083a6ab3)

**Comment by OlshaMB** [comment]
@raphamorim Sorry didn't have time, so no, did you start to implement it on main?
I think I will try to implement it this weekend

**Comment by raphamorim** [comment]
I wrote in a branch but haven't finished yet. What works so far is recognize the link, save to cells and update style to underline.

**Comment by raphamorim** [comment]
Implemented in main for MacOS (holding command and hovering the link allows the click), Linux/BSD does work now with `xdg-open` with super key but will be changed `alt` (as windows)

Documentation will be update once all platforms have support (will be wrapped up before next version 0.0.26 release)

**Comment by raphamorim** [comment]
Implemented for Linux, Windows, BSD and MacOS. Coming for upcoming version

![demo-hyperlink-linux](https://github.com/raphamorim/rio/assets/3630346/5edd373e-9901-43b0-915e-a0e772121ece)
![demo-hyperlink-macos](https://github.com/raphamorim/rio/assets/3630346/8dbb08eb-ff12-4895-9eb5-68deaf35da5e)
![demo-hyperlink-windows](https://github.com/raphamorim/rio/assets/3630346/67fb40a9-b806-4942-a008-016c8654518b)

**Comment by tauil** [comment]
Great work! One small remark/question: I noticed that the link behavior with the underline only triggers if I move the mouse, so if I just leave the mouse over the link and click the Cmd button, the link doesn't activate, only after moving the mouse. Is it expected to be like that? I know it's just nitpicking but still worth checking! 😄 

https://github.com/raphamorim/rio/assets/14328/8937e652-8e85-4974-b94a-64cdda09ca9f

**Comment by raphamorim** [comment]
Yes, this is known. The way rio implemented the links is to avoid running regex without necessity so you actually need to interact with link to activate. It should be better with time (like press command and hit the link directly, but the handler now is in the mouse moving listener)

**Comment by tauil** [comment]
To be honest I wouldn't mind having the handler in the Cmd key instead if that's possible.

**Comment by raphamorim** [comment]
Will do, but next version (needs to be tested carefully don't affect performance for other cases)

**Comment by lypanov** [comment]
This works well for me here on my (niche) setup - the project as a whole surprised me to be honest as wezterm was a train wreck qua performance on my platform (Android). However it seems that while you have OSC 8 marked as IMPLEMENTED you haven't yet connected the two parts? Is this a safe assumption? Is there any chance there is a plan to do so? I'm currently running xfce4-terminal for the sixels and tilix for the tabbing capabilities but would like to unify (bonus, xfce4-terminal took me hours to get building vs 10 minutes or so for your project, tilix also has too many deps alas)

**Comment by raphamorim** [comment]
Hey @lypanov thanks for the message.

Rio does implements OSC 8 https://github.com/raphamorim/rio/blob/main/rio/src/performer/handler.rs#L604-L622 , although it will still required to hold the key to enable the click.
If OSC8 isn't working for you with the hyperlink in URL, then it's a bug I can take a look

**Comment by raphamorim** [comment]
Actually never mind, found a bug with OSC 8 implementation that was preventing to show for majority of cases. Added the fix in [3078e63](https://github.com/raphamorim/rio/commit/3078e6389201dfe87a722b0df03b1c5417826fb8)

<img width="894" alt="Screenshot 2023-11-11 at 13 01 18" src="https://github.com/raphamorim/rio/assets/3630346/9b1c3252-6819-4bff-8827-5e71dc8701e1">

**Comment by brian6932** [comment]
>are you using shift+hover?

I wasn't in the video, but even when I do hold <kbd>SHIFT</kbd>, it still doesn't work.

>could you open an issue?

Sure.
