### ISSUE TITLE
Close all tabs except for the curent one 

### ISSUE THREAD

**Issue by xMonody** [raphamorim/rio#608]
Close all tabs except for the curent one

**Comment by orhun** [comment]
Happy to add this feature if @raphamorim finds it useful :)

**Comment by raphamorim** [comment]
I think this feature makes sense but I don’t think it can be via UI at least now. Either will be a Action that you can configure through key binding like `CloseAllBesidesCurrent` or a cli hook. However the second option will require build the cli support to trigger on Rio application. So maybe start with key binding now?

**Comment by xMonody** [comment]
Thank you very much for your project. The UI is not necessary; implementing an action and binding it to a shortcut key would be perfect

**Comment by orhun** [comment]
Alright, I will be working on it then 🐻
