### ISSUE TITLE
Support searching in Vim mode

### ISSUE THREAD

**Issue by orhun** [raphamorim/rio#611]
It would be nice to be able use search in Vim mode via pressing `/`

Switching between Vim mode and search mode is not super convenient right now.

Any plans to support such feature?

**Comment by raphamorim** [comment]
Yes!! It's definitely on the roadmap :D

**Comment by orhun** [comment]
aight I can also work on it I think :D

**Comment by raphamorim** [comment]
Merged into main, closing this issue
