### ISSUE TITLE
Vim or other mode is not full

### ISSUE THREAD

**Issue by richerfu** [raphamorim/rio#615]
Version: 0.1.9
OS: Apple  M2 Pro 14.4.1

<img width="1063" alt="image" src="https://github.com/user-attachments/assets/349828b6-2ebc-4362-acbe-1eb5e4889d2d">

`git diff` or `vim` always have empty block

**Comment by raphamorim** [comment]
@richerfu thanks for the issue, do you have line-height configured?

**Comment by richerfu** [comment]
Yes, i remove it and it's fine. Is this a known issue?

**Comment by raphamorim** [comment]
Yea, it started to happen on 0.1.x versions, I plan to make a proper fix for line-height soon (probably next version) but now it's just breaking whenever is used.

Will close this issue for now, let me know anything! 🙏

**Comment by nobeh** [comment]
@raphamorim I see a similar empty box even without `line-height` configuration -- 

<img width="1176" alt="image" src="https://github.com/user-attachments/assets/660505c3-6cbb-4cbd-aad7-b10eaf0b9a0f">
