### ISSUE TITLE
[Feature Request] macOS option to disable “hand” mouse cursor

### ISSUE THREAD

**Issue by andrewcrook** [raphamorim/rio#624]
Would it be possible to get rid of the “hand" mouse curser over the windows bar and when dragging?
Just use the default macOS one?

![Screenshot 2024-08-29 at 16 57 21](https://github.com/user-attachments/assets/13fa378d-4952-417c-807e-2ee52fa05bd5)

**Comment by raphamorim** [comment]
Hey @andrewcrook thanks for the issue,

I actually thinking in get rid of it on macos

**Comment by andrewcrook** [comment]
> I actually thinking in get rid of it on macOS

tbh, I think that’s probably a good idea. Thanks

**Comment by raphamorim** [comment]
removed on 78097615
closing this issue, thank you 🙏
