### ISSUE TITLE
iTerm2 Image protocol

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#634]

**Comment by AnonymouX47** [comment]
Just wanna note a couple things. See:

- https://github.com/jerch/xterm-addon-image/issues/57#issuecomment-1979734859 concerning cursor placement, and
- https://github.com/jerch/xterm-addon-image/issues/58 concerning feature reporting / support detection.

These may have even been taken care of, pointing them out just in case.

Thanks :smiley:.
