### ISSUE TITLE
sixel: Text doesn't overwrite sixels

### ISSUE THREAD

**Issue by AnonymouX47** [raphamorim/rio#636]
I just tested it out the sixel support...

First, kudos for the work. :+1:

Just one observation so far... **text doesn't overwrite sixels**, which I believe is opposite to the standard behaviour, as in:

![Screenshot_2024-09-02_08-35-06](https://github.com/user-attachments/assets/36d46da4-5afd-4ca7-9647-783616ed1b53)

This is unlike several other terminal emulators. Also, this means the only way to clear sixels off the screen is by actually clearing the whole screen which isn't very practical. This might not seem like a problem to users who only "cat out" images on a scrolling screen but this behaviour makes the feature difficult/impossible to use in fullscreen applications (i.e. which don't scroll the screen). Below are shots from Xterm and WezTerm:

| Xterm | Wezterm |
|:---:|:---:|
| ![Screenshot_2024-09-02_08-35-40](https://github.com/user-attachments/assets/92b4f99d-1b07-4d31-a531-33080ecbc38d) | ![Screenshot_2024-09-02_08-35-45](https://github.com/user-attachments/assets/f216f237-b50a-4ba5-8db8-5b199333b299) |

For what it's worth, I understand the work isn't finalized yet but I thought it was still worth noting.

Finally, I see iTerm2 IIP support is also underway. I'd like to note that the behaviour should be the same.

Thanks. :smiley:

_Originally posted by @AnonymouX47 in https://github.com/raphamorim/rio/issues/38#issuecomment-2325242762_

**Comment by raphamorim** [comment]
Thank you for the issue! Will take a look on it

**Comment by raphamorim** [comment]
Pushed a fix for text overwrite in main, when you have time please test it 🙏 
<img width="912" alt="Screenshot 2024-09-05 at 18 47 40" src="https://github.com/user-attachments/assets/b7372bf8-23c2-4879-990c-5499e95e5413">

**Comment by AnonymouX47** [comment]
Tested and it works great! :tada:

I also tested EL (`CSI K`) and ECH (`CSI X`) and they erased sixels, as they should.

Thank you very much and well done! :smiley:

**Comment by raphamorim** [comment]
Thank you for testing it @AnonymouX47 !
