### ISSUE TITLE
ctlseqs: Implement parameters `14` and `16` of `CSI t`

### ISSUE THREAD

**Issue by AnonymouX47** [raphamorim/rio#637]
On a different note, I noticed parameters `14` and `16` of `CSI t` aren't implemented [yet]. Though, according to the docs, they aren't rejected. Some applications require at least one of these two (usually `14`) to use graphics protocols.

For what it's worth, I know the `TIOCGWINSZ` ioctl is implemented already (and that's personally what I always prefer) but it isn't an option in every environment e.g on Windows.

_Originally posted by @AnonymouX47 in https://github.com/raphamorim/rio/issues/38#issuecomment-2325261041_

**Comment by raphamorim** [comment]
Hey @AnonymouX47 thanks for the issue,
did you test the CSI t14 or was based on docs? Because I thought I implemented it https://github.com/raphamorim/rio/blob/8b20a0ed438aa37a05649d5ee88abaa15acc4aaf/rio-backend/src/performer/handler.rs#L1013

**Comment by raphamorim** [comment]
(i need to update the docs though)

**Comment by AnonymouX47** [comment]
I tested it multiple times on both a stable build (0.1.8) and `main` @ 8b20a0ed4.

**Comment by raphamorim** [comment]
okej, will take a look then.

**Comment by raphamorim** [comment]
oops you are very right, i couldn't get with `echo -ne "\\033[14t\\033\\ "`

**Comment by raphamorim** [comment]
<img width="576" alt="Screenshot 2024-09-03 at 14 57 21" src="https://github.com/user-attachments/assets/9a9646e0-1e39-4ca0-ba75-c3c94cf8b7f6">

**Comment by raphamorim** [comment]
should be ready now in main branch

**Comment by AnonymouX47** [comment]
Noted.

I'll test 'em out as soon as possible and get back to you.

By the way, I noticed `14` was ommited in d7c0fc9bef6541a0f2dbaff0419186e2b6ea9b18, or what that intentional?

Thanks.

**Comment by raphamorim** [comment]
> By the way, I noticed 14 was omitted in https://github.com/raphamorim/rio/commit/d7c0fc9bef6541a0f2dbaff0419186e2b6ea9b18, or was that intentional?

My bad, added info regarding the wrong one.

I also added 16 as well 🙏

**Comment by AnonymouX47** [comment]
Well done. :+1:

Sorry for the nitpickiness but I couldn't but notice the definition of "CSI 14 t" as "Window Size" in b99b2bf03fed0db6f66b0cf98b2f3a1da7d4be48. I believe it should be "Text Area Size", as you've used within the code. I also believe you've correctly implemented it (yet to test but I've read through the code).

Earlier, I wanted to note that you should beware of the difference between `14 t` and `14 ; 2 t` but dismissed it. Anyways, I don't think the later is necessary to implement.

Thanks. :smiley:

**Comment by raphamorim** [comment]
> Sorry for the nitpickiness but I couldn't but notice the definition of "CSI 14 t" as "Window Size" in https://github.com/raphamorim/rio/commit/b99b2bf03fed0db6f66b0cf98b2f3a1da7d4be48. I believe it should be "Text Area Size", as you've used within the code. I also believe you've correctly implemented it (yet to test but I've read through the code).

I agree, I actually wanted to drop the window size struct and use the sugarloaf layout struct later since doesn't make sense be "turning" already existent data to just do pty write.

> Earlier, I wanted to note that you should beware of the difference between 14 t and 14 ; 2 t

I would love to learn! what's the difference between both?

**Comment by raphamorim** [comment]
I will close for now but i appreciate your time testing!

**Comment by AnonymouX47** [comment]
You're welcome.

> > Earlier, I wanted to note that you should beware of the difference between 14 t and 14 ; 2 t
> 
> I would love to learn! what's the difference between both?

Well... quoting from Xterm [ctlseqs](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_) page:

> ```
> CSI Ps ; Ps ; Ps t
>           Window manipulation (XTWINOPS), dtterm, extended by xterm.
>
>           ...
>
>             Ps = 1 4  ⇒  Report xterm text area size in pixels.
>           Result is CSI  4 ;  height ;  width t
>             Ps = 1 4 ;  2  ⇒  Report xterm window size in pixels.
>           Normally xterm's window is larger than its text area, since it
>           includes the frame (or decoration) applied by the window
>           manager, as well as the area used by a scroll-bar.
>           Result is CSI  4 ;  height ;  width t
> ```

Hence, I believe the "text area" should be just the area of the window used to display the actual tty I/O or terminal screen content i.e. excluding window decorations, scroll bar, tab bar, margins, paddings, etc.

**Comment by raphamorim** [comment]
That's good to know, yea I applied the code considering only the text area but I was wondering about the window height/width as well

**Comment by AnonymouX47** [comment]
Tested and all seems to work fine.

Thanks. :+1:
