### ISSUE TITLE
ctlseqs,sixel: Report sixel feature in Primary Device Attributes

### ISSUE THREAD

**Issue by AnonymouX47** [raphamorim/rio#638]
The current response to `CSI c` doesn't indicate the sixel feature.

Various applications use this as a means to detect support for sixel graphics, as this is the standard method.

It should include a parameter `4`. Also, I believe the terminal ID parameter (the first one) should change.

Thanks.

**Comment by raphamorim** [comment]
Could you confirm if it's correct now?

<img width="912" alt="Screenshot 2024-09-02 at 23 11 36" src="https://github.com/user-attachments/assets/b0d66169-9340-4f76-adf7-716973a89a74">

**Comment by AnonymouX47** [comment]
Yes, resolved. Thanks.
