### ISSUE TITLE
Flash of white during startup on Windows (may possibly affect other platforms)

### ISSUE THREAD

**Issue by fgimian** [raphamorim/rio#640]
Hey there, really great job on Rio.

On Windows, there's a rather unpleasant initial flash of white and black while the app is starting up. It may be worth keeping the window hidden until the first draw is completed.

Please see a recording below:

![Rio Startup](https://github.com/user-attachments/assets/06897c14-e7dd-40ec-ab9a-a06ce9ea50c5)

Cheers
Fotis

**Comment by raphamorim** [comment]
Thank you for the issue!

Yes, I could reproduce it today. Will mark to take a look!

**Comment by raphamorim** [comment]
Fixed on main, it was similar issue to https://github.com/vizia/vizia/pull/386
