### ISSUE TITLE
If editor is not found, the app panics

### ISSUE THREAD

**Issue by fgimian** [raphamorim/rio#641]
Hey again, since the application defaults to `vi` as its editor, I noticed this problem on Windows before updating my configuration.

![image](https://github.com/user-attachments/assets/574a20dc-63be-4cd9-aeb9-1948938cf987)

Unfortunately, this also makes the app crash.

Cheers
Fotis

**Comment by raphamorim** [comment]
Thank you for the issue @fgimian 

Very interesting because on macos and linux the app just close the window. Will take a look on it 👍

**Comment by fgimian** [comment]
> Thank you for the issue @fgimian
> 
> Very interesting because on macos and linux the app just close the window. Will take a look on it 👍

Thanks heaps 😄

**Comment by raphamorim** [comment]
I believe should be fixed now!

![Screenshot 2024-09-04 030926](https://github.com/user-attachments/assets/8d84de6e-d164-481f-8e6e-d3cdc952656f)

It will be included on next release, will close this issue for now but lemme know anything and I can reopen.
