### ISSUE TITLE
Improve logging and store logs in a file

### ISSUE THREAD

**Issue by orhun** [raphamorim/rio#645]
### Discussed in https://github.com/raphamorim/rio/discussions/626

<div type='discussions-op-text'>

<sup>Originally posted by **andrewcrook** August 31, 2024</sup>
I have tried to setup logging 

```
 [developer]
#log-level= “ERROR"
 log-level = “DEBUG"
```

However, I have looked in the common folders and console app for the log file and I cannot find its location.
Any ideas?</div>

I will be working on it so feel free to assign :)

**Comment by raphamorim** [comment]
Thanks for the heads up @orhun ! Just please in mind that ideally the logs to file should be optional (settled up via config)

Maybe it can also receive the path where the logs will be store but it can be a follow up change.
