### ISSUE TITLE
rio 0.1.12 fails to build on cross targets

### ISSUE THREAD

**Issue by tranzystorekk** [raphamorim/rio#656]
Found when building rio for Void Linux https://github.com/void-linux/void-packages/actions/runs/10758124870/job/29833009268?pr=52138

```
error[E0308]: mismatched types
   --> rio-window/src/platform_impl/linux/x11/ime/context.rs:175:13
    |
175 | /             mem::transmute::<
176 | |                 usize,
177 | |                 unsafe extern "C" fn(*mut x11_dl::xlib::_XIM, *mut i8, *mut i8),
178 | |             >(preedit_start_callback as usize)
    | |______________________________________________^ expected `u8`, found `i8`
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, *mut u8, *mut u8)`
               found fn pointer `unsafe extern "C" fn(_, *mut i8, *mut i8)`
```

**Comment by orhun** [comment]
#657 potentially fixes this.

**Comment by raphamorim** [comment]
@orhun left some comments on your PR, the problem with that fix is that actually would break for other builds with different targets. @tranzystorekk could you test again with latest main? https://github.com/raphamorim/rio/commit/ff3afb7f28ee427590547cc260a7d78c5ae59140

**Comment by tranzystorekk** [comment]
Tested with these changes and rio builds fine! 😁

**Comment by raphamorim** [comment]
Thank you! closing this issue 👌
