### ISSUE TITLE
Lag when using blinking = true

### ISSUE THREAD

**Issue by AntonyZ89** [raphamorim/rio#663]
After updating to version 0.1.13 and adjusting the new [cursor] configuration, I've noticed that the terminal becomes slow when using blinking=true

https://github.com/user-attachments/assets/37beece9-ee9f-4480-80ea-b64a1b79cf69

**Comment by raphamorim** [comment]
@AntonyZ89 should be fixed on main.

Also added a new property now that allows to configure cursor blinking interval:

```toml
# [cursor]
# shape = 'block'
# blinking = false
# blinking-interval = 800 
```
