### ISSUE TITLE
The character on cursor is hidden by it.

### ISSUE THREAD

**Issue by niuez** [raphamorim/rio#67]
Hi, I want to use rio with beam cursor, but the cursor hide the character. Other kind cursors also do.
Because the cursor is rendered to replace the character to cursor character.
It should be like this.

<img width="399" alt="image" src="https://github.com/raphamorim/rio/assets/30189186/4d7cd733-2783-4e58-821b-745008fb4575">

<details>
<summary>my opinion</summary>
I think rendering the cursor by Sugarloaf's Rect is one of the solutions. 
The image above was created by this code. Cursors are considered to be associated with characters, so I defined new SugarStyle `on_cursor`.

https://github.com/niuez/rio/blob/0ea71b80d30af2038fa0a361b4d73b4d92be6b24/sugarloaf/src/sugarloaf.rs#L299-L307

But there are some problems.

- Sugarloaf is rendering engine. It should not be contain cursor shape information. The cursor shapes should be defined in rio.
- The color of cursor should be able to change by rio.
- How to render more complex cursors. For example, unfilled rectangle.
</details>

**Comment by raphamorim** [comment]
Yea, that's for bring this up. Unfortunately the way sugarloaf is built now, consider cursor as a sugar so it would replace a text block, it would work for Block cursors but not for other cases. For fix this issue I was thinking in few possibilities:

- add a new type called `SugarPileLayer` that would be used by `SugarPile` to contain multiple layers (that would be useful for rects that are rendered in background, so after the refactor will be 3 layers: rect, text, text[cursor or special]).
- add a new type called `SugarLayer` that would be used by `Sugar`. Kinda same approach as `SugarPileLayer` but for sugar blocks only.
- render it like we do with `pile` method (in the sugarloaf examples), would be an external method that we say we want a sugar in a specific position in the screen.

**Comment by raphamorim** [comment]
I kinda of like SugarLayer cause it simplify stuff (the way we consider Rects for example).

Maybe something like this:

```rust
pub struct SugarLayer {
    pub layers: Vec<char>
}

#[derive(Debug)]
pub struct Sugar {
    pub content: SugarLayer,
    pub foreground_color: [f32; 4],
    pub background_color: [f32; 4],
    pub style: Option<SugarStyle>,
}
```

**Comment by niuez** [comment]
Using `SugarLayer` becomes block and underline cursor OK, but Beam will be like this I think.
<img width="392" alt="image" src="https://github.com/raphamorim/rio/assets/30189186/7eb19512-d0fd-4dd2-89b5-47839c6991d0">

**Comment by raphamorim** [comment]
hmmm I think is due to the alignment configuration, we do centralize characters in the Sugar. Maybe we can add a property alignment that reflects in the OwnedText alignment: https://docs.rs/wgpu_glyph/latest/wgpu_glyph/enum.HorizontalAlign.html

**Comment by niuez** [comment]
How about thinking of the cursor as decoration on the glyph box of the character by Rect?
gray is beam, blue is underline.

![image](https://github.com/raphamorim/rio/assets/30189186/b20cee97-7ac2-434c-bd8d-770c9268b76c)

Here is example implementation.

https://github.com/niuez/rio/blob/fc0c9c5dc5b1d2acddb1496c95a9c629307de0d7/rio/src/screen/state.rs#L207-L226

**Comment by raphamorim** [comment]
Hmm, SugarDecoration would be a representation of Rect to a specific Sugar right? 
That's also a good idea.

One concern I have with that is when comes to create the underline style that doesn't exist yet, so cursor and underline style doesn't conflict, but underline doesn't necessarily need to use same solution.

**Comment by niuez** [comment]
> SugarDecoration would be a representation of Rect to a specific Sugar right?
Yes. Rendering cursor by Rect does not depend on fonts, and We can know position of cursor by rendering cursor and the character at the same time. It is also possible to think of decoration as a layer whose origin is the top-left position of the letter.

But as you say, it is not clear whether this method should be used in rendering underlines. It may be necessary to consider whether it should be a special parameter for the cursor or a generic one.

**Comment by raphamorim** [comment]
Have been thinking about it, I actually am sold to cursor being rendered by sugarloaf, because when you change fonts, you don't want the cursor dimensions to change or rely on that. I think underline can coexist with the "underline cursor" as well.

Let me know you want to add the implementation for that in the sugarloaf , would be great @niuez

**Comment by raphamorim** [comment]
Closing after #74 merge.
Thanks for the contribution! 🎖️
