### ISSUE TITLE
Undercurl does not work inside Tmux and Neovim

### ISSUE THREAD

**Issue by FahimAnayet** [raphamorim/rio#675]
Undercurl does work in bare terminal, however it doesn't work inside tmux and neovim.

Tmux config (I've tried commented lines too)
![Screen Shot 2024-09-19 at 10 41 50 AM](https://github.com/user-attachments/assets/f6fb8328-6ba3-4be4-8068-99106213667b)

Bare rio
![Screen Shot 2024-09-19 at 10 33 25 AM](https://github.com/user-attachments/assets/7a15294f-e4ff-4240-a1da-0cbc5029c5f3)

Tmux
![Screen Shot 2024-09-19 at 10 33 13 AM](https://github.com/user-attachments/assets/d9f7ef14-346c-4523-848a-55ad963ccdfe)

Tmux+Neovim (same in outside tmux+neovim)
![Screen Shot 2024-09-19 at 10 32 46 AM](https://github.com/user-attachments/assets/4b5f7777-9138-4fb2-a9d0-02eac6141098)

**Comment by raphamorim** [comment]
Thank you for the issue! I will try to reproduce it 👍

**Comment by FahimAnayet** [comment]
With these settings undercurl works perfectly now.  I'm closing the issue as it is complete 😄 

# tmux
```conf
set -g default-terminal xterm-256color
set-option -ga terminal-overrides ",xterm*:Tc"
```
# neovim
```lua
vim.cmd([[hi! DiagnosticUnderlineHint gui=undercurl, cterm=undercurl]])
vim.cmd([[hi! DiagnosticUnderlineInfo gui=undercurl, cterm=undercurl]])
vim.cmd([[hi! DiagnosticUnderlineError gui=undercurl, cterm=undercurl, guisp=red]])
vim.cmd([[hi! DiagnosticUnderlineWarn gui=undercurl, cterm=undercurl, guisp=orange]])
```

**Comment by raphamorim** [comment]
Wow great finding @FahimAnayet 
Thank you for investigating and sharing
