### ISSUE TITLE
Can't close window by command+w when navigation mode is not NativeTab

### ISSUE THREAD

**Issue by shmn7iii** [raphamorim/rio#683]
I want to close the last tab(= window) with command+w as I do with other tabs. When the navigation mode is NativeTab, we can do this.
I've confirmed locally that this can be done by removing [this if-statement](https://github.com/raphamorim/rio/blob/main/frontends/rioterm/src/context.rs#L605). If so, I want to contribute! (though, I guess I'll just be deleting a line. 😂)

But, actually, I'm not familiar with macOS and Rust development. Let me know if there's any reason why it's limited to the NativeTab mode.

Thank you.

**Comment by raphamorim** [comment]
Ah very good you opened this issue! I am actually working on this for next version, it should close for all navigations and I've added a question if you want to really close rio.

<img width="717" alt="Screenshot 2024-09-22 at 17 53 04" src="https://github.com/user-attachments/assets/e5aff7c4-9d02-463c-b4d5-94fe68554ec6">

**Comment by shmn7iii** [comment]
@raphamorim 
Wow! Looks so good!
You mean you've already been working on implementing this (already deleted the if-statement), right? Then I'll wait for the next version, and looking forward to it!

**Comment by raphamorim** [comment]
>  You mean you've already been working on implementing this (already deleted the if-statement), right? Then I'll wait for the next version, and looking forward to it!

Yes!! Should be same behaviour as native tabs 🙏

**Comment by shmn7iii** [comment]
Got it! Thank you so much :)

**Comment by raphamorim** [comment]
@shmn7iii implemented on main, will come to next version

![demo-close](https://github.com/user-attachments/assets/1010b62e-6874-4707-aee9-1c3064246817)
