### ISSUE TITLE
Rio doesn't handle double-width characters (e.g. CJK characters)

### ISSUE THREAD

**Issue by marchbox** [raphamorim/rio#697]
When the cursor is on a double-width character, the character shrinks to single width (see screencast)

https://github.com/user-attachments/assets/2dcd3db9-eba2-4eaf-b9e2-73dac068097d

I found a similar issue that used to be in Alacritty here: https://github.com/alacritty/alacritty/issues/265

**Comment by raphamorim** [comment]
Is this regarding the cursor only? I am not sure if I understood correctly (I am unable to watch the video you sent) 

<img width="470" alt="Screenshot 2024-10-07 at 14 10 32" src="https://github.com/user-attachments/assets/4aaec3a9-dea4-4a23-8f3e-0cc41e548115">

In my case it does indeed 10 cells

<img width="217" alt="Screenshot 2024-10-07 at 14 09 32" src="https://github.com/user-attachments/assets/e9362e4d-8d93-4f9a-ab41-046d1f1f3011">

**Comment by raphamorim** [comment]
Ah ok, I was able to see the video now. weird.. which version are you using and is it running on MacOS?

**Comment by marchbox** [comment]
@raphamorim Yes it's on macOS. The version is 0.1.10. I just upgraded to 0.1.17, the issue is gone :D
