### ISSUE TITLE
Doc for `env-vars` config

### ISSUE THREAD

**Issue by destructobeam** [raphamorim/rio#698]
Hi there,

I couldn't seem to get `env-vars` working. Could we please get an example in the docs of the correct format. Or if you can put one here I can submit a pull request for the docs?

Thanks!

**Comment by raphamorim** [comment]
Hey @destructobeam thanks for the issue!

What is your OS?

**Comment by destructobeam** [comment]
Is the format for `env-vars` config OS specific?

I’m just looking for an example to go in here: https://raphamorim.io/rio/docs/config/env-vars

I’m using macOS though.

**Comment by destructobeam** [comment]
Awesome! Thank you for that!
