### ISSUE TITLE
input window lagging behind the frame upon resizing

### ISSUE THREAD

**Issue by dariavaskovichedlund** [raphamorim/rio#70]
When resizing the window, one may observe that the inner input window is lagging behind the frame window a few ms. mostly noticeable when resizing from small to bigger size.

**Comment by raphamorim** [comment]
Fixed in 94fb71f8469818253106573b2ca737c2015e3951 

![demo](https://github.com/raphamorim/rio/assets/3630346/aea3a90b-4b3a-4648-bfdd-19f1e0f0480d)
