### ISSUE TITLE
Rio cannot use macos automation 

### ISSUE THREAD

**Issue by lbuczkow** [raphamorim/rio#701]
Please add com.apple.security.automation.apple-events entitlement to Rio.entitlements. This will allow Rio to interact with other apps via Apple Events on macOS. Without this permission apps started from Rio cannot get arguments, for example:

/Applications/p4merge.app/Contents/Resources/launchp4merge file1 file2

Under Rio file1 and file2 are not passed to p4merge (https://www.perforce.com/downloads/visual-merge-tool).

**Comment by raphamorim** [comment]
@lbuczkow thanks for the issue. Added on abae04b , please lemme know anything

**Comment by lbuczkow** [comment]
Now it works, thanks!
