### ISSUE TITLE
line-height property breaks screen layout

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#703]
Issue originally posted on Rio discord.

Microsoft Windows:

![image](https://github.com/user-attachments/assets/ffde1fe4-15c3-4f4a-926c-5694bd04f985)
![image](https://github.com/user-attachments/assets/157e8584-f99e-45cb-b654-f650dd00e419)

(I haven't reproduced it yet)

**Comment by SunP04** [comment]
Issue was in my computer, installed it through scoop.

**Comment by SunP04** [comment]
"Solution" `line-height` was not fully supported yet, so it missaligned the content (I think).

**Comment by moenodedev** [comment]
line-height also breaks screen layout on macOS.

**Comment by raphamorim** [comment]
closing this issue since is duplicated of #449
