### ISSUE TITLE
[BUG] Window doesn't receive mouse events on Windows 11

### ISSUE THREAD

**Issue by igorsaux** [raphamorim/rio#708]
The terminal's window does not receive any mouse events other than scrolling. So you can't resize the window, select text, etc. The only thing that works is clicking on the title bar to bring the window into focus.

It looks like the problem came from this commit: https://github.com/raphamorim/rio/commit/b4287fde7779206d43ffa685e49546920014bb11

From these lines, to be exact:
https://github.com/raphamorim/rio/blob/2231e255d82bbff8155594ba00f383070f292e7a/rio-window/src/platform_impl/windows/event_loop.rs#L2166-L2168

According to the [docs](https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-nchittest), this branch must return values other than `HTNOWHERE` to work properly. I don't know much about the Win32 API, so I can't say how to do this correctly, but deleting this branch fixes all the problems with the mouse.

OS: Windows 11 (23H2)
OS Build: 22631.4317

**Comment by raphamorim** [comment]
Thank you for the issue! I see, I will test it locally as well but would you like to send a PR reverting b4287fd ?

**Comment by raphamorim** [comment]
@igorsaux thank you for the PR, i don't know if you would like to keep contributing. I have been thinking about add Rio on winget https://github.com/raphamorim/rio/issues/520 . Not sure if this is something you would be interested in help with. (any case I am available on discord)

**Comment by igorsaux** [comment]
> @igorsaux thank you for the PR, i don't know if you would like to keep contributing. I have been thinking about add Rio on winget #520 . Not sure if this is something you would be interested in help with. (any case I am available on discord)

It would be nice, but I don't have much time and I'm using a patched version of the terminal (for rendering cool shaders). But I will try to report and fix problems on Windows from time to time.

**Comment by raphamorim** [comment]
>  I'm using a patched version of the terminal (for rendering cool shaders)

That's cool! I just took a look on it https://github.com/raphamorim/rio/commit/3af814365224a0c8611a5f96cd099e120f94b93b

This is something that I want to add on Rio, CRT shaders (https://emulation.gametechwiki.com/index.php/CRT_shaders). If you would like to work on it it's also welcomed 🙏

**Comment by raphamorim** [comment]
Added a new issue regarding it https://github.com/raphamorim/rio/issues/711
