### ISSUE TITLE
iosevka ss05 is rendered incorrectly

### ISSUE THREAD

**Issue by teidesu** [raphamorim/rio#718]
`]` is rendered as `F` and `k` as `I` for whatever reason

<img width="271" alt="image" src="https://github.com/user-attachments/assets/857cac29-c2e3-40a2-a36b-975718c76c7e">

font in question: https://s3.tei.su/iosevka-nerd.tgz,
but this also seems to happen on original non-nerd iosevka as well (https://github.com/be5invis/Iosevka/releases/download/v31.9.1/PkgTTF-IosevkaSS05-31.9.1.zip), for which even more glyphs are messed up:
<img width="441" alt="image" src="https://github.com/user-attachments/assets/e9c27732-32fc-48e9-8bd6-80b9f2ccf0e3">

macos 15.0 on m3 max
Darwin sumire 24.0.0 Darwin Kernel Version 24.0.0: Wed Aug  7 03:08:06 PDT 2024; root:xnu-11215.1.9~22/RELEASE_ARM64_T6031 arm64
Rio Version 0.1.15 (20230528.115631)

**Comment by raphamorim** [comment]
Hey @teidesu thanks for the issue, yes unfortunately it was an issue on 0.1.15 (font update would require close and reopen again) but should be fixed on main now 0.1.17.

closing this issue for now 🙏
