### ISSUE TITLE
make emoji representation configurable

### ISSUE THREAD

**Issue by dariavaskovichedlund** [raphamorim/rio#72]
currently, the emojis are being represented as outlined only. perhaps a configuration option would be a nice to have so that users can choose between having the emojis as outlined or as "filled in"/original look.

**Comment by AlexW00** [comment]
+1!!!

**Comment by raphamorim** [comment]
Now emojis are available and implemented in the main, but the renderer still have remaining work https://github.com/raphamorim/rio/issues/456

![image](https://github.com/raphamorim/rio/assets/3630346/6b1896d1-59a6-4c1f-b9a1-d28377c86b83)

For now I will close this issue (I still will track it on the project board later to test). Thanks!
