### ISSUE TITLE
No mouse events getting captured in windows 11

### ISSUE THREAD

**Issue by muzammil-iftikhar** [raphamorim/rio#726]
No mouse events are getting captured in windows 11.  I can't select any text. It doesn't bring the window to focus when I click anywhere in the window.
I am using the latest rio version 0.1.17.

**Comment by raphamorim** [comment]
Hey @muzammil-iftikhar thanks for the issue, this was fixed on main already by #710

**Comment by muzammil-iftikhar** [comment]
When is the plan to release 0.1.18 ? I actually used scoop to install rio.

**Comment by raphamorim** [comment]
Fixed on 0.2.0 (released today) 👌
