### ISSUE TITLE
Support Shift-Command-Double-Click on macOS

### ISSUE THREAD

**Issue by moenodedev** [raphamorim/rio#727]
Double click to select words
Triple click to select paragraphs

https://scriptingosx.com/obscure/

**Comment by moenodedev** [comment]
A setting to disable hyperlinks would be needed

**Comment by raphamorim** [comment]
Double click to select words
Triple click to select paragraphs

does not work double click to select word for you?
in macos if i click twice it selects the word and three times the whole line, or am i missing anything.

**Comment by moenodedev** [comment]
You're correct. The boundary for Terminal.app includes punctuation and special characters so double click selection works differently.

**Comment by moenodedev** [comment]
The selection behavior isn't intuitive.

An example is trying to double click `link`. `link=https` is selected.
```
> echo link=https://github.com/
```

If you Shift-Command-Double-Click the URL is opened.
