### ISSUE TITLE
Debian packages?

### ISSUE THREAD

**Issue by melroy89** [raphamorim/rio#730]
I think Rio is great!

What about releasing [official Debian and Ubuntu packages](https://raphamorim.io/rio/docs/install/linux/) as well, to increase adoption?

Not all people will build from source or are willing to do so.

Regards,
Melroy

**Comment by raphamorim** [comment]
Hey there @melroy89 👋 thanks for the issue!

Yea, that would be awesome.

I confess that I have no idea about how to request/ask to add Rio in the official packages.

**Comment by melroy89** [comment]
I see. Well you could start with maybe configuring `Cargo.toml` by including `[package.metadata.deb]`?
https://medium.com/rust-programming-language/simplifying-debian-packaging-for-rust-a-step-by-step-guide-for-rust-developers-0457cdb3c81d

You could start with just providing a prebuild binary via the site or if you don't want that. You can also leverage GitHub Release with GitHub Actions to trigger a build.

This would also open-up alternative builds like maybe AppImage or alike.

**Comment by raphamorim** [comment]
Rio already does that https://github.com/raphamorim/rio/releases/tag/v0.1.17

The `.deb` files are included in the release files, however is only building `.deb` for amd64

**Comment by melroy89** [comment]
> Rio already does that https://github.com/raphamorim/rio/releases/tag/v0.1.17
> 
> The `.deb` files are included in the release files, however is only building `.deb` for amd64

Owh! This isn't mentioned on https://raphamorim.io/rio/docs/install/linux/

**Comment by raphamorim** [comment]
Oh maybe should add the info then.

**Comment by raphamorim** [comment]
I submitted also a request to debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1086142

**Comment by raphamorim** [comment]
Added the info on documentation https://raphamorim.io/rio/docs/install/linux/ and will add support for ARM architecture as well #746 

Will close this issue for now, but let's keep track on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1086142 :D

**Comment by melroy89** [comment]
> Added the info on documentation https://raphamorim.io/rio/docs/install/linux/ and will add support for ARM architecture as well #746

Also nice work, I think this will help Debian/Ubuntu users at lot.
