### ISSUE TITLE
Question: Does the Windows installer support `stable-aarch64-pc-windows-msvc`?

### ISSUE THREAD

**Issue by andreban** [raphamorim/rio#735]
I recently acquired an [Snapdragon Elite X](https://www.qualcomm.com/snapdragon/laptops) laptop. I cloned the repo and built Rio for the `stable-aarch64-pc-windows-msvc` architecture and it compiled flawlessly on the first go. I'd like to have Rio properly installed (icons, etc) though and I was wondering if the existing `msi` installer supports the architecture.

**Comment by raphamorim** [comment]
Hey @andreban thanks for the issue,

it should work! But the msi isn’t aarch based. I think the best approach is add it on the github pipeline to build aarch 64 binaries and then add on winget.

is this something you would like to contribute?

**Comment by andreban** [comment]
Looking at the GH workflows I couldn't see anything about winget, which I did find the bits to build the nightly portable and msi installer, for nightly and stable though. Any pointers on this?

**Comment by raphamorim** [comment]
> Looking at the GH workflows I couldn't see anything about winget, which I did find the bits to build the nightly portable and msi installer, for nightly and stable though. Any pointers on this?

That's correct! The only thing you need to implement is actually do a second msi/exe built with stable-aarch64-pc-windows-msvc. 

Then next time I update winget (or any other person) can add a second architecture based on the fragments created for aarch64 https://github.com/microsoft/winget-pkgs/pull/184792/files#diff-8bdee926b80bdf8e2c38209e90ae6377d569c574946712ade2a25774157f3651R20-R23

**Comment by raphamorim** [comment]
Probably rename the current msi and exe to something like `Rio-installer-x64` would be also a good idea

**Comment by andreban** [comment]
Created https://github.com/raphamorim/rio/pull/739 while listening to [Samba do Aviao](https://www.youtube.com/watch?v=_PQ0HxBnUWs).

Here are the test releases in my fork:
 - Nightly: https://github.com/andreban/rio/releases/tag/nightly
 - Release: https://github.com/andreban/rio/releases/tag/v100.0.0

**Comment by raphamorim** [comment]
Wow fantastic! 

> Created https://github.com/raphamorim/rio/pull/739 while listening to [Samba do Aviao](https://www.youtube.com/watch?v=_PQ0HxBnUWs).

Great song ;)

**Comment by andreban** [comment]
I did notice some jank on startup when running the `x86` version using the compatibility layer Windows provides, but the `aarch64` native version is incredibly snappy!

**Comment by raphamorim** [comment]
That's good to know! thank you for sharing, I actually had same experience when I was testing using `aarch64` on linux.

**Comment by raphamorim** [comment]
I will close this issue for now as #739 addressed it, for next version I will add the arm on winget as well

**Comment by raphamorim** [comment]
Thank you for your contribution, I really appreciate 🙏
