### ISSUE TITLE
Failed to build from the latest git version on archlinux

### ISSUE THREAD

**Issue by HSidhiuwhfiunci** [raphamorim/rio#737]
I was using the PKGBUILD from the ABS with some modifications to make it possible to build from the latest git version, and here is the PKGBUILD and makepkg.conf:
[PKGBUILD.txt](https://github.com/user-attachments/files/17534252/PKGBUILD.txt)
[makepkg.conf.txt](https://github.com/user-attachments/files/17534253/makepkg.conf.txt)
It built successfully about one or two weeks ago, but always got failed during these several days.
And the failed log is like this:
[log.txt](https://github.com/user-attachments/files/17534289/log.txt)
(I am using the latest software from the archlinux which has the rust at 1.82.0 [1:1.82.0-2 for the actual rust pkg version from arch])

**Comment by raphamorim** [comment]
Thank you for the issue!

interesting, i had same issue on macos whenever building release target. What fixed for me was use a slightly newer version of clang when compiling

**Comment by orhun** [comment]
You need to build with LTO disabled:

```
options=('!lto')
```

**Comment by raphamorim** [comment]
I am closing this regarding #752 

thank you 🙏
