### ISSUE TITLE
Backend seems to fail and stops displaying text on the terminal 

### ISSUE THREAD

**Issue by Brianalmeida** [raphamorim/rio#743]
Currently, using Fedora 40 Silverblue, and installed the latest version of Rio using cargo and once making some config changes to the config.toml, the terminal will stop displaying text and only shows dots and dashes. Commands still work.

It resets when you kill the terminal and restart it. I will add some screenshots and additional information about my environment:

- OS: Fedora Linux 40.20241029.0 (Silverblue)
- GPU: NVIDIA Corporation GA107GLM [RTX A1000 6GB Laptop GPU] (rev a1)
- Font: Hack
- rioterm 0.1.17

![Screenshot from 2024-10-29 10-32-30](https://github.com/user-attachments/assets/74401b4f-1a91-4795-ab94-e246c6b8dd39)
![Screenshot from 2024-10-29 10-33-41](https://github.com/user-attachments/assets/a908d9c4-d1b2-40d7-9410-5a4a765c5378)
![Screenshot from 2024-10-29 10-43-52](https://github.com/user-attachments/assets/126557cc-4b44-4a9b-bd1d-9994b99ffda0)

Some warning logs from another terminal:
```
2024-10-29T14:32:40.699144Z  WARN rio_backend::performer::handler: [unhandled osc_dispatch]: [['1''3''3'],['C'],] at line 597
2024-10-29T14:32:40.703152Z  WARN rio_backend::performer::handler: [unhandled osc_dispatch]: [['7'],['f''i''l''e'':''/''/''f''e''d''o''r''a''/''v''a''r''/''h''o''m''e''/''b''r''i''a''n''/''.''c''o''n''f''i''g'],] at line 597

```

Edit: Testing to see if the setting `backend = "Automatic"` is the problem or not

**Comment by raphamorim** [comment]
Hey @Brianalmeida thanks for the issue,

Was it working correctly on 0.1.16?

Could you test on main branch if it's reproduceable?

**Comment by Brianalmeida** [comment]
I'll try testing with 0.1.16 and latest to see if it's just a 0.1.17 issue 👀

**Comment by Brianalmeida** [comment]
Seems to be fixed with 0.2.0 🤔. I'll try with some different versions to verify

**Comment by raphamorim** [comment]
Could be it was fixed with wgpu bump

**Comment by Brianalmeida** [comment]
Most likely. Alright then, I think we're good to close this out 😄. If I notice anything else, then I'll update this issue.
