### ISSUE TITLE
`confirm-before-quit = false` still display system dialogue on macOS

### ISSUE THREAD

**Issue by MidKnightXI** [raphamorim/rio#776]
### Context

I enjoy using `cmd + q` on my mac to close programs I don't need, but Rio always display the system dialogue window even when using `confirm-before-quit = false`, is there a way to not display it anymore ?

<img width="416" alt="image" src="https://github.com/user-attachments/assets/8d74bd7a-dce8-44b3-afbc-b5511bea8900">

### Suggestion

If it isn't yet possible, let us configure a way to close it without that system dialogue.

**Comment by MirniWantsSweets** [comment]
hello! I actually had the same issue and here is the solution:
- Go to your rio config file ( or press command + , )
- Cut the line "confirm-before-quit = false"
- Paste it at the top of the file
- Save and restart rio

Explanation:
The toml file format has sections and this specific option is global. So I'm pretty sure you have a line starting with [ and ending in ] somewhere above the "confirm-before-quit = false" line. If you make sure the is no headers ( The [ ] lines ) above this option it will work.

**Comment by raphamorim** [comment]
Yes, I was going to ask about the configuration file because of that.

Thank you for the info/detail @MidKnightXI 🙏

**Comment by MidKnightXI** [comment]
works like a charm ty
