### ISSUE TITLE
Search seems broken in 0.2.0

### ISSUE THREAD

**Issue by svenstaro** [raphamorim/rio#785]
Unless I'm misusing something, search seems to be broken on v0.2.0. I'm launching rio without any config whatsover and I'm observing this behavior: [broken search.webm](https://github.com/user-attachments/assets/48a67b0a-9b20-481d-ae1d-3be66c9f04f9)

As you can see, it either refuses to do anything at all or it will just highlight the first letter, _sometimes_.

**Comment by raphamorim** [comment]
Indeed have a regression on search in 0.2.0 marking it as bug

**Comment by raphamorim** [comment]
Should be fixed on main now, please lemme know if doesn't 🙏
