### ISSUE TITLE
text style: underline 

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#79]
Implement underline feature in the sugarloaf. Rio and Crosswords already provide an information if the square/cell is underlined, would be similar to the way flag is working for bold, italic and bold_italic https://github.com/raphamorim/rio/blob/main/rio/src/screen/state.rs#L193-L203

**Comment by niuez** [comment]
examples from other terminals. left is character underline, right is cursor underline. selection is to visualize glyph min and max y.

alacritty
- character underline and cursor underline is same.
- the bottoms of both underlines are same to the bottom of glyph.
<img width="340" alt="image" src="https://github.com/raphamorim/rio/assets/30189186/3137cb8f-8e68-450f-b7c6-16f6aed5dd8e">

- character underline and cursor underline is not same y position.
- the bottom of cursor underline is the same to the bottom of glyph.
- the bottom of character underline is placed by underline position of font information.
<img width="195" alt="image" src="https://github.com/raphamorim/rio/assets/30189186/3d334da2-21d7-4425-ae6b-c70659ef5744">

the implementation of alacritty is easy. but using font information is strict.

**Comment by raphamorim** [comment]
I like more Alacritty implementation (character underline and cursor underline is same), feels a bit off cursor style that specify underline do a different rendering that a normal text underline. What you think?

**Comment by niuez** [comment]
I have never used underline cursor, so I wanted to hear from anyone with an opinion.
Appearance aside, I think Alacritty's method is easy if we want just implementing underline feature. It can be changed after.

**Comment by raphamorim** [comment]
yup, we can start with alacritty's way and later revisit as well. Although might bump into this same type of problems https://github.com/alacritty/alacritty/issues/3471 (if the cursor doesn't differentiate at least bit)

**Comment by raphamorim** [comment]
Thinking about it, I don't believe we are able to do the second approach until rewrite the font loader. For now implemented Strikethrough and Underline using the sugardecoration but I think we can revisit it later once we have the font loader more stable (need to rewrite it due to #80 and WASM support).

Below some screenshots with underline and strikethrough using same approach as alacritty.

<img width="886" alt="Screenshot 2023-06-05 at 08 56 22" src="https://github.com/raphamorim/rio/assets/3630346/1a5576d5-6508-48cc-a422-d09839397567">
<img width="571" alt="Screenshot 2023-06-05 at 09 00 50" src="https://github.com/raphamorim/rio/assets/3630346/ef9f2ddd-128f-406a-8a55-872fcd62181c">
<img width="677" alt="demo-text-styles" src="https://github.com/raphamorim/rio/assets/3630346/d50dbe03-f931-4ca8-869e-2891461f7889">
