### ISSUE TITLE
Loss of Image Support on v0.2.x ?

### ISSUE THREAD

**Issue by sdamera95** [raphamorim/rio#795]
Image support within Rio seems to have regressed with versions 0.2.0 and 0.2.1. Seemed to work perfectly with v0.1.17. 
Attaching details and screenshots:

Rio version: 0.1.17
installation method: .dmg and Homebrew (tested using both)
OS: MacOS Sequoia 15.1 
imgcat: PyPI
$TERM: xterm-256color

<img width="1511" alt="Screenshot 2024-11-17 at 6 38 28 PM" src="https://github.com/user-attachments/assets/22eb78b5-dc59-45eb-a45c-078ae369f184">

Now, 

Rio version: 0.2.1
installation method(s): .dmg and homebrew (tested using both)

<img width="1511" alt="Screenshot 2024-11-17 at 6 40 48 PM" src="https://github.com/user-attachments/assets/4f2552df-39ce-4b79-89b3-9b093d8e09bf">

**Comment by raphamorim** [comment]
Thank you for the issue @sdamera95 

Good catch, I know the reason (lockfile is using a messed up version of rio sub dependency). Will add this fix to 0.2.2 (probably release by the end of this week 🙏 )

**Comment by raphamorim** [comment]
Could you test using main branch or tomorrow using nightly build if it fixed for you?

I just pushed a fix for that 🙏

**Comment by sdamera95** [comment]
Thank you @raphamorim !

I tested again with the nightly build and it's working again. Screenshot attached:

<img width="1511" alt="Screenshot 2024-11-17 at 7 35 08 PM" src="https://github.com/user-attachments/assets/c1dc3c49-7a78-4766-8e93-7e8cb035c68e">

The issue can be closed now.

**Comment by raphamorim** [comment]
🙏
