### ISSUE TITLE
Cursor being rendered in the wrong position

### ISSUE THREAD

**Issue by kkuriboh** [raphamorim/rio#80]
**it only happens when using a custom font**

When the prompt starts getting longer, the cursor will start being rendered some characters before when it should be at the end

![2023-06-03-080557_344x116_scrot](https://github.com/raphamorim/rio/assets/40146018/1e7987b8-55d5-4bdd-9854-894c8646bdd2)
in this image the cursor was supposed to be at the end of the prompt 

system information:
OS: Artix
backend/protocol: X11
WM: dwm
font: JetBrainsMono Nerd Font

**Comment by raphamorim** [comment]
Thank you for the report.

yea custom font in Rio isn't stable yet. The reason it happens is that sugarloaf is mixing bold/italic/regular dimensions from custom font with the default font. I will be working in make custom fonts stable for the next release (0.0.6), meanwhile marking this issue as bug.

**Comment by raphamorim** [comment]
@kkuriboh would you mind try again with latest main?
Believe this PR fixed the issue https://github.com/raphamorim/rio/pull/83

**Comment by kkuriboh** [comment]
Now the custom fonts are working fine. But unfortunately we got a new problem, now there's a big padding on the right side of the window, before it was just a little over padding on the top.

![2023-06-05-153814_1920x1080_scrot](https://github.com/raphamorim/rio/assets/40146018/0987273a-a6af-47dc-b214-799979a4a6a7)

It's probably because I'm using a WM, but worth reporting. Should I open a new issue and close this one?

**Comment by raphamorim** [comment]
Great to know it fixed @kkuriboh and glad we found a new bug ha,
yes please open a new ticket. Closing this one for now.
