### ISSUE TITLE
font setting for bold, italic and bold italic

### ISSUE THREAD

**Issue by niuez** [raphamorim/rio#81]
One of the reasons why #80 is caused is that the fonts of bold, italic and bold italic be initialize with Cascadia Code. If they could be changed to fonts of the same width as each other, the problem might subside a little.

- I dont know how to load the fonts with specific styles? For example, `Menlo, style=Bold` for bold font.
  - Alacritty has setting font with specific style, but how to do in font_kit.
  - `select_best_match` may be the solution, but I havent tried yet. https://docs.rs/font-kit/latest/font_kit/sources/fontconfig/struct.FontconfigSource.html#method.select_best_match

**Comment by raphamorim** [comment]
Yea, that's exactly the issue. Right now sugarloaf is ignoring other fonts besides regular types, I haven't checked properly how others GPU apps are dealing with it. Saw few implementations from mozilla/servo and https://github.com/wez/wezterm (which doesn't have font-kit as default)
