### ISSUE TITLE
Is displaying images in Rio still supported?

### ISSUE THREAD

**Issue by lbuczkow** [raphamorim/rio#810]
Is displaying images in Rio still supported? It works in 0.1.7 but not in 0.2.1. I use https://iterm2.com/utilities/imgcat on mac.

**Comment by raphamorim** [comment]
It's fixed on main, but haven't bumped a version yet. Will it tonight or tomorrow.

Closing this issue for now but will reopen if 0.2.2 doesn't fix this

**Comment by lbuczkow** [comment]
Ah ok. Thanks!

**Comment by raphamorim** [comment]
Sorry about it 🙏
