### ISSUE TITLE
[Help wanted] Looking for new themes to add in the themes page 

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#82]
Right now we only have two themes in the website. Looking forward to add more themes there :)

<img width="1266" alt="Screenshot 2023-06-03 at 19 19 50" src="https://github.com/raphamorim/rio/assets/3630346/52f31634-a8f3-4be5-8556-ebefd75d6694">

**Comment by kkuriboh** [comment]
Hey, it's pretty easy to convert alacritty themes into rio themes. I'll try to make a script for it and throw into a repo for you.

**Comment by kkuriboh** [comment]
can you tell me if rio supports dimmed and bright foregrounds/backgrounds? i'll just ignore them by now

**Comment by raphamorim** [comment]
Actually I changed my mind about this issue after seeing the docs from hyper.is and alacritty.org that doesn't link to themes unless is built in, I think the best approach might be just let users know is possible to switch themes but not display a gallery in the website.

Also, when start to work in the "customize" page then I think themes page will be obsolete because "customize" page will be a live editor of the Rio terminal using webassembly and configuration toggles (e.g: switch colors).

**Comment by kkuriboh** [comment]
It's fine. Anyways, if someday you seek for new themes, you can check here https://github.com/kkuriboh/allacrity2rio

There are some alacritty theme options that I couldn't find an equivalent for rio, so I just left them empty, overall they didn't seem to affect the themes. I haven't tested most of them, but the ones I've tried seemed to work fine just fine.

**Comment by raphamorim** [comment]
That's great! I saved to use it in the future (when start to work in the customize page)". 👌 🎖️
