### ISSUE TITLE
Lag when ssh into a remote server on a slow connection

### ISSUE THREAD

**Issue by messense** [raphamorim/rio#827]
SSH through a rather slow tailscale connection

![2024-12-01 09 20 22](https://github.com/user-attachments/assets/5545860c-814e-4444-b039-ab4a98eefe88)

Version: 0.2.2

**Comment by raphamorim** [comment]
Hey @messense thanks for the issue!

I have a non related question that could be connected: Did you install Rio terminfo on the server?

**Comment by messense** [comment]
> Did you install Rio terminfo on the server?

No, do I need to install it for Rio to work flawlessly?

**Comment by raphamorim** [comment]
Yes or either set TERM in rio side. More info: https://raphamorim.io/rio/docs/frequently-asked-questions/
