### ISSUE TITLE
Settings editor fails to open when `editor.program` is configured to use `micro` or `hx`

### ISSUE THREAD

**Issue by apcamargo** [raphamorim/rio#832]
When configuring the `editor.program` setting to use alternative editors [`micro`](https://github.com/zyedidia/micro) or [`hx`](https://github.com/helix-editor/helix), the settings editor fails to open via the keyboard shortcut. Attempts to add additional parameters have been unsuccessful.

### Steps to Reproduce
1. Change the `editor` setting to either `micro` or `hx` (after installing them).
2. Attempt to open settings using the keyboard shortcut (`⌘ + ,`).

### Observed Behavior
Settings editor does not open when using `micro` or `hx`.

### Expected Behavior
Settings editor should open with the configured editor.

### Additional Information
- `vim` and `vi` work properly.

**Comment by raphamorim** [comment]
Hey @apcamargo thank you for the issue!!

Could be because you would need to place the full path of `hx`, could you try with the result of `where hx`?

**Comment by apcamargo** [comment]
Good point

```sh
$which hx
/Users/apcamargo/.pixi/bin/hx
```

```toml
[editor]
program = "/Users/apcamargo/.pixi/bin/hx"
```

This worked. `micro` worked as well.

Is there a reason that `nano`, `vi`, and `vim` work without the full path? Maybe `micro` and `hx` would work as well if I put them in `/bin`?

**Comment by raphamorim** [comment]
Yea, mostly is the reason. I think we can fix that by Rio side as well, but Rio would have to login in the shell (to acknowledge the path) then run the `$program`

I will close it for now but if you want to discuss more about it, we can convert this issue on discussion or ping me on Rio discord https://discord.gg/zRvJjmKGwS

**Comment by apcamargo** [comment]
I think I'm ok as things are. It would be good to have this in the documentation somehow (or, better yet, built into Rio at some point)

**Comment by raphamorim** [comment]
I agree 100%, is this something you would like to contribute? ( I think sometimes docs gets better written by people that had actually the issue itself )

**Comment by apcamargo** [comment]
Yep. I can do that! I'm very busy the rest of the week, but I can work on
that right after.

**Comment by raphamorim** [comment]
No worries, feel free to do whenever you have time! thank you 🙏
