### ISSUE TITLE
Exit command not closing the app

### ISSUE THREAD

**Issue by matheus1lva** [raphamorim/rio#87]
Minor suggestion, whenever i type exit on many terminals i expect it to close, rio currently stays on 
![image](https://github.com/raphamorim/rio/assets/831308/0f53fded-4e17-43c7-8b8e-22704e3ade22)

Not a major one, but a nice to have!

Specs: mac os 13.4

**Comment by raphamorim** [comment]
@matheus1lva added the fix for it in f249a45 ⭐
