### ISSUE TITLE
GitHub issue templates

### ISSUE THREAD

**Issue by avelino** [raphamorim/rio#90]
To simplify the contribution we need to think of issue templates to help people open issues, we could have the following templates:
- bug
  - rio version (or git hash)
  - OS
  - problem (describe the problem)
  - reporting steps
  - step by step to reproduce
  - expected behavior
  - other important information
- feature
  - OS
  - describe the feature
  - which terminal has this feature?
- diacussion: link for GitHub discussion

GitHub doc: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by raphamorim** [comment]
Closing this issue since there's no action item and isn't a requirement/wishlist either but feel free to add it 👌
