### ISSUE TITLE
Background colors are not matching when using ranger

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#92]
Kitty and Alacritty:

<img width="324" alt="Screenshot 2023-06-12 at 23 05 32" src="https://github.com/raphamorim/rio/assets/3630346/7cd949b2-e4be-4839-964d-24e8d1fa5b76">
<img width="368" alt="Screenshot 2023-06-12 at 23 05 45" src="https://github.com/raphamorim/rio/assets/3630346/d5b78b0e-92af-43b7-85e0-f4629712aee2">

Rio:

<img width="402" alt="Screenshot 2023-06-12 at 23 06 00" src="https://github.com/raphamorim/rio/assets/3630346/12af56a1-d9ad-4310-bd4e-3d96d42e8a42">

**Comment by ehjmx** [comment]
For me aerc and joe's own editor show the same behavior. 

Joe in Alacritty
![Alacritty](https://github.com/raphamorim/rio/assets/75489369/38ad423c-77a2-4d90-985c-03d3cf9b02ca)

Joe in Rio
![Rio_Terminal](https://github.com/raphamorim/rio/assets/75489369/e8730710-7c0f-4c23-afcc-01224ac2b7fb)

macOS 13.4 
Rio Version 0.0.61

The latest Canary build from 8 hours ago not only changed the Icon but it also broke themes support here on my Mac. In 0.0.61 themes support works so the config file is correct.

**Comment by raphamorim** [comment]
@ehjmx the latest canary introduced breaking changes in the configuration file. The new format https://raphamorim.io/rio/docs/#configuration-file (I will write more about it in the changelog of 0.0.7)

Thanks for letting me know about the joe case, I will take a look on it as well

**Comment by ehjmx** [comment]
@raphamorim I did a test with the new configuration format and themes now work again. 
I especially like that I can now set another shell as zsh as the default shell that Rio launches. 

However there is display glitch when I switch to block for the cursor.

Cursor underscore looks like this
![cursor_as_underscore](https://github.com/raphamorim/rio/assets/75489369/a6635424-cc17-4a0b-9df5-6b2d7316567c)

Cursor as block the block uses two lines
![cursor_as_block](https://github.com/raphamorim/rio/assets/75489369/7928e24b-1717-4879-8e8b-3452c8a91fa0)

Shall I file a new issue for this? 

Thanks for rio. I like using it and I'm thinking about using as my new default terminal but at the moment the heavy development and the changes in the configuration file etc are sort of a deal breaker in my stable work environment

**Comment by raphamorim** [comment]
Fixed in c6f380f 

<img width="712" alt="Screenshot 2023-07-05 at 18 55 58" src="https://github.com/raphamorim/rio/assets/3630346/16484829-7b5e-4f8b-8c4e-2ee22b103dfe">
<img width="668" alt="Screenshot 2023-07-05 at 18 56 20" src="https://github.com/raphamorim/rio/assets/3630346/39531c88-8e04-48ad-b09a-8fd12a0e011b">
