### ISSUE TITLE
Fail to run in X11

### ISSUE THREAD

**Issue by otavio** [raphamorim/rio#93]
I started looking at packaging rio for NixOS (see: https://github.com/NixOS/nixpkgs/pull/237664) and I am getting runtime error from wgpu:

```
thread 'main' panicked at 'Request device: RequestDeviceError', /build/source/sugarloaf/src/context/mod.rs:114:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

Any idea about the cause?

**Comment by raphamorim** [comment]
Hey @otavio thanks for the issue and for packaging it!

Hmm, the way Rio configure devices uses wpgu-rs default values which is incompatible with some hardwares. I added a fallback (4935590) in the device descriptor so should allow the code to run on all possible hardware.

**Comment by otavio** [comment]
Awesome. It works 👍🏼 

![image](https://github.com/raphamorim/rio/assets/25278/ddf2a050-91f3-429e-8dd5-939a824937fa)
