### ISSUE TITLE
Wrong size passed to tmux

### ISSUE THREAD

**Issue by otavio** [raphamorim/rio#98]
Using `tmux` inside `Rio` uses wrong window size. See:

![image](https://github.com/raphamorim/rio/assets/25278/50b434e4-eb26-410b-8bbd-6c5552913ba0)

**Comment by raphamorim** [comment]
Hey @otavio , could you try with latest main? 

<img width="1176" alt="Screenshot 2023-06-18 at 08 34 25" src="https://github.com/raphamorim/rio/assets/3630346/75daf299-4fef-4a72-8822-c79ea92f114c">

Also, another question: Are you using the default font?

**Comment by raphamorim** [comment]
I can confirm this issue in wayland only

![Screenshot 2023-06-18 at 12 03 27](https://github.com/raphamorim/rio/assets/3630346/76180690-7743-45bd-a8f6-77c28307573d)
![Screenshot 2023-06-18 at 12 04 39](https://github.com/raphamorim/rio/assets/3630346/65ffde58-82d9-4e53-9b26-61ba7dbddc13)

**Comment by otavio** [comment]
Fixed on main.
